//! Shared helpers for the golden-vector integration tests.
//!
//! Each integration test binary compiles this module independently, so not
//! every helper is used by every binary.
#![allow(dead_code)]

use std::path::PathBuf;

/// Root of the checked-in cross-language vectors
/// (`coordinator-rs/fixtures/vectors`), generated by
/// `go run ./coordinator-rs/fixtures/gen` from the repository root.
pub fn vectors_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/vectors")
}

pub fn read_vector_file(rel: &str) -> Vec<u8> {
    let path = vectors_dir().join(rel);
    std::fs::read(&path).unwrap_or_else(|e| {
        panic!(
            "missing vector file {} ({e}) — run `go run ./coordinator-rs/fixtures/gen` \
             from the repo root",
            path.display()
        )
    })
}

pub fn from_hex(s: &str) -> Vec<u8> {
    hex::decode(s).expect("valid hex in vector file")
}

pub fn hex32(s: &str) -> [u8; 32] {
    from_hex(s).try_into().expect("32-byte hex value")
}
