// Package prose holds the generated half of the overlay's amber tier: the
// sentences that explain a route or a dependency node, and nothing the graph
// draws.
//
// The overlay's tiers exist because they carry different risk. Clusters,
// namespaces, auth classes and declared tables decide what the map *shows* — a
// wrong value there puts a wrong edge or a wrong boundary on a published page,
// so those are written by a person and gated hard. Prose decides only what the
// page *says* about a node that source already found. That is the half nobody
// keeps up to date, and the half whose gate can only ever ask "is there a
// sentence here", never "is the sentence still true".
//
// So prose is generated in CI and kept in this file, separate from the overlay,
// with two properties the hand-written workflow could not have:
//
//   - Every entry records the hash of the derived facts it describes. When a
//     route gains a gate, changes auth class or starts touching another table,
//     the hash moves and the entry is regenerated. Prose that describes code
//     that no longer exists becomes drift instead of a lie.
//   - Nothing here can create a node, an edge, a cluster or an auth class.
//     Generated text lands in `description`, `details`, `label` and the
//     `depDocs` fields, all of which the renderer prints and the graph ignores.
//     A hallucination costs a wrong sentence, which review catches; it cannot
//     cost a wrong map, which review does not.
//
// Hand-written prose in `overlay.json` always wins over a generated entry for
// the same key, so anything worth saying properly can still be said by a person
// and will not be overwritten.
package prose

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"sort"
	"strings"
)

// Version is the schema version of the generated file. A generator that does
// not understand the file it finds refuses rather than overwriting it.
const Version = 1

// File is the generated prose, keyed as `kind:key` — "route:GET /v1/models",
// "label:mem.warmPool", "node:pg.api_keys".
type File struct {
	Version int              `json:"version"`
	Note    string           `json:"note"`
	Entries map[string]Entry `json:"entries"`
}

// Entry is the prose for one route or node, plus the hash of the derived facts
// it was written from. The hash is what makes the entry falsifiable: see
// Requests.
type Entry struct {
	Kind string `json:"kind"`
	Hash string `json:"hash"`

	// Model records which model wrote the entry, so a bad batch can be found
	// and re-run without guessing.
	Model string `json:"model,omitempty"`

	Description string            `json:"description,omitempty"` // kind "route"
	Details     string            `json:"details,omitempty"`     // kind "route"
	Label       string            `json:"label,omitempty"`       // kind "label"
	Docs        map[string]string `json:"docs,omitempty"`        // kind "node"
}

const note = "Generated by `make -C tools/systemmap enrich`. Prose only — nothing here " +
	"changes what the map draws. Hand-written prose in overlay.json wins over any entry " +
	"here. Each hash covers the derived facts the entry describes; when source moves, the " +
	"entry is regenerated. Edit overlay.json rather than this file."

// Load reads the generated prose. A missing file is not an error: prose is an
// artifact, and a repository that has never run enrichment must still build a
// map — it just reports every route as missing prose, exactly as it does today.
func Load(path string) (*File, error) {
	raw, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return &File{Version: Version, Note: note, Entries: map[string]Entry{}}, nil
	}
	if err != nil {
		return nil, err
	}
	var f File
	dec := json.NewDecoder(strings.NewReader(string(raw)))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&f); err != nil {
		return nil, fmt.Errorf("generated prose %s: %w", path, err)
	}
	if f.Version != Version {
		return nil, fmt.Errorf("generated prose %s: version %d, want %d; delete the file to regenerate it", path, f.Version, Version)
	}
	if f.Entries == nil {
		f.Entries = map[string]Entry{}
	}
	for key, e := range f.Entries {
		if e.Hash == "" {
			return nil, fmt.Errorf("generated prose %s: entry %q has no hash, so nothing can tell whether it still describes its source", path, key)
		}
		if kind, _, ok := strings.Cut(key, ":"); !ok || kind != e.Kind {
			return nil, fmt.Errorf("generated prose %s: entry %q declares kind %q", path, key, e.Kind)
		}
	}
	return &f, nil
}

// Save writes the generated prose with stable key order, so a regenerated file
// diffs only where prose actually changed.
func (f *File) Save(path string) error {
	f.Version = Version
	f.Note = note
	raw, err := json.MarshalIndent(f, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(raw, '\n'), 0o644)
}

// Route returns generated prose for a route key ("GET /v1/models").
func (f *File) Route(key string) (description, details string, ok bool) {
	e, ok := f.Entries[RouteKey(key)]
	if !ok || e.Description == "" {
		return "", "", false
	}
	return e.Description, e.Details, true
}

// Label returns the generated label for a node.
func (f *File) Label(id string) (string, bool) {
	e, ok := f.Entries[LabelKey(id)]
	if !ok || e.Label == "" {
		return "", false
	}
	return e.Label, true
}

// Docs returns the generated depDocs object for a node, marshalled the way the
// overlay would have carried it. The fields are fixed by DocFields: a generated
// object that is missing one, or carries one nobody asked for, is not written.
func (f *File) Docs(id string) (json.RawMessage, bool) {
	e, ok := f.Entries[NodeKey(id)]
	if !ok || len(e.Docs) == 0 {
		return nil, false
	}
	for _, field := range DocFields {
		if strings.TrimSpace(e.Docs[field]) == "" {
			return nil, false
		}
	}
	ordered := make([]string, 0, len(DocFields))
	for _, field := range DocFields {
		val, err := json.Marshal(e.Docs[field])
		if err != nil {
			return nil, false
		}
		ordered = append(ordered, fmt.Sprintf("%q: %s", field, val))
	}
	return json.RawMessage("{" + strings.Join(ordered, ", ") + "}"), true
}

// DocFields are the fields every depDocs entry carries, in the order the
// overlay writes them. Enrichment fills all of them or the entry is rejected:
// a node documented in five of eight fields reads as complete and is not.
var DocFields = []string{
	"overview", "represents", "construction", "access", "concurrency", "lifecycle", "restart", "sources",
}

// Keys. The kind prefix keeps a route named like a node from colliding with it,
// and lets one file hold every kind without a nested structure that diffs badly.
func RouteKey(key string) string { return "route:" + key }
func LabelKey(id string) string  { return "label:" + id }
func NodeKey(id string) string   { return "node:" + id }

// Keys returns the entry keys in sorted order.
func (f *File) Keys() []string {
	out := make([]string, 0, len(f.Entries))
	for k := range f.Entries {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}
