#!/bin/bash
# Canonical provider installer. coordinator/api/install.sh is generated byte-for-byte
# by scripts/sync-install-embed.sh and embedded in the coordinator binary.
set -euo pipefail

# Darkbloom Provider Installer (Swift CLI release v0.5.0+)
# Usage: curl -fsSL https://api.darkbloom.dev/install.sh | bash
#
# This script:
#   1. Fetches the latest signed release from the coordinator
#   2. Downloads the provider app (binaries, metallib, SwiftPM resources)
#   3. Verifies bundle SHA-256 + Apple Developer ID code signature
#   4. Sets up the Secure Enclave identity
#   5. Optionally enrolls in MDM (device attestation)
#   6. Optionally downloads a starter model
#
# Zero prerequisites — just macOS 14+ on Apple Silicon. The Swift CLI
# links mlx-swift directly and ships a colocated mlx.metallib for Metal
# kernels; there is no Python interpreter to install and no inference
# subprocess to spawn.

# This source intentionally retains the placeholder used by the coordinator.
# End users fetch /install.sh from a coordinator, which substitutes its own base
# URL. Direct source execution must set COORD_URL explicitly.
COORD_URL="${COORD_URL:-__DARKBLOOM_COORD_URL__}"
INSTALL_DIR="$HOME/.darkbloom"
BIN_DIR="$INSTALL_DIR/bin"
DARKBLOOM_DESIGNATED_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.provider" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
DARKBLOOM_FAN_HELPER_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.fan-helper" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
FAN_HELPER_REQUIREMENT="$DARKBLOOM_FAN_HELPER_REQUIREMENT"
INSTALL_TEST_MODE=0
PATH_SYMLINK_DIR=""

fail_install() {
    echo "  ✗ $*" >&2
    return 1
}

verify_file_hash() {
    local file=$1
    local expected=$2
    local label=$3
    [ -z "$expected" ] && return 0
    local actual
    actual=$(shasum -a 256 "$file" | cut -d' ' -f1)
    [ "$actual" = "$expected" ] \
        || fail_install "$label hash mismatch (expected $expected, got $actual)."
}

verify_code_requirement() {
    local target=$1
    local deep=$2
    local requirement=$3
    if [ "$deep" = "1" ]; then
        codesign --verify --deep --strict --verbose=2 \
            "-R=$requirement" "$target" >/dev/null 2>&1
    else
        codesign --verify --strict --verbose=2 \
            "-R=$requirement" "$target" >/dev/null 2>&1
    fi
}

verify_staged_app_signature() {
    local app=$1
    local requirement=${2:-$DARKBLOOM_DESIGNATED_REQUIREMENT}
    verify_code_requirement "$app" 1 "$requirement" || {
        fail_install "Staged Darkbloom.app does not satisfy the pinned signature requirement."
        return 1
    }
}

# Stock-macOS binary capability probe. `strings` is an Xcode CLT shim on a
# pristine Mac (it prompts/fails without developer tools), so scan the file
# directly with BSD grep's binary-as-text mode — grep ships in base macOS.
binary_contains_paged_code() {
    local binary=$1
    LC_ALL=C grep -a -q -F 'engine_v2_kv_backend' "$binary"
}

verify_fan_helper_capability() {
    local app=$1
    local executable="$app/Contents/MacOS/darkbloom"
    local marker="$app/Contents/Resources/darkbloom-runtime-capabilities/fan-helper-v1"
    local helper="$app/Contents/Helpers/darkbloom-fan-helper"
    local code_present=0
    local marker_present=0
    local helper_present=0

    LC_ALL=C grep -a -q -F 'darkbloom-fan-helper-v1' "$executable" \
        && code_present=1
    if [ -e "$marker" ] || [ -L "$marker" ]; then marker_present=1; fi
    if [ -e "$helper" ] || [ -L "$helper" ]; then helper_present=1; fi
    [ "$code_present" -eq "$marker_present" ] \
        && [ "$marker_present" -eq "$helper_present" ] || {
        fail_install "Fan-helper CLI capability, marker, and nested helper must be present together."
        return 1
    }
    [ "$marker_present" -eq 1 ] || return 0

    [ -f "$marker" ] && [ ! -L "$marker" ] \
        && [ "$(tr -d '[:space:]' < "$marker")" = "1" ] || {
        fail_install "Fan-helper capability marker is invalid."
        return 1
    }
    [ -f "$helper" ] && [ ! -L "$helper" ] && [ -x "$helper" ] || {
        fail_install "Bundled fan helper must be a regular executable, not a symlink."
        return 1
    }
    [ "$(stat -f '%Lp' "$helper" 2>/dev/null || true)" = "755" ] || {
        fail_install "Bundled fan helper must have mode 0755."
        return 1
    }
    verify_code_requirement "$helper" 0 "$FAN_HELPER_REQUIREMENT" || {
        fail_install "Bundled fan helper does not satisfy the pinned helper signature requirement."
        return 1
    }
}

verify_staged_app() {
    local app=$1
    local executable="$app/Contents/MacOS/darkbloom"
    local marker="$app/Contents/Resources/darkbloom-runtime-capabilities/paged-kernel-v1"

    if [ "$INSTALL_TEST_MODE" = "1" ]; then
        codesign --verify --deep --strict --verbose=2 "$app" >/dev/null 2>&1 || {
            fail_install "Strict code-signature verification failed for staged Darkbloom.app."
            return 1
        }
    else
        verify_staged_app_signature "$app" || return 1
    fi
    verify_fan_helper_capability "$app" || return 1

    local code_has_paged=0
    local marker_present=0
    binary_contains_paged_code "$executable" && code_has_paged=1
    [ -f "$marker" ] && marker_present=1
    [ "$code_has_paged" -eq "$marker_present" ] || {
        if [ "$code_has_paged" -eq 1 ]; then
            fail_install "Paged-capable staged app is missing its signed capability marker."
        else
            fail_install "Staged app advertises paged capability without paged runtime code."
        fi
        return 1
    }
    [ "$marker_present" -eq 1 ] || return 0
    [ "$(tr -d '[:space:]' < "$marker")" = "1" ] || {
        fail_install "Paged runtime capability marker is invalid."
        return 1
    }

    shopt -s nullglob
    local paged_resources=(
        "$app/Contents/Resources"/*.bundle/pagedattention.metal
    )
    local expected_resource="$app/Contents/Resources/mlx-swift-lm_MLXLMCommon.bundle/pagedattention.metal"
    [ "${#paged_resources[@]}" -eq 1 ] \
        && [ "${paged_resources[0]}" = "$expected_resource" ] \
        && [ -s "$expected_resource" ] \
        || {
            fail_install "Paged-capable staged app requires exactly one sealed MLXLMCommon pagedattention.metal."
            return 1
        }

    DARKBLOOM_NO_UPDATE_CHECK=1 \
        DARKBLOOM_GEMMA4_PREFILL_CHUNK_EVAL=18 \
        MLX_GEMMA4_FUSED_WEIGHTED_UNSORT=1 \
        MLX_GATHER_QMM_EXPERT_SLICES=1 \
        "$executable" runtime-smoke >/dev/null \
        || {
            fail_install "Packaged paged-kernel runtime smoke failed."
            return 1
        }
}

verify_staged_app_payload() {
    local app=$1
    local binary_hash=$2
    local metallib_hash=$3
    local app_bin="$app/Contents/MacOS"
    [ -n "$binary_hash" ] && [ -n "$metallib_hash" ] || {
        fail_install "App releases require binary_hash and metallib_hash."
        return 1
    }
    verify_file_hash "$app_bin/darkbloom" "$binary_hash" "App binary" \
        && verify_file_hash "$app_bin/mlx.metallib" "$metallib_hash" "App metallib"
}

commit_staged_app() {
    local staged_app=$1
    local install_dir=$2
    local backup="$install_dir/.install-backup-$$-$RANDOM"
    local destination="$install_dir/Darkbloom.app"
    local had_previous=0
    mkdir -p "$backup" "$install_dir/bin"

    if [ -d "$destination" ]; then
        mv "$destination" "$backup/Darkbloom.app" || {
            rm -rf "$backup"
            return 1
        }
        had_previous=1
    fi
    if ! mv "$staged_app" "$destination"; then
        [ "$had_previous" -eq 1 ] \
            && mv "$backup/Darkbloom.app" "$destination" 2>/dev/null || true
        rm -rf "$backup"
        return 1
    fi

    local app_bin="$destination/Contents/MacOS"
    if ! ln -sfn "../Darkbloom.app/Contents/MacOS/darkbloom" "$install_dir/bin/darkbloom" \
        || ! ln -sfn "../Darkbloom.app/Contents/MacOS/darkbloom-enclave" "$install_dir/bin/darkbloom-enclave" \
        || ! ln -sfn "../Darkbloom.app/Contents/MacOS/mlx.metallib" "$install_dir/bin/mlx.metallib" \
        || ! ln -sfn "darkbloom-enclave" "$install_dir/bin/eigeninference-enclave"
    then
        rm -rf "$destination"
        [ "$had_previous" -eq 1 ] \
            && mv "$backup/Darkbloom.app" "$destination" 2>/dev/null || true
        rm -rf "$backup"
        return 1
    fi
    chmod +x "$app_bin/darkbloom" "$app_bin/darkbloom-enclave"
    rm -rf "$backup"
}

commit_staged_flat_bundle() {
    local staged_bin=$1
    local install_dir=$2
    local backup="$install_dir/.install-backup-$$-$RANDOM"
    local destination="$install_dir/bin"
    mkdir -p "$backup"
    if [ -d "$destination" ]; then
        mv "$destination" "$backup/bin" || {
            rm -rf "$backup"
            return 1
        }
    fi
    if ! mv "$staged_bin" "$destination"; then
        [ -d "$backup/bin" ] && mv "$backup/bin" "$destination" 2>/dev/null || true
        rm -rf "$backup"
        return 1
    fi
    chmod +x "$destination/darkbloom" "$destination/darkbloom-enclave"
    ln -sfn "darkbloom-enclave" "$destination/eigeninference-enclave"
    rm -rf "$backup"
}

install_bundle_atomically() {
    local archive=$1
    local install_dir=$2
    local binary_hash=${3:-}
    local metallib_hash=${4:-}
    local stage="$install_dir/.install-staging-$$-$RANDOM"
    rm -rf "$stage"
    mkdir -p "$stage"
    if ! tar xzf "$archive" -C "$stage"; then
        rm -rf "$stage"
        return 1
    fi

    local flat_bin="$stage/bin"
    [ -f "$flat_bin/darkbloom" ] \
        && [ -f "$flat_bin/darkbloom-enclave" ] \
        && [ -f "$flat_bin/mlx.metallib" ] \
        || {
            rm -rf "$stage"
            fail_install "Release bundle is missing required flat verifier files."
            return 1
        }
    verify_file_hash "$flat_bin/darkbloom" "$binary_hash" "Binary" || {
        rm -rf "$stage"
        return 1
    }
    verify_file_hash "$flat_bin/mlx.metallib" "$metallib_hash" "Metallib" || {
        rm -rf "$stage"
        return 1
    }

    if [ -d "$stage/Darkbloom.app" ]; then
        verify_staged_app_payload \
            "$stage/Darkbloom.app" "$binary_hash" "$metallib_hash" || {
            rm -rf "$stage"
            return 1
        }
        verify_staged_app "$stage/Darkbloom.app" || {
            rm -rf "$stage"
            return 1
        }
        commit_staged_app "$stage/Darkbloom.app" "$install_dir" || {
            rm -rf "$stage"
            fail_install "Atomic app swap failed; previous install was restored."
            return 1
        }
    else
        if [ "$INSTALL_TEST_MODE" = "1" ]; then
            codesign --verify --strict --verbose=2 "$flat_bin/darkbloom" >/dev/null 2>&1 || {
                rm -rf "$stage"
                fail_install "Strict signature verification failed for legacy flat artifact."
                return 1
            }
        else
            verify_code_requirement \
                "$flat_bin/darkbloom" 0 "$DARKBLOOM_DESIGNATED_REQUIREMENT" || {
                rm -rf "$stage"
                fail_install "Legacy flat artifact does not satisfy the pinned signature requirement."
                return 1
            }
        fi
        commit_staged_flat_bundle "$flat_bin" "$install_dir" || {
            rm -rf "$stage"
            fail_install "Atomic flat-bundle swap failed; previous install was restored."
            return 1
        }
    fi
    rm -rf "$stage"
}

# PATH setup. `curl | bash` cannot change the parent shell, so the installer
# (1) writes ~/.darkbloom/bin into every common startup file a new terminal
# will actually read, and (2) tries a symlink into a directory already on
# PATH (/usr/local/bin, Homebrew) so `darkbloom` works in the current
# session when that write is allowed. Writing only ~/.zshrc left bash login
# shells (macOS Terminal after chsh/bash) with "command not found".
path_contains() {
    case ":$PATH:" in
        *":$1:"*) return 0 ;;
        *) return 1 ;;
    esac
}

ensure_trailing_newline() {
    local file=$1
    local last
    [ -s "$file" ] || return 0
    last=$(tail -c 1 "$file" 2>/dev/null || true)
    [ -z "$last" ] || [ "$last" = $'\n' ] || printf '\n' >> "$file"
}

ensure_path_in_file() {
    local file=$1
    local path_line='export PATH="$HOME/.darkbloom/bin:$PATH"'
    if [ -f "$file" ] && grep -Fqx "$path_line" "$file" 2>/dev/null; then
        return 0
    fi
    mkdir -p "$(dirname "$file")"
    ensure_trailing_newline "$file"
    printf '\n# Darkbloom\n%s\n' "$path_line" >> "$file"
}

ensure_path_in_fish() {
    local file=$1
    local path_line='set -gx PATH "$HOME/.darkbloom/bin" $PATH'
    if [ -f "$file" ] && grep -Fqx "$path_line" "$file" 2>/dev/null; then
        return 0
    fi
    mkdir -p "$(dirname "$file")"
    ensure_trailing_newline "$file"
    printf '\n# Darkbloom\n%s\n' "$path_line" >> "$file"
}

setup_path_symlinks() {
    PATH_SYMLINK_DIR=""
    local candidates dest rest
    if [ -n "${DARKBLOOM_PATH_LINK_CANDIDATES+x}" ]; then
        candidates="$DARKBLOOM_PATH_LINK_CANDIDATES"
    else
        candidates="/usr/local/bin:/opt/homebrew/bin"
    fi
    rest="$candidates"
    while [ -n "$rest" ]; do
        dest="${rest%%:*}"
        if [ "$rest" = "$dest" ]; then
            rest=""
        else
            rest="${rest#*:}"
        fi
        [ -n "$dest" ] || continue
        mkdir -p "$dest" 2>/dev/null || true
        if [ -d "$dest" ] && [ -w "$dest" ] \
            && ln -sfn "$BIN_DIR/darkbloom" "$dest/darkbloom" 2>/dev/null
        then
            if path_contains "$dest"; then
                PATH_SYMLINK_DIR="$dest"
                return 0
            fi
        fi
    done
}

setup_shell_path() {
    PATH_SYMLINK_DIR=""
    mkdir -p "$BIN_DIR"
    setup_path_symlinks

    # zsh is the macOS default. Always create ~/.zshrc so a stock Terminal
    # window finds darkbloom after install.
    ensure_path_in_file "$HOME/.zshrc"
    [ -f "$HOME/.zprofile" ] && ensure_path_in_file "$HOME/.zprofile"

    # bash interactive (bash launched from zsh, Linux, some IDEs).
    ensure_path_in_file "$HOME/.bashrc"

    # Bash login reads the first of ~/.bash_profile, ~/.bash_login,
    # ~/.profile — never ~/.zshrc. Create bash_profile only when none of
    # those exist, so we do not shadow an existing login file.
    if [ -f "$HOME/.bash_profile" ]; then
        ensure_path_in_file "$HOME/.bash_profile"
    elif [ -f "$HOME/.bash_login" ]; then
        ensure_path_in_file "$HOME/.bash_login"
    elif [ -f "$HOME/.profile" ]; then
        ensure_path_in_file "$HOME/.profile"
    else
        ensure_path_in_file "$HOME/.bash_profile"
    fi
    [ -f "$HOME/.bash_login" ] && ensure_path_in_file "$HOME/.bash_login"
    [ -f "$HOME/.profile" ] && ensure_path_in_file "$HOME/.profile"

    if [ -f "$HOME/.config/fish/config.fish" ] \
        || [ "$(basename "${SHELL:-}")" = "fish" ]; then
        ensure_path_in_fish "$HOME/.config/fish/config.fish"
    fi

    export PATH="$BIN_DIR:$PATH"
}

if [ "${1:-}" = "--verify-staged-app-signature-test" ]; then
    [ "$#" -eq 3 ] || {
        echo "usage: $0 --verify-staged-app-signature-test <app> <requirement>" >&2
        exit 64
    }
    verify_staged_app_signature "$2" "$3"
    exit $?
fi

if [ "${1:-}" = "--install-bundle-test" ]; then
    { [ "$#" -eq 5 ] || [ "$#" -eq 6 ]; } || {
        echo "usage: $0 --install-bundle-test <archive> <install-dir> <binary-hash> <metallib-hash> [fan-helper-requirement]" >&2
        exit 64
    }
    INSTALL_TEST_MODE=1
    if [ "$#" -eq 6 ]; then FAN_HELPER_REQUIREMENT=$6; fi
    install_bundle_atomically "$2" "$3" "$4" "$5"
    exit $?
fi

if [ "${1:-}" = "--setup-path-test" ]; then
    if [ -n "${2:-}" ]; then
        HOME="$2"
        INSTALL_DIR="$HOME/.darkbloom"
        BIN_DIR="$INSTALL_DIR/bin"
    fi
    # Opt-in only: an unset override skips /usr/local/bin so CI never
    # writes host PATH directories. Live installs use the default
    # candidate list inside setup_shell_path.
    if [ -z "${DARKBLOOM_PATH_LINK_CANDIDATES+x}" ]; then
        DARKBLOOM_PATH_LINK_CANDIDATES=""
    fi
    setup_shell_path
    exit $?
fi

# Detect interactive vs piped (curl | bash).
if [ -t 0 ]; then
    INTERACTIVE=true
else
    INTERACTIVE=false
fi

echo "╔══════════════════════════════════════════════╗"
echo "║  Darkbloom — Private AI on Verified Macs     ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── Pre-flight checks ───────────────────────────────────────
if [ "$(uname)" != "Darwin" ]; then
    echo "Error: Darkbloom requires macOS with Apple Silicon."
    exit 1
fi
if [ "$(uname -m)" != "arm64" ]; then
    echo "Error: Darkbloom requires Apple Silicon (arm64)."
    exit 1
fi

CHIP=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "Apple Silicon")
MEM=$(sysctl -n hw.memsize 2>/dev/null | awk '{printf "%.0f", $1/1073741824}')
MACOS=$(sw_vers -productVersion 2>/dev/null || echo "?")
echo "  $CHIP · ${MEM}GB · macOS $MACOS"
echo ""

# ─── Step 1: Fetch latest release ────────────────────────────
echo "→ [1/5] Fetching latest release from $COORD_URL ..."

RELEASE_JSON=$(curl -fsSL "$COORD_URL/v1/releases/latest" 2>/dev/null || echo "")
if [ -z "$RELEASE_JSON" ]; then
    echo "  ✗ Could not reach coordinator at $COORD_URL"
    echo "    Check your internet connection and try again."
    exit 1
fi

# Extract JSON string fields with sed — no python3 needed (no Xcode CLT prompt).
json_val() { echo "$1" | sed -n "s/.*\"$2\":\"\([^\"]*\)\".*/\1/p"; }
BUNDLE_URL=$(json_val "$RELEASE_JSON" url)
BUNDLE_HASH=$(json_val "$RELEASE_JSON" bundle_hash)
BINARY_HASH=$(json_val "$RELEASE_JSON" binary_hash)
METALLIB_HASH=$(json_val "$RELEASE_JSON" metallib_hash)
VERSION=$(json_val "$RELEASE_JSON" version)
BACKEND=$(json_val "$RELEASE_JSON" backend)

if [ -z "$BUNDLE_URL" ] || [ -z "$BUNDLE_HASH" ] || [ -z "$VERSION" ]; then
    echo "  ✗ Coordinator response missing required fields (url / bundle_hash / version)."
    echo "    Raw response: $RELEASE_JSON"
    exit 1
fi

echo "  Version: $VERSION"
echo "  Backend: ${BACKEND:-mlx-swift}"
echo "  Signed by: Developer ID Application: Eigen Labs, Inc."
echo ""

# ─── Step 2: Download + verify bundle ────────────────────────
echo "→ [2/5] Downloading Darkbloom v${VERSION}..."
mkdir -p "$INSTALL_DIR" "$BIN_DIR"

TARBALL="/tmp/darkbloom-bundle.tar.gz"
curl -f#L "$BUNDLE_URL" -o "$TARBALL"

ACTUAL_HASH=$(shasum -a 256 "$TARBALL" | cut -d' ' -f1)
if [ "$ACTUAL_HASH" != "$BUNDLE_HASH" ]; then
    echo ""
    echo "  ✗ Bundle hash mismatch — refusing to install possibly-tampered binary."
    echo "    Expected: $BUNDLE_HASH"
    echo "    Got:      $ACTUAL_HASH"
    rm -f "$TARBALL"
    exit 1
fi
echo "  Bundle hash verified ✓"

echo "  Staging and verifying the complete app before touching the live install ..."
if ! install_bundle_atomically "$TARBALL" "$INSTALL_DIR" "$BINARY_HASH" "$METALLIB_HASH"; then
    rm -f "$TARBALL"
    echo "  Existing installation was left unchanged."
    exit 1
fi
rm -f "$TARBALL"
echo "  Strict signature, runtime resources, and atomic swap verified ✓"

setup_shell_path
echo "  Binaries installed ✓"
if [ -n "$PATH_SYMLINK_DIR" ]; then
    echo "  On PATH via $PATH_SYMLINK_DIR/darkbloom"
else
    echo "  Added ~/.darkbloom/bin to PATH in zsh/bash startup files"
fi

# ─── Migrate from old installs ───────────────────────────────
# Migration chain: ~/.dginf → ~/.eigeninference → ~/.darkbloom
for OLD_DIR in "$HOME/.dginf" "$HOME/.eigeninference"; do
    if [ -d "$OLD_DIR" ] && [ ! -L "$OLD_DIR" ]; then
        echo ""
        echo "  Migrating from $OLD_DIR..."
        for f in enclave_key.data wallet_key auth_token; do
            [ -f "$OLD_DIR/$f" ] && cp -n "$OLD_DIR/$f" "$INSTALL_DIR/$f" 2>/dev/null || true
        done
        # Symlink old path so stragglers still work, then drop the old python/
        # subtree -- the Swift release no longer needs it.
        ln -sfn "$INSTALL_DIR" "$OLD_DIR" 2>/dev/null || true
        echo "  Migration complete ✓"
    fi
done

# ─── Step 3: Secure Enclave identity ─────────────────────────
echo ""
echo "→ [3/5] Provisioning Secure Enclave identity..."
if "$BIN_DIR/darkbloom-enclave" info >/dev/null 2>&1; then
    echo "  Secure Enclave ✓ (P-256 key generated)"
else
    echo "  Secure Enclave ⚠ (not available on this hardware; provider will run with reduced trust)"
fi

# ─── Step 4: Enrollment + device attestation ─────────────────
echo ""
echo "→ [4/5] Enrollment + device attestation..."

ALREADY_ENROLLED=false
if profiles status -type enrollment 2>&1 | grep -q "MDM enrollment: Yes"; then
    ALREADY_ENROLLED=true
fi

if [ "$ALREADY_ENROLLED" = true ]; then
    echo "  Already enrolled ✓"
else
    echo "  Requesting enrollment profile from coordinator..."
    PROFILE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/Darkbloom-Enroll.XXXXXX")"
    PROFILE_PATH="$PROFILE_DIR/Darkbloom-Enroll.mobileconfig"
    if curl -fsSL -X POST "$COORD_URL/v1/enroll" \
        -H "Content-Type: application/json" \
        -d '{}' \
        -o "$PROFILE_PATH" 2>/dev/null; then
        echo ""
        echo "  ┌──────────────────────────────────────────────────┐"
        echo "  │ ACTION REQUIRED: Install the enrollment profile  │"
        echo "  │                                                  │"
        echo "  │ This profile lets the coordinator verify:        │"
        echo "  │  • SIP, Secure Boot, system integrity            │"
        echo "  │  • Your Secure Enclave is genuine Apple silicon  │"
        echo "  │  • Device identity signed by Apple's Root CA     │"
        echo "  │                                                  │"
        echo "  │ Darkbloom CANNOT erase, lock, or control         │"
        echo "  │ your Mac. Remove anytime in System Settings.     │"
        echo "  └──────────────────────────────────────────────────┘"
        echo ""
        open "$PROFILE_PATH"
        sleep 1
        open "x-apple.systempreferences:com.apple.Profiles-Settings.extension"

        echo "  System Settings opened — click Install and enter your password."
        if [ "$INTERACTIVE" = true ]; then
            echo ""
            read -p "  Press Enter once you have installed the profile..." || true
        else
            echo "  After installing, the provider will verify on first start."
            sleep 3
        fi
        if profiles status -type enrollment 2>&1 | grep -q "MDM enrollment: Yes"; then
            echo "  Enrollment verified ✓"
        else
            echo "  Enrollment pending ⚠ (complete it in System Settings, or run: darkbloom enroll)"
        fi
    else
        echo "  Enrollment ⚠ (coordinator unreachable — enroll later with: darkbloom enroll)"
    fi
fi

# ─── Step 5: Optional starter model ──────────────────────────
echo ""
echo "→ [5/5] Inference model..."

CATALOG_JSON=$(curl -fsSL "$COORD_URL/v1/models/catalog?type=text" 2>/dev/null || echo "")

if [ -n "$CATALOG_JSON" ]; then
    if [ "$INTERACTIVE" = true ]; then
        echo ""
        echo "  Available text models:"
        echo "$CATALOG_JSON" \
          | tr ',' '\n' \
          | sed -n 's/.*"id":"\([^"]*\)".*"display_name":"\([^"]*\)".*"size_gb":\([0-9.]*\).*"min_ram_gb":\([0-9]*\).*/  • \2  ~\3 GB  (≥\4 GB RAM)  [\1]/p' \
          | head -20
        echo ""
        echo "  Download a model with:"
        echo "    darkbloom models download <id>"
    else
        echo "  Run interactively to pick a starter model:"
        echo "    curl -fsSL $COORD_URL/install.sh | bash -s"
        echo "  Or list the catalog with:  darkbloom models catalog"
    fi
else
    echo "  Could not fetch model catalog (continuing anyway)."
fi

# ─── Done ────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  Install complete                            ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  Next steps:"
if [ -z "$PATH_SYMLINK_DIR" ]; then
    echo "    export PATH=\"\$HOME/.darkbloom/bin:\$PATH\"   # this terminal"
    echo ""
fi
echo "    darkbloom doctor             # verify the system is ready"
echo "    darkbloom models catalog     # browse available models"
echo "    darkbloom models download <id>"
echo "    darkbloom login              # link this Mac to your account"
echo "    darkbloom start              # serve inference (interactive picker)"
echo ""
