#!/bin/bash
# Canonical provider installer. coordinator/api/install.sh is generated byte-for-byte
# by scripts/sync-install-embed.sh and embedded in the coordinator binary.
set -euo pipefail

# Darkbloom Provider Installer (Swift CLI release v0.5.0+)
# Usage: curl -fsSL https://api.darkbloom.dev/install.sh | bash
#
# This script:
#   1. Fetches the latest signed release from the coordinator
#   2. Downloads Darkbloom.app (SwiftUI DarkbloomApp main executable PLUS the
#      co-bundled provider CLI, enclave helper, metallib, SwiftPM resources)
#      and installs it at the stable managed-update path
#      ~/.darkbloom/Darkbloom.app
#   3. Verifies bundle SHA-256 + Apple Developer ID code signature
#   4. Sets up the Secure Enclave identity
#   5. Optionally enrolls in MDM (device attestation)
#   6. Optionally downloads a starter model
#   7. Offers to launch the app (interactive terminals only)
#
# Zero prerequisites — just macOS 14+ on Apple Silicon. The Swift CLI
# links mlx-swift directly and ships a colocated mlx.metallib for Metal
# kernels; there is no Python interpreter to install and no inference
# subprocess to spawn.

# This source intentionally retains the placeholder used by the coordinator.
# End users fetch /install.sh from a coordinator, which substitutes its own base
# URL. Direct source execution must set COORD_URL explicitly.
COORD_URL="${COORD_URL:-__DARKBLOOM_COORD_URL__}"
INSTALL_DIR="$HOME/.darkbloom"
BIN_DIR="$INSTALL_DIR/bin"
DARKBLOOM_DESIGNATED_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.provider" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
DARKBLOOM_FAN_HELPER_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.fan-helper" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
FAN_HELPER_REQUIREMENT="$DARKBLOOM_FAN_HELPER_REQUIREMENT"
INSTALL_TEST_MODE=0

fail_install() {
    echo "  ✗ $*" >&2
    return 1
}

verify_file_hash() {
    local file=$1
    local expected=$2
    local label=$3
    [ -z "$expected" ] && return 0
    local actual
    actual=$(shasum -a 256 "$file" | cut -d' ' -f1)
    [ "$actual" = "$expected" ] \
        || fail_install "$label hash mismatch (expected $expected, got $actual)."
}

verify_code_requirement() {
    local target=$1
    local deep=$2
    local requirement=$3
    if [ "$deep" = "1" ]; then
        codesign --verify --deep --strict --verbose=2 \
            "-R=$requirement" "$target" >/dev/null 2>&1
    else
        codesign --verify --strict --verbose=2 \
            "-R=$requirement" "$target" >/dev/null 2>&1
    fi
}

verify_staged_app_signature() {
    local app=$1
    local requirement=${2:-$DARKBLOOM_DESIGNATED_REQUIREMENT}
    verify_code_requirement "$app" 1 "$requirement" || {
        fail_install "Staged Darkbloom.app does not satisfy the pinned signature requirement."
        return 1
    }
}

# Stock-macOS binary capability probe. `strings` is an Xcode CLT shim on a
# pristine Mac (it prompts/fails without developer tools), so scan the file
# directly with BSD grep's binary-as-text mode — grep ships in base macOS.
binary_contains_paged_code() {
    local binary=$1
    LC_ALL=C grep -a -q -F 'engine_v2_kv_backend' "$binary"
}

verify_fan_helper_capability() {
    local app=$1
    local executable="$app/Contents/MacOS/darkbloom"
    local marker="$app/Contents/Resources/darkbloom-runtime-capabilities/fan-helper-v1"
    local helper="$app/Contents/Helpers/darkbloom-fan-helper"
    local code_present=0
    local marker_present=0
    local helper_present=0

    LC_ALL=C grep -a -q -F 'darkbloom-fan-helper-v1' "$executable" \
        && code_present=1
    if [ -e "$marker" ] || [ -L "$marker" ]; then marker_present=1; fi
    if [ -e "$helper" ] || [ -L "$helper" ]; then helper_present=1; fi
    [ "$code_present" -eq "$marker_present" ] \
        && [ "$marker_present" -eq "$helper_present" ] || {
        fail_install "Fan-helper CLI capability, marker, and nested helper must be present together."
        return 1
    }
    [ "$marker_present" -eq 1 ] || return 0

    [ -f "$marker" ] && [ ! -L "$marker" ] \
        && [ "$(tr -d '[:space:]' < "$marker")" = "1" ] || {
        fail_install "Fan-helper capability marker is invalid."
        return 1
    }
    [ -f "$helper" ] && [ ! -L "$helper" ] && [ -x "$helper" ] || {
        fail_install "Bundled fan helper must be a regular executable, not a symlink."
        return 1
    }
    [ "$(stat -f '%Lp' "$helper" 2>/dev/null || true)" = "755" ] || {
        fail_install "Bundled fan helper must have mode 0755."
        return 1
    }
    verify_code_requirement "$helper" 0 "$FAN_HELPER_REQUIREMENT" || {
        fail_install "Bundled fan helper does not satisfy the pinned helper signature requirement."
        return 1
    }
}

verify_staged_app() {
    local app=$1
    local executable="$app/Contents/MacOS/darkbloom"
    local marker="$app/Contents/Resources/darkbloom-runtime-capabilities/paged-kernel-v1"

    if [ "$INSTALL_TEST_MODE" = "1" ]; then
        codesign --verify --deep --strict --verbose=2 "$app" >/dev/null 2>&1 || {
            fail_install "Strict code-signature verification failed for staged Darkbloom.app."
            return 1
        }
    else
        verify_staged_app_signature "$app" || return 1
    fi
    verify_fan_helper_capability "$app" || return 1

    local code_has_paged=0
    local marker_present=0
    binary_contains_paged_code "$executable" && code_has_paged=1
    [ -f "$marker" ] && marker_present=1
    [ "$code_has_paged" -eq "$marker_present" ] || {
        if [ "$code_has_paged" -eq 1 ]; then
            fail_install "Paged-capable staged app is missing its signed capability marker."
        else
            fail_install "Staged app advertises paged capability without paged runtime code."
        fi
        return 1
    }
    [ "$marker_present" -eq 1 ] || return 0
    [ "$(tr -d '[:space:]' < "$marker")" = "1" ] || {
        fail_install "Paged runtime capability marker is invalid."
        return 1
    }

    shopt -s nullglob
    local paged_resources=(
        "$app/Contents/Resources"/*.bundle/pagedattention.metal
    )
    local expected_resource="$app/Contents/Resources/mlx-swift-lm_MLXLMCommon.bundle/pagedattention.metal"
    [ "${#paged_resources[@]}" -eq 1 ] \
        && [ "${paged_resources[0]}" = "$expected_resource" ] \
        && [ -s "$expected_resource" ] \
        || {
            fail_install "Paged-capable staged app requires exactly one sealed MLXLMCommon pagedattention.metal."
            return 1
        }

    DARKBLOOM_NO_UPDATE_CHECK=1 \
        DARKBLOOM_GEMMA4_PREFILL_CHUNK_EVAL=18 \
        MLX_GEMMA4_FUSED_WEIGHTED_UNSORT=1 \
        MLX_GATHER_QMM_EXPERT_SLICES=1 \
        "$executable" runtime-smoke >/dev/null \
        || {
            fail_install "Packaged paged-kernel runtime smoke failed."
            return 1
        }
}

verify_staged_app_payload() {
    local app=$1
    local binary_hash=$2
    local metallib_hash=$3
    local app_bin="$app/Contents/MacOS"
    [ -n "$binary_hash" ] && [ -n "$metallib_hash" ] || {
        fail_install "App releases require binary_hash and metallib_hash."
        return 1
    }
    verify_file_hash "$app_bin/darkbloom" "$binary_hash" "App binary" \
        && verify_file_hash "$app_bin/mlx.metallib" "$metallib_hash" "App metallib"
}

# ~/.darkbloom/Darkbloom.app ownership: release bundles have always carried
# OUR id (io.darkbloom.provider — first the CLI wrapper, now the combined
# app); dev loops via script/build_and_run.sh produce the unsigned dev build
# (dev.darkbloom.app). Both are replaced in place. Anything else at that path
# is NOT ours (user-copied app, other tooling, corrupt bundle without an
# Info.plist): preserve it beside the install dir and warn, never clobber it.
existing_bundle_is_ours() {
    local app=$1
    local id
    [ -d "$app" ] && [ ! -L "$app" ] || return 1
    id=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' \
        "$app/Contents/Info.plist" 2>/dev/null || true)
    case "$id" in
        io.darkbloom.provider)
            read_canonical_app_version "$app" >/dev/null || return 1
            if [ "$INSTALL_TEST_MODE" = "1" ]; then
                codesign --verify --deep --strict --verbose=2 \
                    "$app" >/dev/null 2>&1
            else
                verify_code_requirement \
                    "$app" 1 "$DARKBLOOM_DESIGNATED_REQUIREMENT"
            fi
            ;;
        dev.darkbloom.app) return 0 ;;
        *) return 1 ;;
    esac
}

foreign_bundle_destination() {
    local install_dir=$1
    local base
    base="$install_dir/Darkbloom.app.foreign-$(date +%Y%m%d-%H%M%S)"
    local preserved=$base
    local suffix=1
    while [ -e "$preserved" ] || [ -L "$preserved" ]; do
        preserved="${base}-${suffix}"
        suffix=$((suffix + 1))
    done
    printf '%s\n' "$preserved"
}

install_test_fault() {
    local point=$1
    [ "$INSTALL_TEST_MODE" = "1" ] \
        && [ "${DARKBLOOM_INSTALL_TEST_FAIL_POINT:-}" = "$point" ]
}

install_test_crash() {
    local point=$1
    if [ "$INSTALL_TEST_MODE" = "1" ] \
        && [ "${DARKBLOOM_INSTALL_TEST_CRASH_POINT:-}" = "$point" ]
    then
        kill -KILL "$$"
    fi
}

install_path_exists() {
    [ -e "$1" ] || [ -L "$1" ]
}

semver_identifiers_valid() {
    local value=$1
    local allow_numeric_leading_zero=$2
    local pattern='^[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*$'
    [[ "$value" =~ $pattern ]] || return 1

    local -a identifiers
    local identifier
    IFS=. read -r -a identifiers <<< "$value"
    for identifier in "${identifiers[@]}"; do
        if [ "$allow_numeric_leading_zero" -eq 0 ] \
            && [[ "$identifier" =~ ^[0-9]+$ ]] \
            && [ "${#identifier}" -gt 1 ] \
            && [ "${identifier#0}" != "$identifier" ]
        then
            return 1
        fi
    done
}

semver_is_valid() {
    local raw=$1
    [ -n "$raw" ] || return 1

    local without_build=$raw
    local build=""
    if [[ "$raw" == *+* ]]; then
        without_build=${raw%%+*}
        build=${raw#*+}
        [ -n "$without_build" ] \
            && [ -n "$build" ] \
            && [[ "$build" != *+* ]] \
            && semver_identifiers_valid "$build" 1 \
            || return 1
    fi

    local core=$without_build
    local prerelease=""
    if [[ "$without_build" == *-* ]]; then
        core=${without_build%%-*}
        prerelease=${without_build#*-}
        [ -n "$prerelease" ] \
            && semver_identifiers_valid "$prerelease" 0 \
            || return 1
    fi

    local core_pattern='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$'
    [[ "$core" =~ $core_pattern ]]
}

read_canonical_app_version() {
    local app=$1
    local short_version
    local bundle_version
    short_version=$(/usr/libexec/PlistBuddy \
        -c 'Print :CFBundleShortVersionString' \
        "$app/Contents/Info.plist" 2>/dev/null || true)
    bundle_version=$(/usr/libexec/PlistBuddy \
        -c 'Print :CFBundleVersion' \
        "$app/Contents/Info.plist" 2>/dev/null || true)
    [ "$short_version" = "$bundle_version" ] \
        && semver_is_valid "$short_version" \
        || return 1
    printf '%s\n' "$short_version"
}

compare_numeric_identifiers() {
    local left=$1
    local right=$2
    while [ "${#left}" -gt 1 ] && [ "${left#0}" != "$left" ]; do left=${left#0}; done
    while [ "${#right}" -gt 1 ] && [ "${right#0}" != "$right" ]; do right=${right#0}; done
    if [ "${#left}" -lt "${#right}" ]; then
        printf '%s\n' -1
    elif [ "${#left}" -gt "${#right}" ]; then
        printf '%s\n' 1
    elif [[ "$left" < "$right" ]]; then
        printf '%s\n' -1
    elif [[ "$left" > "$right" ]]; then
        printf '%s\n' 1
    else
        printf '%s\n' 0
    fi
}

semver_is_older() {
    semver_is_valid "$1" && semver_is_valid "$2" || return 1
    local candidate_no_build=${1%%+*}
    local installed_no_build=${2%%+*}
    local candidate_core=${candidate_no_build%%-*}
    local installed_core=${installed_no_build%%-*}
    local candidate_pre=""
    local installed_pre=""
    [[ "$candidate_no_build" == *-* ]] && candidate_pre=${candidate_no_build#*-}
    [[ "$installed_no_build" == *-* ]] && installed_pre=${installed_no_build#*-}

    local -a candidate_parts
    local -a installed_parts
    IFS=. read -r -a candidate_parts <<< "$candidate_core"
    IFS=. read -r -a installed_parts <<< "$installed_core"
    local index
    local comparison
    for index in 0 1 2; do
        comparison=$(compare_numeric_identifiers \
            "${candidate_parts[$index]}" "${installed_parts[$index]}")
        [ "$comparison" -lt 0 ] && return 0
        [ "$comparison" -gt 0 ] && return 1
    done

    [ -z "$candidate_pre" ] && return 1
    [ -z "$installed_pre" ] && return 0

    local -a candidate_identifiers
    local -a installed_identifiers
    IFS=. read -r -a candidate_identifiers <<< "$candidate_pre"
    IFS=. read -r -a installed_identifiers <<< "$installed_pre"
    local count=${#candidate_identifiers[@]}
    [ "${#installed_identifiers[@]}" -gt "$count" ] \
        && count=${#installed_identifiers[@]}
    for ((index = 0; index < count; index++)); do
        if [ "$index" -ge "${#candidate_identifiers[@]}" ]; then return 0; fi
        if [ "$index" -ge "${#installed_identifiers[@]}" ]; then return 1; fi
        local candidate_identifier=${candidate_identifiers[$index]}
        local installed_identifier=${installed_identifiers[$index]}
        if [[ "$candidate_identifier" =~ ^[0-9]+$ ]] \
            && [[ "$installed_identifier" =~ ^[0-9]+$ ]]
        then
            comparison=$(compare_numeric_identifiers \
                "$candidate_identifier" "$installed_identifier")
            [ "$comparison" -lt 0 ] && return 0
            [ "$comparison" -gt 0 ] && return 1
        elif [[ "$candidate_identifier" =~ ^[0-9]+$ ]]; then
            return 0
        elif [[ "$installed_identifier" =~ ^[0-9]+$ ]]; then
            return 1
        elif [[ "$candidate_identifier" < "$installed_identifier" ]]; then
            return 0
        elif [[ "$candidate_identifier" > "$installed_identifier" ]]; then
            return 1
        fi
    done
    return 1
}

validate_app_version_transition() {
    local staged_app=$1
    local destination=$2
    local source_version
    source_version=$(read_canonical_app_version "$staged_app") || {
        fail_install "Staged Darkbloom.app has invalid or inconsistent version metadata."
        return 1
    }
    install_path_exists "$destination" || return 0
    existing_bundle_is_ours "$destination" || return 0

    local installed_id
    installed_id=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' \
        "$destination/Contents/Info.plist" 2>/dev/null || true)
    [ "$installed_id" = "io.darkbloom.provider" ] || return 0
    local installed_version
    installed_version=$(read_canonical_app_version "$destination") || return 0
    semver_is_older "$source_version" "$installed_version" || return 0
    fail_install \
        "Refusing to replace newer Darkbloom $installed_version with $source_version."
}

prepare_app_install_lock_file() {
    local lock=$1
    if [ -L "$lock" ] || { install_path_exists "$lock" && [ ! -f "$lock" ]; }; then
        fail_install "Installation lock path is not a regular file: $lock"
        return 1
    fi
    : >> "$lock" || return 1
    chmod 600 "$lock"
}

acquire_app_install_lock_fd() {
    local descriptor=$1
    local deadline=$2
    while ! /usr/bin/lockf -s -t 0 "$descriptor"; do
        if [ "$(date +%s)" -ge "$deadline" ]; then
            fail_install "Another Darkbloom installation is still active."
            return 1
        fi
        sleep 0.05
    done
}

with_app_install_lock() {
    local install_dir=$1
    shift
    local primary_lock="$install_dir/.app-install.lock"
    local legacy_lock="$install_dir/recovery/update.lock"
    mkdir -p "$install_dir/recovery" || return 1
    prepare_app_install_lock_file "$primary_lock" || return 1
    prepare_app_install_lock_file "$legacy_lock" || return 1

    exec 8>>"$primary_lock"
    exec 9>>"$legacy_lock"
    local deadline=$(( $(date +%s) + 30 ))
    trap 'exit 129' HUP
    trap 'exit 130' INT
    trap 'exit 143' TERM

    local status=0
    acquire_app_install_lock_fd 8 "$deadline" || status=$?
    if [ "$status" -eq 0 ]; then
        acquire_app_install_lock_fd 9 "$deadline" || status=$?
    fi
    if [ "$status" -eq 0 ]; then
        : > "$legacy_lock" || status=$?
    fi
    if [ "$status" -eq 0 ]; then
        recover_interrupted_install_transactions "$install_dir" || status=$?
    fi
    if [ "$status" -eq 0 ]; then
        "$@" || status=$?
    fi

    trap - HUP INT TERM
    exec 9>&-
    exec 8>&-
    return "$status"
}

transaction_value() {
    local backup=$1
    local name=$2
    sed -n '1p' "$backup/.$name" 2>/dev/null || true
}

mark_install_transaction_phase() {
    local backup=$1
    local phase=$2
    local temporary="$backup/.transaction-phase.tmp-$$"
    printf '%s\n' "$phase" > "$temporary" \
        && chmod 600 "$temporary" \
        && mv "$temporary" "$backup/.transaction-phase"
}

write_install_transaction() {
    local backup=$1
    local kind=$2
    local had_previous=$3
    local previous_was_foreign=${4:-0}
    local staging_name=$5
    [[ "$staging_name" == .install-staging-* ]] \
        && [[ "$staging_name" != */* ]] \
        || return 1
    printf '1\n' > "$backup/.transaction-version" \
        && printf '%s\n' "$kind" > "$backup/.transaction-kind" \
        && printf '%s\n' "$had_previous" > "$backup/.had-previous" \
        && printf '%s\n' "$previous_was_foreign" > "$backup/.previous-was-foreign" \
        && printf '%s\n' "$staging_name" > "$backup/.staging-name" \
        && chmod 600 "$backup"/.transaction-* \
            "$backup/.had-previous" "$backup/.previous-was-foreign" \
            "$backup/.staging-name" \
        && mark_install_transaction_phase "$backup" prepared
}

cleanup_recorded_staging() {
    local backup=$1
    local install_dir=$2
    local staging_name
    staging_name=$(transaction_value "$backup" staging-name)
    [ -z "$staging_name" ] && return 0
    [[ "$staging_name" == .install-staging-* ]] \
        && [[ "$staging_name" != */* ]] \
        || return 1
    rm -rf "$install_dir/$staging_name"
}

remove_managed_links() {
    local bin_dir=$1
    local name
    local failed=0
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        rm -rf "${bin_dir:?}/$name" 2>/dev/null || failed=1
    done
    return "$failed"
}

snapshot_managed_links() {
    local backup_bin=$1
    local bin_dir=$2
    local name
    mkdir -p "$backup_bin" || return 1
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        if install_path_exists "$bin_dir/$name"; then
            cp -pPR "$bin_dir/$name" "$backup_bin/$name" || return 1
        fi
    done
    : > "${backup_bin%/bin}/.links-snapshotted"
}

app_payload_complete() {
    local app=$1
    [ -d "$app" ] \
        && [ ! -L "$app" ] \
        && [ -f "$app/Contents/MacOS/darkbloom" ] \
        && [ -f "$app/Contents/MacOS/darkbloom-enclave" ] \
        && [ -f "$app/Contents/MacOS/mlx.metallib" ]
}

managed_app_layout_complete() {
    local install_dir=$1
    local app="$install_dir/Darkbloom.app"
    local bin_dir="$install_dir/bin"
    app_payload_complete "$app" \
        && [ -L "$bin_dir/darkbloom" ] \
        && [ "$(readlink "$bin_dir/darkbloom")" = \
            "../Darkbloom.app/Contents/MacOS/darkbloom" ] \
        && [ -L "$bin_dir/darkbloom-enclave" ] \
        && [ "$(readlink "$bin_dir/darkbloom-enclave")" = \
            "../Darkbloom.app/Contents/MacOS/darkbloom-enclave" ] \
        && [ -L "$bin_dir/mlx.metallib" ] \
        && [ "$(readlink "$bin_dir/mlx.metallib")" = \
            "../Darkbloom.app/Contents/MacOS/mlx.metallib" ] \
        && [ -L "$bin_dir/eigeninference-enclave" ] \
        && [ "$(readlink "$bin_dir/eigeninference-enclave")" = \
            "darkbloom-enclave" ]
}

flat_layout_complete() {
    local bin_dir=$1
    [ -f "$bin_dir/darkbloom" ] \
        && [ -f "$bin_dir/darkbloom-enclave" ] \
        && [ -f "$bin_dir/mlx.metallib" ] \
        && [ -L "$bin_dir/eigeninference-enclave" ] \
        && [ "$(readlink "$bin_dir/eigeninference-enclave")" = \
            "darkbloom-enclave" ]
}

install_canonical_managed_links() {
    local install_dir=$1
    local destination="$install_dir/Darkbloom.app"
    local bin_dir="$install_dir/bin"
    app_payload_complete "$destination" || return 1
    mkdir -p "$bin_dir" \
        && remove_managed_links "$bin_dir" \
        && ln -s "../Darkbloom.app/Contents/MacOS/darkbloom" \
            "$bin_dir/darkbloom" \
        && ln -s "../Darkbloom.app/Contents/MacOS/darkbloom-enclave" \
            "$bin_dir/darkbloom-enclave" \
        && ln -s "../Darkbloom.app/Contents/MacOS/mlx.metallib" \
            "$bin_dir/mlx.metallib" \
        && ln -s "darkbloom-enclave" "$bin_dir/eigeninference-enclave" \
        && chmod +x \
            "$destination/Contents/MacOS/darkbloom" \
            "$destination/Contents/MacOS/darkbloom-enclave"
}

restore_all_backed_up_bin_entries() {
    local backup_bin=$1
    local bin_dir=$2
    local entry
    [ -d "$backup_bin" ] || return 0
    mkdir -p "$bin_dir" || return 1
    shopt -s nullglob
    local -a entries=("$backup_bin"/*)
    shopt -u nullglob
    for entry in "${entries[@]}"; do
        rm -rf "$bin_dir/${entry##*/}" \
            && mv "$entry" "$bin_dir/${entry##*/}" \
            || return 1
    done
}

recover_prepared_app_transaction() {
    local backup=$1
    local install_dir=$2
    local had_previous
    had_previous=$(transaction_value "$backup" had-previous)
    [[ "$had_previous" =~ ^[01]$ ]] || return 1
    [ -f "$backup/.links-snapshotted" ] || return 1

    local destination="$install_dir/Darkbloom.app"
    if install_path_exists "$backup/Darkbloom.app"; then
        rm -rf "$destination" \
            && mv "$backup/Darkbloom.app" "$destination" \
            || return 1
    elif [ "$had_previous" -eq 0 ]; then
        rm -rf "$destination" || return 1
    fi
    restore_managed_links "$backup/bin" "$install_dir/bin" || return 1
    cleanup_recorded_staging "$backup" "$install_dir" || return 1
    rm -rf "$backup"
}

finalize_committed_app_transaction() {
    local backup=$1
    local install_dir=$2
    local previous_was_foreign
    previous_was_foreign=$(transaction_value "$backup" previous-was-foreign)
    [[ "$previous_was_foreign" =~ ^[01]$ ]] || return 1
    managed_app_layout_complete "$install_dir" || return 1

    if [ "$previous_was_foreign" -eq 1 ] \
        && install_path_exists "$backup/Darkbloom.app"
    then
        local preserved
        preserved=$(foreign_bundle_destination "$install_dir")
        mv "$backup/Darkbloom.app" "$preserved" || return 1
        echo "  ⚠ Preserved the previous foreign app at:"
        echo "      $preserved"
    fi
    cleanup_recorded_staging "$backup" "$install_dir" || return 1
    rm -rf "$backup"
}

recover_prepared_flat_transaction() {
    local backup=$1
    local install_dir=$2
    local had_previous
    had_previous=$(transaction_value "$backup" had-previous)
    [[ "$had_previous" =~ ^[01]$ ]] || return 1

    if [ -d "$backup/bin" ]; then
        rm -rf "$install_dir/bin" \
            && mv "$backup/bin" "$install_dir/bin" \
            || return 1
    elif [ "$had_previous" -eq 0 ]; then
        rm -rf "$install_dir/bin" || return 1
    fi
    cleanup_recorded_staging "$backup" "$install_dir" || return 1
    rm -rf "$backup"
}

recover_legacy_install_transaction() {
    local backup=$1
    local install_dir=$2
    local destination="$install_dir/Darkbloom.app"

    if install_path_exists "$backup/Darkbloom.app"; then
        rm -rf "$destination" \
            && mv "$backup/Darkbloom.app" "$destination" \
            || return 1
        restore_all_backed_up_bin_entries \
            "$backup/bin" "$install_dir/bin" || return 1
    elif app_payload_complete "$destination"; then
        install_canonical_managed_links "$install_dir" || return 1
    elif [ -d "$backup/bin" ]; then
        rm -rf "$destination" || return 1
        restore_all_backed_up_bin_entries \
            "$backup/bin" "$install_dir/bin" || return 1
    fi
    rm -rf "$backup"
}

recover_interrupted_install_transactions() {
    local install_dir=$1
    local backup
    shopt -s nullglob
    local -a backups=("$install_dir"/.install-backup-*)
    shopt -u nullglob
    for backup in "${backups[@]}"; do
        [ -d "$backup" ] || continue
        local version
        local kind
        local phase
        version=$(transaction_value "$backup" transaction-version)
        kind=$(transaction_value "$backup" transaction-kind)
        phase=$(transaction_value "$backup" transaction-phase)

        if [ -z "$version" ] && [ -z "$kind" ] && [ -z "$phase" ]; then
            recover_legacy_install_transaction "$backup" "$install_dir" || {
                fail_install "Could not recover interrupted installer transaction $backup."
                return 1
            }
            continue
        fi
        if [ "$version" != "1" ] || [[ ! "$kind" =~ ^(app|flat)$ ]]; then
            fail_install "Installer transaction metadata is invalid at $backup."
            return 1
        fi
        if [ -z "$phase" ]; then
            cleanup_recorded_staging "$backup" "$install_dir" || return 1
            rm -rf "$backup" || return 1
            continue
        fi

        case "$kind:$phase" in
            app:prepared)
                recover_prepared_app_transaction "$backup" "$install_dir"
                ;;
            app:committed)
                finalize_committed_app_transaction "$backup" "$install_dir"
                ;;
            flat:prepared)
                recover_prepared_flat_transaction "$backup" "$install_dir"
                ;;
            flat:committed)
                flat_layout_complete "$install_dir/bin" \
                    && cleanup_recorded_staging "$backup" "$install_dir" \
                    && rm -rf "$backup"
                ;;
            *)
                fail_install "Installer transaction phase is invalid at $backup."
                return 1
                ;;
        esac || {
            fail_install "Could not recover interrupted installer transaction $backup."
            return 1
        }
    done
}

restore_backed_up_links() {
    local backup_bin=$1
    local bin_dir=$2
    local name
    local failed=0
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        if install_path_exists "$backup_bin/$name"; then
            if ! rm -rf "${bin_dir:?}/$name" 2>/dev/null; then
                failed=1
                continue
            fi
            mv "$backup_bin/$name" "$bin_dir/$name" 2>/dev/null || failed=1
        fi
    done
    return "$failed"
}

restore_managed_links() {
    local backup_bin=$1
    local bin_dir=$2
    local failed=0
    remove_managed_links "$bin_dir" || failed=1
    restore_backed_up_links "$backup_bin" "$bin_dir" || failed=1
    return "$failed"
}

create_managed_link() {
    local target=$1
    local link=$2
    local fault_point=$3
    install_test_fault "$fault_point" && return 1
    ln -s "$target" "$link"
}

ensure_user_app_shortcut() {
    local managed_app=$1
    local shortcut=$2
    local shortcut_dir=${shortcut%/*}
    local managed_resolved
    local shortcut_resolved

    [ -d "$managed_app" ] && [ ! -L "$managed_app" ] || return 0
    mkdir -p "$shortcut_dir" || {
        echo "  ⚠ Could not create $shortcut_dir; launch the managed app directly."
        return 1
    }

    if [ -e "$shortcut" ] || [ -L "$shortcut" ]; then
        if [ -L "$shortcut" ]; then
            managed_resolved=$(cd -P "$managed_app" 2>/dev/null && pwd -P || true)
            shortcut_resolved=$(cd -P "$shortcut" 2>/dev/null && pwd -P || true)
            if [ -n "$managed_resolved" ] \
                && [ "$shortcut_resolved" = "$managed_resolved" ]
            then
                return 0
            fi
        fi
        echo "  ⚠ Preserving existing $shortcut; open $managed_app directly."
        return 0
    fi

    if ! ln -s "$managed_app" "$shortcut"; then
        if [ -e "$shortcut" ] || [ -L "$shortcut" ]; then
            echo "  ⚠ Preserving $shortcut, which appeared while installing."
            return 0
        fi
        echo "  ⚠ Could not create the user Applications shortcut at $shortcut."
        return 1
    fi
}

commit_staged_app() {
    local staged_app=$1
    local install_dir=$2
    local backup="$install_dir/.install-backup-$$-$RANDOM"
    local destination="$install_dir/Darkbloom.app"
    local bin_dir="$install_dir/bin"
    local previous_app="$backup/Darkbloom.app"
    local had_previous=0
    local previous_was_foreign=0
    local staging_name=${staged_app%/Darkbloom.app}
    staging_name=${staging_name##*/}
    validate_app_version_transition "$staged_app" "$destination" || return 1
    mkdir -p "$backup" "$bin_dir" || {
        rm -rf "$backup"
        return 1
    }

    if install_path_exists "$destination"; then
        existing_bundle_is_ours "$destination" || previous_was_foreign=1
        had_previous=1
    fi
    snapshot_managed_links "$backup/bin" "$bin_dir" \
        && write_install_transaction \
            "$backup" app "$had_previous" "$previous_was_foreign" \
            "$staging_name" \
        || {
            rm -rf "$backup"
            return 1
        }

    if [ "$had_previous" -eq 1 ]; then
        if ! mv "$destination" "$previous_app"; then
            rm -rf "$backup"
            return 1
        fi
        install_test_crash "previous-app-moved"
    fi
    if install_test_fault "staged-app-move" \
        || ! mv "$staged_app" "$destination"
    then
        recover_prepared_app_transaction "$backup" "$install_dir" || true
        return 1
    fi
    install_test_crash "staged-app-moved"
    remove_managed_links "$bin_dir" || {
        recover_prepared_app_transaction "$backup" "$install_dir" || true
        return 1
    }

    local app_bin="$destination/Contents/MacOS"
    if ! create_managed_link \
        "../Darkbloom.app/Contents/MacOS/darkbloom" \
        "$bin_dir/darkbloom" "link-darkbloom" \
        || ! create_managed_link \
            "../Darkbloom.app/Contents/MacOS/darkbloom-enclave" \
            "$bin_dir/darkbloom-enclave" "link-darkbloom-enclave" \
        || ! create_managed_link \
            "../Darkbloom.app/Contents/MacOS/mlx.metallib" \
            "$bin_dir/mlx.metallib" "link-metallib" \
        || ! create_managed_link \
            "darkbloom-enclave" \
            "$bin_dir/eigeninference-enclave" "link-legacy-enclave"
    then
        recover_prepared_app_transaction "$backup" "$install_dir" || true
        return 1
    fi
    if install_test_fault "app-chmod" \
        || ! chmod +x "$app_bin/darkbloom" "$app_bin/darkbloom-enclave"
    then
        recover_prepared_app_transaction "$backup" "$install_dir" || true
        return 1
    fi
    managed_app_layout_complete "$install_dir" || {
        recover_prepared_app_transaction "$backup" "$install_dir" || true
        return 1
    }
    install_test_crash "managed-links-installed"

    mark_install_transaction_phase "$backup" committed || {
        recover_prepared_app_transaction "$backup" "$install_dir" || true
        return 1
    }
    install_test_crash "app-transaction-committed"
    finalize_committed_app_transaction "$backup" "$install_dir" || {
        echo "  ⚠ Installed successfully, but could not remove transaction backup $backup." >&2
    }
}

commit_staged_flat_bundle() {
    local staged_bin=$1
    local install_dir=$2
    local backup="$install_dir/.install-backup-$$-$RANDOM"
    local destination="$install_dir/bin"
    local had_previous=0
    local staging_name=${staged_bin%/bin}
    staging_name=${staging_name##*/}
    mkdir -p "$backup"
    if install_path_exists "$destination"; then
        had_previous=1
    fi
    write_install_transaction \
        "$backup" flat "$had_previous" 0 "$staging_name" || {
        rm -rf "$backup"
        return 1
    }
    if [ "$had_previous" -eq 1 ]; then
        mv "$destination" "$backup/bin" || {
            rm -rf "$backup"
            return 1
        }
        install_test_crash "flat-previous-moved"
    fi
    if ! mv "$staged_bin" "$destination"; then
        recover_prepared_flat_transaction "$backup" "$install_dir" || true
        return 1
    fi
    install_test_crash "flat-layout-moved"
    if ! chmod +x "$destination/darkbloom" "$destination/darkbloom-enclave" \
        || ! ln -sfn "darkbloom-enclave" "$destination/eigeninference-enclave" \
        || ! flat_layout_complete "$destination"
    then
        recover_prepared_flat_transaction "$backup" "$install_dir" || true
        return 1
    fi
    mark_install_transaction_phase "$backup" committed || {
        recover_prepared_flat_transaction "$backup" "$install_dir" || true
        return 1
    }
    install_test_crash "flat-transaction-committed"
    rm -rf "$backup" || {
        echo "  ⚠ Installed successfully, but could not remove transaction backup $backup." >&2
    }
}

install_bundle_atomically() {
    local archive=$1
    local install_dir=$2
    local binary_hash=${3:-}
    local metallib_hash=${4:-}
    local stage="$install_dir/.install-staging-$$-$RANDOM"
    rm -rf "$stage"
    mkdir -p "$stage"
    if ! tar xzf "$archive" -C "$stage"; then
        rm -rf "$stage"
        return 1
    fi

    local flat_bin="$stage/bin"
    [ -f "$flat_bin/darkbloom" ] \
        && [ -f "$flat_bin/darkbloom-enclave" ] \
        && [ -f "$flat_bin/mlx.metallib" ] \
        || {
            rm -rf "$stage"
            fail_install "Release bundle is missing required flat verifier files."
            return 1
        }
    verify_file_hash "$flat_bin/darkbloom" "$binary_hash" "Binary" || {
        rm -rf "$stage"
        return 1
    }
    verify_file_hash "$flat_bin/mlx.metallib" "$metallib_hash" "Metallib" || {
        rm -rf "$stage"
        return 1
    }

    if [ -d "$stage/Darkbloom.app" ]; then
        verify_staged_app_payload \
            "$stage/Darkbloom.app" "$binary_hash" "$metallib_hash" || {
            rm -rf "$stage"
            return 1
        }
        verify_staged_app "$stage/Darkbloom.app" || {
            rm -rf "$stage"
            return 1
        }
        with_app_install_lock \
            "$install_dir" commit_staged_app "$stage/Darkbloom.app" "$install_dir" || {
            rm -rf "$stage"
            fail_install "Atomic app swap failed; previous install was restored."
            return 1
        }
    else
        if [ "$INSTALL_TEST_MODE" = "1" ]; then
            codesign --verify --strict --verbose=2 "$flat_bin/darkbloom" >/dev/null 2>&1 || {
                rm -rf "$stage"
                fail_install "Strict signature verification failed for legacy flat artifact."
                return 1
            }
        else
            verify_code_requirement \
                "$flat_bin/darkbloom" 0 "$DARKBLOOM_DESIGNATED_REQUIREMENT" || {
                rm -rf "$stage"
                fail_install "Legacy flat artifact does not satisfy the pinned signature requirement."
                return 1
            }
        fi
        with_app_install_lock \
            "$install_dir" commit_staged_flat_bundle "$flat_bin" "$install_dir" || {
            rm -rf "$stage"
            fail_install "Atomic flat-bundle swap failed; previous install was restored."
            return 1
        }
    fi
    rm -rf "$stage"
}

install_lock_noop() {
    return 0
}

install_lock_probe_body() {
    local entered=$1
    local release=$2
    local after=$3
    printf 'entered\n' > "$entered"
    while [ ! -e "$release" ]; do
        sleep 0.05
    done
    printf 'after\n' > "$after"
}

if [ "${1:-}" = "--semver-test" ]; then
    [ "$#" -eq 2 ] || exit 64
    semver_is_valid "$2"
    exit $?
fi

if [ "${1:-}" = "--semver-older-test" ]; then
    [ "$#" -eq 3 ] || exit 64
    semver_is_older "$2" "$3"
    exit $?
fi

if [ "${1:-}" = "--recover-install-transactions-test" ]; then
    [ "$#" -eq 2 ] || exit 64
    INSTALL_TEST_MODE=1
    with_app_install_lock "$2" install_lock_noop
    exit $?
fi

if [ "${1:-}" = "--hold-install-lock-test" ]; then
    [ "$#" -eq 5 ] || exit 64
    INSTALL_TEST_MODE=1
    with_app_install_lock "$2" install_lock_probe_body "$3" "$4" "$5"
    exit $?
fi

if [ "${1:-}" = "--verify-staged-app-signature-test" ]; then
    [ "$#" -eq 3 ] || {
        echo "usage: $0 --verify-staged-app-signature-test <app> <requirement>" >&2
        exit 64
    }
    verify_staged_app_signature "$2" "$3"
    exit $?
fi

if [ "${1:-}" = "--ensure-user-app-shortcut-test" ]; then
    [ "$#" -eq 3 ] || {
        echo "usage: $0 --ensure-user-app-shortcut-test <managed-app> <shortcut>" >&2
        exit 64
    }
    ensure_user_app_shortcut "$2" "$3"
    exit $?
fi

if [ "${1:-}" = "--install-bundle-test" ]; then
    { [ "$#" -eq 5 ] || [ "$#" -eq 6 ]; } || {
        echo "usage: $0 --install-bundle-test <archive> <install-dir> <binary-hash> <metallib-hash> [fan-helper-requirement]" >&2
        exit 64
    }
    INSTALL_TEST_MODE=1
    if [ "$#" -eq 6 ]; then FAN_HELPER_REQUIREMENT=$6; fi
    install_bundle_atomically "$2" "$3" "$4" "$5"
    exit $?
fi

# Detect interactive vs piped (curl | bash).
if [ -t 0 ]; then
    INTERACTIVE=true
else
    INTERACTIVE=false
fi

echo "╔══════════════════════════════════════════════╗"
echo "║  Darkbloom — Private AI on Verified Macs     ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── Pre-flight checks ───────────────────────────────────────
if [ "$(uname)" != "Darwin" ]; then
    echo "Error: Darkbloom requires macOS with Apple Silicon."
    exit 1
fi
if [ "$(uname -m)" != "arm64" ]; then
    echo "Error: Darkbloom requires Apple Silicon (arm64)."
    exit 1
fi

CHIP=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "Apple Silicon")
MEM=$(sysctl -n hw.memsize 2>/dev/null | awk '{printf "%.0f", $1/1073741824}')
MACOS=$(sw_vers -productVersion 2>/dev/null || echo "?")
echo "  $CHIP · ${MEM}GB · macOS $MACOS"
echo ""

# ─── Step 1: Fetch latest release ────────────────────────────
echo "→ [1/5] Fetching latest release from $COORD_URL ..."

RELEASE_JSON=$(curl -fsSL "$COORD_URL/v1/releases/latest" 2>/dev/null || echo "")
if [ -z "$RELEASE_JSON" ]; then
    echo "  ✗ Could not reach coordinator at $COORD_URL"
    echo "    Check your internet connection and try again."
    exit 1
fi

# Extract JSON string fields with sed — no python3 needed (no Xcode CLT prompt).
json_val() { echo "$1" | sed -n "s/.*\"$2\":\"\([^\"]*\)\".*/\1/p"; }
BUNDLE_URL=$(json_val "$RELEASE_JSON" url)
BUNDLE_HASH=$(json_val "$RELEASE_JSON" bundle_hash)
BINARY_HASH=$(json_val "$RELEASE_JSON" binary_hash)
METALLIB_HASH=$(json_val "$RELEASE_JSON" metallib_hash)
VERSION=$(json_val "$RELEASE_JSON" version)
BACKEND=$(json_val "$RELEASE_JSON" backend)

if [ -z "$BUNDLE_URL" ] || [ -z "$BUNDLE_HASH" ] || [ -z "$VERSION" ]; then
    echo "  ✗ Coordinator response missing required fields (url / bundle_hash / version)."
    echo "    Raw response: $RELEASE_JSON"
    exit 1
fi

echo "  Version: $VERSION"
echo "  Backend: ${BACKEND:-mlx-swift}"
echo "  Signed by: Developer ID Application: Eigen Labs, Inc."
echo ""

# ─── Step 2: Download + verify bundle ────────────────────────
echo "→ [2/5] Downloading Darkbloom v${VERSION}..."
mkdir -p "$INSTALL_DIR" "$BIN_DIR"

TARBALL="/tmp/darkbloom-bundle.tar.gz"
curl -f#L "$BUNDLE_URL" -o "$TARBALL"

ACTUAL_HASH=$(shasum -a 256 "$TARBALL" | cut -d' ' -f1)
if [ "$ACTUAL_HASH" != "$BUNDLE_HASH" ]; then
    echo ""
    echo "  ✗ Bundle hash mismatch — refusing to install possibly-tampered binary."
    echo "    Expected: $BUNDLE_HASH"
    echo "    Got:      $ACTUAL_HASH"
    rm -f "$TARBALL"
    exit 1
fi
echo "  Bundle hash verified ✓"

echo "  Staging and verifying the complete app before touching the live install ..."
if ! install_bundle_atomically "$TARBALL" "$INSTALL_DIR" "$BINARY_HASH" "$METALLIB_HASH"; then
    rm -f "$TARBALL"
    echo "  Existing installation was left unchanged."
    exit 1
fi
rm -f "$TARBALL"
echo "  Strict signature, runtime resources, and atomic swap verified ✓"

ensure_user_app_shortcut \
    "$INSTALL_DIR/Darkbloom.app" \
    "$HOME/Applications/Darkbloom.app" || true

# Make available in PATH. Try /usr/local/bin symlink, fall back to shell rc.
if ln -sf "$BIN_DIR/darkbloom" /usr/local/bin/darkbloom 2>/dev/null; then
    :
fi
RC="$HOME/.zshrc"
if [ -f "$HOME/.bashrc" ] && [ ! -f "$HOME/.zshrc" ]; then
    RC="$HOME/.bashrc"
fi
if ! grep -q "\.darkbloom/bin" "$RC" 2>/dev/null; then
    sed -i '' '/\.dginf\/bin/d; /\.eigeninference\/bin/d; /alias eigeninf/d; /alias dginf/d; /# EigenInference/d; /# Darkbloom$/d' "$RC" 2>/dev/null || true
    cat >> "$RC" << 'SHELL'

# Darkbloom
export PATH="$HOME/.darkbloom/bin:$PATH"
SHELL
fi
export PATH="$BIN_DIR:$PATH"

# Source rc so commands work in this shell. Disable -eu around it: rc files
# may use unbound vars or shell-specific builtins that fail under bash strict.
set +eu
# The selected user rc path is intentionally dynamic.
# shellcheck disable=SC1090
source "$RC" 2>/dev/null || true
set -eu

echo "  Binaries installed ✓"
echo "  Shortcut: darkbloom"

# ─── Migrate from old installs ───────────────────────────────
# Migration chain: ~/.dginf → ~/.eigeninference → ~/.darkbloom
for OLD_DIR in "$HOME/.dginf" "$HOME/.eigeninference"; do
    if [ -d "$OLD_DIR" ] && [ ! -L "$OLD_DIR" ]; then
        echo ""
        echo "  Migrating from $OLD_DIR..."
        for f in enclave_key.data wallet_key auth_token; do
            [ -f "$OLD_DIR/$f" ] && cp -n "$OLD_DIR/$f" "$INSTALL_DIR/$f" 2>/dev/null || true
        done
        # Symlink old path so stragglers still work, then drop the old python/
        # subtree -- the Swift release no longer needs it.
        ln -sfn "$INSTALL_DIR" "$OLD_DIR" 2>/dev/null || true
        echo "  Migration complete ✓"
    fi
done

# ─── Step 3: Secure Enclave identity ─────────────────────────
echo ""
echo "→ [3/5] Provisioning Secure Enclave identity..."
if "$BIN_DIR/darkbloom-enclave" info >/dev/null 2>&1; then
    echo "  Secure Enclave ✓ (P-256 key generated)"
else
    echo "  Secure Enclave ⚠ (not available on this hardware; provider will run with reduced trust)"
fi

# ─── Step 4: Enrollment + device attestation ─────────────────
echo ""
echo "→ [4/5] Enrollment + device attestation..."

ALREADY_ENROLLED=false
if profiles status -type enrollment 2>&1 | grep -q "MDM enrollment: Yes"; then
    ALREADY_ENROLLED=true
fi

if [ "$ALREADY_ENROLLED" = true ]; then
    echo "  Already enrolled ✓"
else
    echo "  Requesting enrollment profile from coordinator..."
    PROFILE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/Darkbloom-Enroll.XXXXXX")"
    PROFILE_PATH="$PROFILE_DIR/Darkbloom-Enroll.mobileconfig"
    if curl -fsSL -X POST "$COORD_URL/v1/enroll" \
        -H "Content-Type: application/json" \
        -d '{}' \
        -o "$PROFILE_PATH" 2>/dev/null; then
        echo ""
        echo "  ┌──────────────────────────────────────────────────┐"
        echo "  │ ACTION REQUIRED: Install the enrollment profile  │"
        echo "  │                                                  │"
        echo "  │ This profile lets the coordinator verify:        │"
        echo "  │  • SIP, Secure Boot, system integrity            │"
        echo "  │  • Your Secure Enclave is genuine Apple silicon  │"
        echo "  │  • Device identity signed by Apple's Root CA     │"
        echo "  │                                                  │"
        echo "  │ Darkbloom CANNOT erase, lock, or control         │"
        echo "  │ your Mac. Remove anytime in System Settings.     │"
        echo "  └──────────────────────────────────────────────────┘"
        echo ""
        open "$PROFILE_PATH"
        sleep 1
        open "x-apple.systempreferences:com.apple.Profiles-Settings.extension"

        echo "  System Settings opened — click Install and enter your password."
        if [ "$INTERACTIVE" = true ]; then
            echo ""
            read -r -p "  Press Enter once you have installed the profile..." || true
        else
            echo "  After installing, the provider will verify on first start."
            sleep 3
        fi
        if profiles status -type enrollment 2>&1 | grep -q "MDM enrollment: Yes"; then
            echo "  Enrollment verified ✓"
        else
            echo "  Enrollment pending ⚠ (complete it in System Settings, or run: darkbloom enroll)"
        fi
    else
        echo "  Enrollment ⚠ (coordinator unreachable — enroll later with: darkbloom enroll)"
    fi
fi

# ─── Step 5: Optional starter model ──────────────────────────
echo ""
echo "→ [5/5] Inference model..."

CATALOG_JSON=$(curl -fsSL "$COORD_URL/v1/models/catalog?type=text" 2>/dev/null || echo "")

if [ -n "$CATALOG_JSON" ]; then
    if [ "$INTERACTIVE" = true ]; then
        echo ""
        echo "  Available text models:"
        echo "$CATALOG_JSON" \
          | tr ',' '\n' \
          | sed -n 's/.*"id":"\([^"]*\)".*"display_name":"\([^"]*\)".*"size_gb":\([0-9.]*\).*"min_ram_gb":\([0-9]*\).*/  • \2  ~\3 GB  (≥\4 GB RAM)  [\1]/p' \
          | head -20
        echo ""
        echo "  Download a model with:"
        echo "    darkbloom models download <id>"
    else
        echo "  Run interactively to pick a starter model:"
        echo "    curl -fsSL $COORD_URL/install.sh | bash -s"
        echo "  Or list the catalog with:  darkbloom models catalog"
    fi
else
    echo "  Could not fetch model catalog (continuing anyway)."
fi

# ─── Done ────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  Install complete                            ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
# Only releases that ship the SwiftUI payload can be launched; downlevel
# flat/CLI-wrapper bundles simply skip this step.
APP_MAIN="$INSTALL_DIR/Darkbloom.app/Contents/MacOS/DarkbloomApp"
if [ -x "$APP_MAIN" ]; then
    echo "  Next step: open Darkbloom and follow the guided setup."
    echo "  App location: ~/.darkbloom/Darkbloom.app"
    echo ""
    if [ "$INTERACTIVE" = true ]; then
        REPLY=""
        read -r -p "  Launch the Darkbloom app now? [Y/n] " REPLY || REPLY="n"
        case "$REPLY" in
            n|N|no|NO|No|nO)
                echo "  Skipped. Launch later with: open ~/.darkbloom/Darkbloom.app"
                ;;
            *)
                /usr/bin/open "$INSTALL_DIR/Darkbloom.app" \
                    && echo "  Darkbloom.app launched ✓" \
                    || echo "  ⚠ Could not launch the app; try: open ~/.darkbloom/Darkbloom.app"
                ;;
        esac
    else
        echo "  Desktop app: open ~/.darkbloom/Darkbloom.app"
    fi
    echo ""
    echo "  Advanced CLI (optional):"
else
    echo "  Next steps:"
fi
echo "    darkbloom doctor             # verify the system is ready"
echo "    darkbloom models catalog     # browse available models"
echo "    darkbloom models download <id>"
echo "    darkbloom login              # link this Mac to your account"
echo "    darkbloom start              # serve inference (interactive picker)"
echo ""
