#!/bin/bash
# Canonical provider installer. coordinator/api/install.sh is generated byte-for-byte
# by scripts/sync-install-embed.sh and embedded in the coordinator binary.
set -euo pipefail

# Darkbloom Provider Installer (Swift CLI release v0.5.0+)
# Usage: curl -fsSL https://api.darkbloom.dev/install.sh | bash
#
# This script:
#   1. Fetches the latest signed release from the coordinator
#   2. Downloads the provider app and its signed sandboxed XPC worker
#   3. Verifies bundle SHA-256 + Apple Developer ID code signature
#   4. Sets up the Secure Enclave identity
#   5. Optionally enrolls in MDM (device attestation)
#   6. Optionally downloads a starter model
#
# Zero prerequisites — just macOS 14+ on Apple Silicon. The Swift supervisor
# delegates plaintext inference to its separately signed, sandboxed XPC worker;
# there is no Python interpreter or unsandboxed inference subprocess.

# This source intentionally retains the placeholder used by the coordinator.
# End users fetch /install.sh from a coordinator, which substitutes its own base
# URL. Direct source execution must set COORD_URL explicitly.
COORD_URL="${COORD_URL:-__DARKBLOOM_COORD_URL__}"
INSTALL_DIR="$HOME/.darkbloom"
BIN_DIR="$INSTALL_DIR/bin"
DARKBLOOM_DESIGNATED_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.provider" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
DARKBLOOM_FAN_HELPER_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.fan-helper" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
DARKBLOOM_WORKER_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.provider.inference-worker" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
WORKER_BUNDLE_RELATIVE_PATH='Contents/XPCServices/DarkbloomInferenceWorker.xpc'
WORKER_EXECUTABLE_RELATIVE_PATH='Contents/MacOS/darkbloom-inference-worker'
FAN_HELPER_REQUIREMENT="$DARKBLOOM_FAN_HELPER_REQUIREMENT"
WORKER_REQUIREMENT="$DARKBLOOM_WORKER_REQUIREMENT"
INSTALL_TEST_MODE=0
SANDBOX_TEST_PROBE=""

fail_install() {
    echo "  ✗ $*" >&2
    return 1
}

DOWNLOAD_DIR=""
TARBALL=""

cleanup_download_bundle() {
    if [ -n "$DOWNLOAD_DIR" ] && [ -d "$DOWNLOAD_DIR" ] && [ ! -L "$DOWNLOAD_DIR" ]; then
        rm -rf -- "$DOWNLOAD_DIR"
    fi
    DOWNLOAD_DIR=""
    TARBALL=""
}

verify_download_archive_path() {
    local archive=$1
    [ -f "$archive" ] && [ ! -L "$archive" ] \
        && [ "$(stat -f '%u' "$archive" 2>/dev/null || true)" = "$(id -u)" ] \
        && [ "$(stat -f '%l' "$archive" 2>/dev/null || true)" = "1" ] \
        || fail_install "Downloaded release archive must be an owned, single-link regular file."
}

secure_download_release() {
    local url=$1
    local old_umask
    DOWNLOAD_DIR=$(mktemp -d "${TMPDIR:-/tmp}/darkbloom-install.XXXXXX") || {
        fail_install "Could not allocate a private release download directory."
        return 1
    }
    trap cleanup_download_bundle EXIT
    trap 'exit 129' HUP
    trap 'exit 130' INT
    trap 'exit 143' TERM
    chmod 0700 "$DOWNLOAD_DIR"
    [ ! -L "$DOWNLOAD_DIR" ] \
        && [ "$(stat -f '%Lp' "$DOWNLOAD_DIR" 2>/dev/null || true)" = "700" ] \
        && [ "$(stat -f '%u' "$DOWNLOAD_DIR" 2>/dev/null || true)" = "$(id -u)" ] \
        || {
            fail_install "Release download directory is not private to the current user."
            return 1
        }

    TARBALL="$DOWNLOAD_DIR/darkbloom-bundle.tar.gz"
    [ ! -e "$TARBALL" ] && [ ! -L "$TARBALL" ] || {
        fail_install "Private release archive path unexpectedly already exists."
        return 1
    }
    old_umask=$(umask)
    umask 077
    if ! curl -f#L "$url" -o "$TARBALL"; then
        umask "$old_umask"
        return 1
    fi
    umask "$old_umask"
    verify_download_archive_path "$TARBALL"
}

verify_file_hash() {
    local file=$1
    local expected=$2
    local label=$3
    [ -z "$expected" ] && return 0
    local actual
    actual=$(shasum -a 256 "$file" | cut -d' ' -f1)
    [ "$actual" = "$expected" ] \
        || fail_install "$label hash mismatch (expected $expected, got $actual)."
}

verify_code_requirement() {
    local target=$1
    local deep=$2
    local requirement=$3
    if [ "$deep" = "1" ]; then
        codesign --verify --deep --strict --verbose=2 \
            "-R=$requirement" "$target" >/dev/null 2>&1
    else
        codesign --verify --strict --verbose=2 \
            "-R=$requirement" "$target" >/dev/null 2>&1
    fi
}

verify_staged_app_signature() {
    local app=$1
    local requirement=${2:-$DARKBLOOM_DESIGNATED_REQUIREMENT}
    verify_code_requirement "$app" 1 "$requirement" || {
        fail_install "Staged Darkbloom.app does not satisfy the pinned signature requirement."
        return 1
    }
}
plist_value() {
    /usr/libexec/PlistBuddy -c "Print :$2" "$1" 2>/dev/null
}
private_validation_dir() {
    local old_umask dir
    old_umask=$(umask)
    umask 077
    dir=$(mktemp -d "${TMPDIR:-/tmp}/darkbloom-verify.XXXXXX") || {
        umask "$old_umask"
        fail_install "Could not allocate a private verification directory."
        return 1
    }
    umask "$old_umask"
    chmod 0700 "$dir"
    [ ! -L "$dir" ] \
        && [ "$(stat -f '%Lp' "$dir" 2>/dev/null || true)" = "700" ] \
        && [ "$(stat -f '%u' "$dir" 2>/dev/null || true)" = "$(id -u)" ] \
        || {
            rm -rf -- "$dir"
            fail_install "Verification directory is not private to the current user."
            return 1
        }
    printf '%s\n' "$dir"
}

verify_worker_profile() {
    local profile=$1
    local temp_dir decoded
    temp_dir=$(private_validation_dir) || return 1
    decoded="$temp_dir/profile.plist"
    if [ "$INSTALL_TEST_MODE" = "1" ]; then
        cp "$profile" "$decoded"
    elif ! security cms -D -i "$profile" > "$decoded" 2>/dev/null; then
        rm -rf -- "$temp_dir"
        fail_install "Inference worker provisioning profile is not a valid Apple CMS profile."
        return 1
    fi
    [ -s "$decoded" ] \
        && [ "$(plist_value "$decoded" 'TeamIdentifier:0' || true)" = "SLDQ2GJ6TL" ] \
        && ! plist_value "$decoded" 'TeamIdentifier:1' >/dev/null \
        && [ "$(plist_value "$decoded" 'Entitlements:application-identifier' || true)" = "SLDQ2GJ6TL.io.darkbloom.provider.inference-worker" ] \
        && [ "$(plist_value "$decoded" 'Entitlements:keychain-access-groups:0' || true)" = "SLDQ2GJ6TL.io.darkbloom.provider" ] \
        && ! plist_value "$decoded" 'Entitlements:keychain-access-groups:1' >/dev/null \
        && [ "$(plist_value "$decoded" 'Entitlements:com.apple.security.app-sandbox' || true)" = "true" ] \
        && [ "$(plist_value "$decoded" 'Entitlements:com.apple.security.files.bookmarks.app-scope' || true)" = "true" ] \
        || {
            rm -rf -- "$temp_dir"
            fail_install "Inference worker provisioning profile does not grant its exact Team, application identity, shared provider key group, sandbox, and app-scoped bookmarks."
            return 1
        }
    rm -rf -- "$temp_dir"
}


verify_worker_entitlements() {
    local worker=$1
    local temp_dir entitlements
    temp_dir=$(private_validation_dir) || return 1
    entitlements="$temp_dir/entitlements.plist"
    if ! codesign -d --entitlements "$entitlements" --xml "$worker" 2>/dev/null \
        || [ ! -s "$entitlements" ]
    then
        rm -rf -- "$temp_dir"
        fail_install "Could not extract inference worker entitlements."
        return 1
    fi

    [ "$(plist_value "$entitlements" 'com.apple.application-identifier' || true)" = "SLDQ2GJ6TL.io.darkbloom.provider.inference-worker" ] \
        && [ "$(plist_value "$entitlements" 'keychain-access-groups:0' || true)" = "SLDQ2GJ6TL.io.darkbloom.provider" ] \
        && ! plist_value "$entitlements" 'keychain-access-groups:1' >/dev/null \
        && [ "$(plist_value "$entitlements" 'com.apple.security.app-sandbox' || true)" = "true" ] \
        && [ "$(plist_value "$entitlements" 'com.apple.security.files.bookmarks.app-scope' || true)" = "true" ] \
        || {
            rm -rf -- "$temp_dir"
            fail_install "Inference worker must have its exact application identity, shared provider key group, App Sandbox, and brokered model access."
            return 1
        }

    local keys key
    keys=$(/usr/libexec/PlistBuddy -c Print "$entitlements" 2>/dev/null \
        | sed -n 's/^[[:space:]]*\([^ =][^ =]*\)[[:space:]]*=.*$/\1/p')
    set -- $keys
    [ "$#" -eq 4 ] || {
        rm -rf -- "$temp_dir"
        fail_install "Inference worker entitlement allowlist is not exact."
        return 1
    }
    for key in $keys; do
        case "$key" in
            com.apple.application-identifier|keychain-access-groups|com.apple.security.app-sandbox|com.apple.security.files.bookmarks.app-scope)
                ;;
            *)
                rm -rf -- "$temp_dir"
                fail_install "Inference worker carries forbidden entitlement: $key."
                return 1
                ;;
        esac
    done
    rm -rf -- "$temp_dir"
}

verify_worker_bundle() {
    local app=$1
    local app_info="$app/Contents/Info.plist"
    local xpc="$app/$WORKER_BUNDLE_RELATIVE_PATH"
    local info="$xpc/Contents/Info.plist"
    local worker="$xpc/$WORKER_EXECUTABLE_RELATIVE_PATH"
    local worker_metallib="$xpc/Contents/MacOS/mlx.metallib"
    local worker_profile="$xpc/Contents/embedded.provisionprofile"
    local worker_resources="$xpc/Contents/Resources"
    local paged_resource="$worker_resources/mlx-swift-lm_MLXLMCommon.bundle/pagedattention.metal"
    local paged_bundle="${paged_resource%/*}"
    [ -d "$xpc" ] && [ ! -L "$xpc" ] \
        && [ -f "$info" ] && [ ! -L "$info" ] \
        && [ -f "$worker_profile" ] && [ ! -L "$worker_profile" ] && [ -s "$worker_profile" ] \
        && [ -f "$worker" ] && [ ! -L "$worker" ] && [ -x "$worker" ] \
        || {
            fail_install "Release is missing the regular executable DarkbloomInferenceWorker.xpc bundle."
            return 1
        }
    [ "$(plist_value "$info" CFBundleIdentifier || true)" = "io.darkbloom.provider.inference-worker" ] \
        && [ "$(plist_value "$info" CFBundleExecutable || true)" = "darkbloom-inference-worker" ] \
        && [ "$(plist_value "$info" CFBundlePackageType || true)" = "XPC!" ] \
        && [ "$(plist_value "$info" 'XPCService:ServiceType' || true)" = "Application" ] \
        && [ "$(plist_value "$info" CFBundleVersion || true)" = "$(plist_value "$app_info" CFBundleVersion || true)" ] \
        && [ "$(plist_value "$info" CFBundleShortVersionString || true)" = "$(plist_value "$app_info" CFBundleShortVersionString || true)" ] \
        || {
            fail_install "Inference worker Info.plist has the wrong service identity, executable, type, or version."
            return 1
        }
    [ ! -e "$xpc/Contents/Frameworks" ] \
        && [ ! -e "$xpc/Contents/Helpers" ] \
        && [ ! -e "$xpc/Contents/PlugIns" ] \
        && [ ! -e "$xpc/Contents/SharedSupport" ] \
        || {
            fail_install "Inference worker bundle contains an unapproved nested code or support directory."
            return 1
        }
    [ -f "$worker_metallib" ] && [ ! -L "$worker_metallib" ] && [ -s "$worker_metallib" ] \
        && [ -d "$worker_resources" ] && [ ! -L "$worker_resources" ] \
        && [ -d "$paged_bundle" ] && [ ! -L "$paged_bundle" ] \
        && [ -f "$paged_resource" ] && [ ! -L "$paged_resource" ] && [ -s "$paged_resource" ] \
        || {
            fail_install "Inference worker is missing its sealed MLX metallib or paged-attention resource."
            return 1
        }
    [ -z "$(find "$worker_resources" -mindepth 1 \
        ! -path "$paged_bundle" ! -path "$paged_resource" -print -quit)" ] || {
            fail_install "Inference worker bundle contains an unapproved runtime resource."
            return 1
        }
    verify_worker_profile "$worker_profile" || return 1


    verify_code_requirement "$xpc" 1 "$WORKER_REQUIREMENT" || {
        fail_install "Inference worker does not satisfy the pinned Team ID and bundle identity requirement."
        return 1
    }
    verify_code_requirement "$worker" 0 "$WORKER_REQUIREMENT" || {
        fail_install "Inference worker executable does not satisfy the pinned Team ID and signing identity requirement."
        return 1
    }
    verify_worker_entitlements "$worker" || return 1
    local sandbox_output sandbox_probe
    sandbox_probe=$worker
    if [ "$INSTALL_TEST_MODE" = "1" ]; then
        # Apple-issued profiles cannot be fabricated for an ad-hoc packaging
        # fixture. The test-only entrypoint supplies an unsigned probe while
        # the staged worker's exact signature and entitlements are still
        # verified above.
        [ -n "$SANDBOX_TEST_PROBE" ] \
            && [ -f "$SANDBOX_TEST_PROBE" ] \
            && [ ! -L "$SANDBOX_TEST_PROBE" ] \
            && [ -x "$SANDBOX_TEST_PROBE" ] || {
                fail_install "Inference worker test probe is invalid."
                return 1
            }
        sandbox_probe=$SANDBOX_TEST_PROBE
    fi
    sandbox_output=$(DARKBLOOM_SIGNED_HOST_TEST=1 \
        "$sandbox_probe" --sandbox-self-test-v1) || {
            fail_install "Inference worker sandbox self-test did not complete."
            return 1
        }
    [ "$sandbox_output" = "DBXPC_SANDBOX_SELF_TEST_V1:63" ] || {
        fail_install "Inference worker sandbox self-test did not deny every prohibited operation."
        return 1
    }
}


verify_fan_helper_capability() {
    local app=$1
    local executable="$app/Contents/MacOS/darkbloom"
    local marker="$app/Contents/Resources/darkbloom-runtime-capabilities/fan-helper-v1"
    local helper="$app/Contents/Helpers/darkbloom-fan-helper"
    local code_present=0
    local marker_present=0
    local helper_present=0

    LC_ALL=C grep -a -q -F 'darkbloom-fan-helper-v1' "$executable" \
        && code_present=1
    if [ -e "$marker" ] || [ -L "$marker" ]; then marker_present=1; fi
    if [ -e "$helper" ] || [ -L "$helper" ]; then helper_present=1; fi
    [ "$code_present" -eq "$marker_present" ] \
        && [ "$marker_present" -eq "$helper_present" ] || {
        fail_install "Fan-helper CLI capability, marker, and nested helper must be present together."
        return 1
    }
    [ "$marker_present" -eq 1 ] || return 0

    [ -f "$marker" ] && [ ! -L "$marker" ] \
        && [ "$(tr -d '[:space:]' < "$marker")" = "1" ] || {
        fail_install "Fan-helper capability marker is invalid."
        return 1
    }
    [ -f "$helper" ] && [ ! -L "$helper" ] && [ -x "$helper" ] || {
        fail_install "Bundled fan helper must be a regular executable, not a symlink."
        return 1
    }
    [ "$(stat -f '%Lp' "$helper" 2>/dev/null || true)" = "755" ] || {
        fail_install "Bundled fan helper must have mode 0755."
        return 1
    }
    verify_code_requirement "$helper" 0 "$FAN_HELPER_REQUIREMENT" || {
        fail_install "Bundled fan helper does not satisfy the pinned helper signature requirement."
        return 1
    }
}

verify_staged_app() {
    local app=$1

    if [ "$INSTALL_TEST_MODE" = "1" ]; then
        codesign --verify --deep --strict --verbose=2 "$app" >/dev/null 2>&1 || {
            fail_install "Strict code-signature verification failed for staged Darkbloom.app."
            return 1
        }
    else
        verify_staged_app_signature "$app" || return 1
    fi
    verify_worker_bundle "$app" || return 1
    verify_fan_helper_capability "$app" || return 1
}

verify_staged_app_payload() {
    local app=$1
    local binary_hash=$2
    local metallib_hash=$3
    local app_bin="$app/Contents/MacOS"
    local worker_metallib="$app/$WORKER_BUNDLE_RELATIVE_PATH/Contents/MacOS/mlx.metallib"
    [ -n "$binary_hash" ] && [ -n "$metallib_hash" ] || {
        fail_install "App releases require binary_hash and metallib_hash."
        return 1
    }
    verify_file_hash "$app_bin/darkbloom" "$binary_hash" "App binary" \
        && verify_file_hash "$worker_metallib" "$metallib_hash" "Worker metallib"
}

restore_launcher_snapshot() {
    local transaction=$1
    local install_dir=$2
    local name current previous restore_failed=0
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        current="$install_dir/bin/$name"
        previous="$transaction/previous-links/$name"
        if [ -e "$previous" ] || [ -L "$previous" ]; then
            if [ -e "$current" ] || [ -L "$current" ]; then
                rm -f -- "$current" || {
                    restore_failed=1
                    continue
                }
            fi
            mv -h "$previous" "$current" || restore_failed=1
        elif [ -e "$transaction/previous-absent/$name" ]; then
            if [ -e "$current" ] || [ -L "$current" ]; then
                rm -f -- "$current" || restore_failed=1
            fi
        fi
    done
    [ "$restore_failed" -eq 0 ]
}

commit_staged_app() {
    local staged_app=$1
    local install_dir=$2
    local destination="$install_dir/Darkbloom.app"
    local transaction had_previous=0 name current rollback_failed
    mkdir -p "$install_dir/bin" || {
        fail_install "Could not prepare the launcher directory."
        return 1
    }
    transaction=$(mktemp -d "$install_dir/.install-transaction.XXXXXX") || {
        fail_install "Could not allocate an installation transaction directory."
        return 1
    }
    if ! chmod 0700 "$transaction" \
        || ! mkdir "$transaction/links" \
            "$transaction/previous-links" \
            "$transaction/previous-absent"
    then
        rm -rf -- "$transaction"
        fail_install "Could not secure the installation transaction directory."
        return 1
    fi

    local staged_bin="$staged_app/Contents/MacOS"
    local staged_worker_bin="$staged_app/$WORKER_BUNDLE_RELATIVE_PATH/Contents/MacOS"
    chmod +x \
        "$staged_bin/darkbloom" \
        "$staged_bin/darkbloom-enclave" \
        "$staged_worker_bin/darkbloom-inference-worker" || {
            rm -rf -- "$transaction"
            fail_install "Could not finalize staged executable permissions."
            return 1
        }

    if ! ln -s "../Darkbloom.app/Contents/MacOS/darkbloom" \
        "$transaction/links/darkbloom" \
        || ! ln -s "../Darkbloom.app/Contents/MacOS/darkbloom-enclave" \
            "$transaction/links/darkbloom-enclave" \
        || ! ln -s "../Darkbloom.app/$WORKER_BUNDLE_RELATIVE_PATH/Contents/MacOS/mlx.metallib" \
            "$transaction/links/mlx.metallib" \
        || ! ln -s "darkbloom-enclave" \
            "$transaction/links/eigeninference-enclave"
    then
        rm -rf -- "$transaction"
        fail_install "Could not prepare atomic launcher replacements."
        return 1
    fi

    # Prior releases installed regular flat files. They are legitimate upgrade
    # inputs alongside current symlinks; directories, devices, sockets, and
    # other special objects are never replaced.
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        current="$install_dir/bin/$name"
        if [ -e "$current" ] || [ -L "$current" ]; then
            if [ ! -L "$current" ] && [ ! -f "$current" ]; then
                rm -rf -- "$transaction"
                fail_install "Refusing to replace unsafe launcher object at $current."
                return 1
            fi
        else
            : > "$transaction/previous-absent/$name"
        fi
    done

    # Remove the entire previous launcher set into the transaction before any
    # new link is exposed. Every subsequent failure restores this snapshot.
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        current="$install_dir/bin/$name"
        if [ -e "$current" ] || [ -L "$current" ]; then
            if ! mv -h "$current" "$transaction/previous-links/$name"; then
                if ! restore_launcher_snapshot "$transaction" "$install_dir"; then
                    fail_install "Launcher snapshot failed and could not be fully restored from $transaction."
                    return 1
                fi
                rm -rf -- "$transaction"
                fail_install "Could not snapshot the previous launcher set."
                return 1
            fi
        fi
    done

    if [ -e "$destination" ] || [ -L "$destination" ]; then
        [ -d "$destination" ] && [ ! -L "$destination" ] || {
            restore_launcher_snapshot "$transaction" "$install_dir" || {
                fail_install "Existing app was unsafe and launcher restoration failed from $transaction."
                return 1
            }
            rm -rf -- "$transaction"
            fail_install "Existing Darkbloom.app is not a regular app directory."
            return 1
        }
        if ! mv "$destination" "$transaction/previous.app"; then
            if ! restore_launcher_snapshot "$transaction" "$install_dir"; then
                fail_install "App snapshot failed and launchers could not be fully restored from $transaction."
                return 1
            fi
            rm -rf -- "$transaction"
            fail_install "Could not begin the app replacement transaction."
            return 1
        fi
        had_previous=1
    fi

    if ! mv "$staged_app" "$destination"; then
        rollback_failed=0
        if [ "$had_previous" -eq 1 ] \
            && ! mv "$transaction/previous.app" "$destination"
        then
            rollback_failed=1
        fi
        restore_launcher_snapshot "$transaction" "$install_dir" \
            || rollback_failed=1
        if [ "$rollback_failed" -ne 0 ]; then
            fail_install "App activation failed and rollback was incomplete; recovery state remains at $transaction."
            return 1
        fi
        rm -rf -- "$transaction"
        fail_install "Could not activate the staged app; previous app and launchers were restored."
        return 1
    fi

    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        if ! mv -h "$transaction/links/$name" "$install_dir/bin/$name"; then
            rollback_failed=0
            if ! mv "$destination" "$staged_app"; then
                rollback_failed=1
            elif [ "$had_previous" -eq 1 ] \
                && ! mv "$transaction/previous.app" "$destination"
            then
                rollback_failed=1
            fi
            restore_launcher_snapshot "$transaction" "$install_dir" \
                || rollback_failed=1
            if [ "$rollback_failed" -ne 0 ]; then
                fail_install "Launcher activation failed and rollback was incomplete; recovery state remains at $transaction."
                return 1
            fi
            rm -rf -- "$transaction"
            fail_install "Launcher activation failed; previous app and launcher set were restored."
            return 1
        fi
    done

    rm -rf -- "$transaction" || {
        fail_install "Installed app, but could not remove its private transaction backup."
        return 1
    }
}


install_bundle_atomically() {
    local archive=$1
    local install_dir=$2
    local binary_hash=${3:-}
    local metallib_hash=${4:-}
    local stage
    mkdir -p "$install_dir" || return 1
    stage=$(mktemp -d "$install_dir/.install-staging.XXXXXX") || {
        fail_install "Could not allocate a private extraction directory."
        return 1
    }
    chmod 0700 "$stage"
    [ ! -L "$stage" ] \
        && [ "$(stat -f '%Lp' "$stage" 2>/dev/null || true)" = "700" ] \
        && [ "$(stat -f '%u' "$stage" 2>/dev/null || true)" = "$(id -u)" ] \
        || {
            rm -rf -- "$stage"
            fail_install "Extraction directory is not private to the current user."
            return 1
        }
    if ! tar xzf "$archive" -C "$stage"; then
        rm -rf "$stage"
        return 1
    fi

    local app="$stage/Darkbloom.app"
    local flat_bin="$stage/bin"
    [ -d "$app" ] && [ ! -L "$app" ] || {
        rm -rf "$stage"
        fail_install "Mature releases require the complete Darkbloom.app with its inference worker; flat artifacts are rejected."
        return 1
    }
    [ -f "$flat_bin/darkbloom" ] && [ ! -L "$flat_bin/darkbloom" ] \
        && [ -f "$flat_bin/darkbloom-enclave" ] && [ ! -L "$flat_bin/darkbloom-enclave" ] \
        && [ -f "$flat_bin/mlx.metallib" ] && [ ! -L "$flat_bin/mlx.metallib" ] \
        || {
            rm -rf "$stage"
            fail_install "Release bundle is missing required regular flat verifier files."
            return 1
        }
    verify_staged_app "$app" || {
        rm -rf "$stage"
        return 1
    }
    verify_staged_app_payload "$app" "$binary_hash" "$metallib_hash" || {
        rm -rf "$stage"
        return 1
    }
    verify_file_hash "$flat_bin/darkbloom" "$binary_hash" "Binary" || {
        rm -rf "$stage"
        return 1
    }
    verify_file_hash "$flat_bin/mlx.metallib" "$metallib_hash" "Metallib" || {
        rm -rf "$stage"
        return 1
    }
    cmp -s "$flat_bin/darkbloom" "$app/Contents/MacOS/darkbloom" \
        && cmp -s "$flat_bin/darkbloom-enclave" "$app/Contents/MacOS/darkbloom-enclave" \
        && cmp -s "$flat_bin/mlx.metallib" \
            "$app/$WORKER_BUNDLE_RELATIVE_PATH/Contents/MacOS/mlx.metallib" || {
            rm -rf "$stage"
            fail_install "Flat verifier files do not match the signed app payload."
            return 1
        }
    commit_staged_app "$app" "$install_dir" || {
        rm -rf "$stage"
        fail_install "App replacement transaction failed; installation was not reported successful."
        return 1
    }
    rm -rf "$stage"
}

if [ "${1:-}" = "--verify-staged-app-signature-test" ]; then
    [ "$#" -eq 3 ] || {
        echo "usage: $0 --verify-staged-app-signature-test <app> <requirement>" >&2
        exit 64
    }
    verify_staged_app_signature "$2" "$3"
    exit $?
fi

if [ "${1:-}" = "--verify-worker-signature-test" ]; then
    [ "$#" -eq 4 ] || {
        echo "usage: $0 --verify-worker-signature-test <xpc-bundle> <worker-executable> <requirement>" >&2
        exit 64
    }
    verify_code_requirement "$2" 1 "$4" \
        && verify_code_requirement "$3" 0 "$4"
    exit $?
fi

if [ "${1:-}" = "--secure-download-test" ]; then
    [ "$#" -eq 3 ] || {
        echo "usage: $0 --secure-download-test <url> <expected-hash>" >&2
        exit 64
    }
    secure_download_release "$2"
    verify_file_hash "$TARBALL" "$3" "Secure download fixture"
    cleanup_download_bundle
    trap - EXIT HUP INT TERM
    exit 0
fi

if [ "${1:-}" = "--verify-download-path-test" ]; then
    [ "$#" -eq 2 ] || {
        echo "usage: $0 --verify-download-path-test <archive>" >&2
        exit 64
    }
    verify_download_archive_path "$2"
    exit $?
fi

if [ "${1:-}" = "--install-bundle-test" ]; then
    [ "$#" -eq 8 ] || {
        echo "usage: $0 --install-bundle-test <archive> <install-dir> <binary-hash> <metallib-hash> <fan-helper-requirement> <worker-requirement> <unsigned-sandbox-probe>" >&2
        exit 64
    }
    INSTALL_TEST_MODE=1
    FAN_HELPER_REQUIREMENT=$6
    WORKER_REQUIREMENT=$7
    SANDBOX_TEST_PROBE=$8
    install_bundle_atomically "$2" "$3" "$4" "$5"
    exit $?
fi

# Detect interactive vs piped (curl | bash).
if [ -t 0 ]; then
    INTERACTIVE=true
else
    INTERACTIVE=false
fi

echo "╔══════════════════════════════════════════════╗"
echo "║  Darkbloom — Private AI on Verified Macs     ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── Pre-flight checks ───────────────────────────────────────
if [ "$(uname)" != "Darwin" ]; then
    echo "Error: Darkbloom requires macOS with Apple Silicon."
    exit 1
fi
if [ "$(uname -m)" != "arm64" ]; then
    echo "Error: Darkbloom requires Apple Silicon (arm64)."
    exit 1
fi

CHIP=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "Apple Silicon")
MEM=$(sysctl -n hw.memsize 2>/dev/null | awk '{printf "%.0f", $1/1073741824}')
MACOS=$(sw_vers -productVersion 2>/dev/null || echo "?")
echo "  $CHIP · ${MEM}GB · macOS $MACOS"
echo ""

# ─── Step 1: Fetch latest release ────────────────────────────
echo "→ [1/5] Fetching latest release from $COORD_URL ..."

RELEASE_JSON=$(curl -fsSL "$COORD_URL/v1/releases/latest" 2>/dev/null || echo "")
if [ -z "$RELEASE_JSON" ]; then
    echo "  ✗ Could not reach coordinator at $COORD_URL"
    echo "    Check your internet connection and try again."
    exit 1
fi

# Extract JSON string fields with sed — no python3 needed (no Xcode CLT prompt).
json_val() { echo "$1" | sed -n "s/.*\"$2\":\"\([^\"]*\)\".*/\1/p"; }
BUNDLE_URL=$(json_val "$RELEASE_JSON" url)
BUNDLE_HASH=$(json_val "$RELEASE_JSON" bundle_hash)
BINARY_HASH=$(json_val "$RELEASE_JSON" binary_hash)
METALLIB_HASH=$(json_val "$RELEASE_JSON" metallib_hash)
VERSION=$(json_val "$RELEASE_JSON" version)
BACKEND=$(json_val "$RELEASE_JSON" backend)

if [ -z "$BUNDLE_URL" ] || [ -z "$BUNDLE_HASH" ] || [ -z "$VERSION" ]; then
    echo "  ✗ Coordinator response missing required fields (url / bundle_hash / version)."
    echo "    Raw response: $RELEASE_JSON"
    exit 1
fi

echo "  Version: $VERSION"
echo "  Backend: ${BACKEND:-mlx-swift}"
echo "  Signed by: Developer ID Application: Eigen Labs, Inc."
echo ""

# ─── Step 2: Download + verify bundle ────────────────────────
echo "→ [2/5] Downloading Darkbloom v${VERSION}..."
mkdir -p "$INSTALL_DIR" "$BIN_DIR"

secure_download_release "$BUNDLE_URL"

ACTUAL_HASH=$(shasum -a 256 "$TARBALL" | cut -d' ' -f1)
if [ "$ACTUAL_HASH" != "$BUNDLE_HASH" ]; then
    echo ""
    echo "  ✗ Bundle hash mismatch — refusing to install possibly-tampered binary."
    echo "    Expected: $BUNDLE_HASH"
    echo "    Got:      $ACTUAL_HASH"
    exit 1
fi
echo "  Bundle hash verified ✓"

echo "  Staging and verifying the complete app before touching the live install ..."
verify_download_archive_path "$TARBALL"
PRE_EXTRACT_HASH=$(shasum -a 256 "$TARBALL" | cut -d' ' -f1)
if [ "$PRE_EXTRACT_HASH" != "$BUNDLE_HASH" ]; then
    fail_install "Release archive changed after verification; refusing extraction."
    exit 1
fi
if ! install_bundle_atomically "$TARBALL" "$INSTALL_DIR" "$BINARY_HASH" "$METALLIB_HASH"; then
    echo "  Existing installation was left unchanged."
    exit 1
fi
cleanup_download_bundle
trap - EXIT HUP INT TERM
echo "  Strict signature, runtime resources, and atomic swap verified ✓"

# Make available in PATH. Try /usr/local/bin symlink, fall back to shell rc.
if ln -sf "$BIN_DIR/darkbloom" /usr/local/bin/darkbloom 2>/dev/null; then
    :
fi
RC="$HOME/.zshrc"
if [ -f "$HOME/.bashrc" ] && [ ! -f "$HOME/.zshrc" ]; then
    RC="$HOME/.bashrc"
fi
if ! grep -q "\.darkbloom/bin" "$RC" 2>/dev/null; then
    sed -i '' '/\.dginf\/bin/d; /\.eigeninference\/bin/d; /alias eigeninf/d; /alias dginf/d; /# EigenInference/d; /# Darkbloom$/d' "$RC" 2>/dev/null || true
    cat >> "$RC" << 'SHELL'

# Darkbloom
export PATH="$HOME/.darkbloom/bin:$PATH"
SHELL
fi
export PATH="$BIN_DIR:$PATH"

# Source rc so commands work in this shell. Disable -eu around it: rc files
# may use unbound vars or shell-specific builtins that fail under bash strict.
set +eu
source "$RC" 2>/dev/null || true
set -eu

echo "  Binaries installed ✓"
echo "  Shortcut: darkbloom"

# ─── Migrate from old installs ───────────────────────────────
# Migration chain: ~/.dginf → ~/.eigeninference → ~/.darkbloom
for OLD_DIR in "$HOME/.dginf" "$HOME/.eigeninference"; do
    if [ -d "$OLD_DIR" ] && [ ! -L "$OLD_DIR" ]; then
        echo ""
        echo "  Migrating from $OLD_DIR..."
        for f in enclave_key.data wallet_key auth_token; do
            [ -f "$OLD_DIR/$f" ] && cp -n "$OLD_DIR/$f" "$INSTALL_DIR/$f" 2>/dev/null || true
        done
        # Symlink old path so stragglers still work, then drop the old python/
        # subtree -- the Swift release no longer needs it.
        ln -sfn "$INSTALL_DIR" "$OLD_DIR" 2>/dev/null || true
        echo "  Migration complete ✓"
    fi
done

# ─── Step 3: Secure Enclave identity ─────────────────────────
echo ""
echo "→ [3/5] Provisioning Secure Enclave identity..."
if "$BIN_DIR/darkbloom-enclave" info >/dev/null 2>&1; then
    echo "  Secure Enclave ✓ (P-256 key generated)"
else
    echo "  Secure Enclave ⚠ (not available on this hardware; provider will run with reduced trust)"
fi

# ─── Step 4: Enrollment + device attestation ─────────────────
echo ""
echo "→ [4/5] Enrollment + device attestation..."

ALREADY_ENROLLED=false
if profiles status -type enrollment 2>&1 | grep -q "MDM enrollment: Yes"; then
    ALREADY_ENROLLED=true
fi

if [ "$ALREADY_ENROLLED" = true ]; then
    echo "  Already enrolled ✓"
else
    echo "  Requesting enrollment profile from coordinator..."
    PROFILE_DIR="$(mktemp -d "${TMPDIR:-/tmp}/Darkbloom-Enroll.XXXXXX")"
    PROFILE_PATH="$PROFILE_DIR/Darkbloom-Enroll.mobileconfig"
    if curl -fsSL -X POST "$COORD_URL/v1/enroll" \
        -H "Content-Type: application/json" \
        -d '{}' \
        -o "$PROFILE_PATH" 2>/dev/null; then
        echo ""
        echo "  ┌──────────────────────────────────────────────────┐"
        echo "  │ ACTION REQUIRED: Install the enrollment profile  │"
        echo "  │                                                  │"
        echo "  │ This profile lets the coordinator verify:        │"
        echo "  │  • SIP, Secure Boot, system integrity            │"
        echo "  │  • Your Secure Enclave is genuine Apple silicon  │"
        echo "  │  • Device identity signed by Apple's Root CA     │"
        echo "  │                                                  │"
        echo "  │ Darkbloom CANNOT erase, lock, or control         │"
        echo "  │ your Mac. Remove anytime in System Settings.     │"
        echo "  └──────────────────────────────────────────────────┘"
        echo ""
        open "$PROFILE_PATH"
        sleep 1
        open "x-apple.systempreferences:com.apple.Profiles-Settings.extension"

        echo "  System Settings opened — click Install and enter your password."
        if [ "$INTERACTIVE" = true ]; then
            echo ""
            read -p "  Press Enter once you have installed the profile..." || true
        else
            echo "  After installing, the provider will verify on first start."
            sleep 3
        fi
        if profiles status -type enrollment 2>&1 | grep -q "MDM enrollment: Yes"; then
            echo "  Enrollment verified ✓"
        else
            echo "  Enrollment pending ⚠ (complete it in System Settings, or run: darkbloom enroll)"
        fi
    else
        echo "  Enrollment ⚠ (coordinator unreachable — enroll later with: darkbloom enroll)"
    fi
fi

# ─── Step 5: Optional starter model ──────────────────────────
echo ""
echo "→ [5/5] Inference model..."

CATALOG_JSON=$(curl -fsSL "$COORD_URL/v1/models/catalog?type=text" 2>/dev/null || echo "")

if [ -n "$CATALOG_JSON" ]; then
    if [ "$INTERACTIVE" = true ]; then
        echo ""
        echo "  Available text models:"
        echo "$CATALOG_JSON" \
          | tr ',' '\n' \
          | sed -n 's/.*"id":"\([^"]*\)".*"display_name":"\([^"]*\)".*"size_gb":\([0-9.]*\).*"min_ram_gb":\([0-9]*\).*/  • \2  ~\3 GB  (≥\4 GB RAM)  [\1]/p' \
          | head -20
        echo ""
        echo "  Download a model with:"
        echo "    darkbloom models download <id>"
    else
        echo "  Run interactively to pick a starter model:"
        echo "    curl -fsSL $COORD_URL/install.sh | bash -s"
        echo "  Or list the catalog with:  darkbloom models catalog"
    fi
else
    echo "  Could not fetch model catalog (continuing anyway)."
fi

# ─── Done ────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  Install complete                            ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "  Next steps:"
echo "    darkbloom doctor             # verify the system is ready"
echo "    darkbloom models catalog     # browse available models"
echo "    darkbloom models download <id>"
echo "    darkbloom login              # link this Mac to your account"
echo "    darkbloom start              # serve inference (interactive picker)"
echo ""
