-- request_waterfall: one row per dispatched attempt, joining the system
-- profiler's request_profiles row with the routing-telemetry inference_routes
-- row on (request_id, attempt). Consumed by the admin UI / ad-hoc analysis.
--
-- THIS VIEW IS NOT IN THE COORDINATOR'S BOOT MIGRATION SLICE (postgres.go
-- migrate()). Like dedupe_provider_earnings.sql it is applied BY HAND with psql,
-- out of band and off the deploy path:
--
--     psql "$EIGENINFERENCE_DATABASE_URL" -f coordinator/store/migrations/request_waterfall.sql
--
-- Rationale: a CREATE VIEW at boot would queue behind any long-running query's
-- relation lock on inference_routes (the 2026-07-03 outage class), and the
-- column list below is a reviewed privacy surface that should not change as a
-- side effect of a deploy. Re-run (CREATE OR REPLACE) whenever a column is
-- added to request_profiles that the waterfall should expose. CREATE OR
-- REPLACE can only APPEND output columns: when a column is inserted mid-list,
-- renamed or dropped, DROP VIEW request_waterfall first, then re-apply.
--
-- The column list is explicit on purpose. `r.*` would silently pull identity
-- columns (consumer_key_hash, key_id), the prompt-derived cache_affinity_key
-- and verbatim provider strings (provider_version, hardware_chip,
-- hardware_chip_family, hardware_tier, system_thermal_state, slot_state) into
-- an admin surface; request_profiles already carries the folded equivalents.
-- TestRequestWaterfallViewListsEveryProfileColumn checks that every
-- request_profiles column appears as p.<col>, that none of the excluded
-- inference_routes columns appear, and (with DATABASE_URL) that the statement
-- is valid against the migrated schema.
--
-- LEFT JOIN: the inference_routes INSERT rides the drop-on-full telemetry sink,
-- so a profile can exist without its route row; the waterfall must still show
-- it (route_* columns are NULL in that case).

CREATE OR REPLACE VIEW request_waterfall AS
SELECT
    p.id,
    p.coord_request_id,
    p.request_id,
    p.attempt,
    p.backup_of,
    p.winning,
    p.endpoint,
    p.stream,
    p.model,
    p.public_model,
    p.provider_id,
    p.provider_version,
    p.chip_family,
    p.kv_backend,
    p.final_status,
    p.error_reason,
    p.terminal_cause,
    p.client_outcome,
    p.provider_outcome,
    p.client_gone_phase,
    p.first_content_budget_ms,
    p.admission_mode,
    p.estimated_prompt_tokens,
    p.requested_max_tokens,
    p.requires_vision,
    p.has_tools,
    p.received_at,

    p.auth_done_us,
    p.ratelimit_done_us,
    p.sealed_open_us,
    p.handler_entry_us,
    p.parsed_us,
    p.reserved_us,
    p.media_fetched_us,
    p.preflight_done_us,
    p.plan_done_us,
    p.attempt_start_us,
    p.reserve_lock_acquired_us,
    p.reserve_done_us,
    p.queued_us,
    p.dequeued_us,
    p.topup_done_us,
    p.encrypted_us,
    p.write_submitted_us,
    p.write_dequeued_us,
    p.write_done_us,
    p.accepted_us,
    p.first_chunk_ingress_us,
    p.first_chunk_dequeued_us,
    p.first_content_ingress_us,
    p.first_content_us,
    p.headers_written_us,
    p.first_flush_us,
    p.last_flush_us,
    p.client_gone_us,
    p.cancel_sent_us,
    p.complete_ingress_us,
    p.done_flushed_us,
    p.finalized_us,
    p.settle_db_us,
    p.db_us,
    p.db_calls,

    p.body_bytes,
    p.sealed_body_bytes,
    p.auth_kind,
    p.auth_db_read,
    p.reserve_mode,
    p.media_items,
    p.media_bytes,
    p.preflight_outcome,
    p.plan_outcome,
    p.chunks_in,
    p.chunks_out,
    p.bytes_out,
    p.decrypt_us_total,
    p.max_chunk_gap_us,
    p.held_preamble_chunks,
    p.client_write_err,
    p.attempts_total,
    p.failed_attempts,
    p.failed_attempts_us,
    p.backup_launched,
    p.backup_won,
    p.transport_est_us,
    p.slept_us,
    p.timing_anomaly,

    p.candidate_set_size,
    p.scanned,
    p.gate_rejections,
    p.runner_up_provider_id,
    p.runner_up_cost_ms,
    p.near_tie_pool_size,
    p.selection_path,
    p.best_idle_provider_id,
    p.best_idle_ttft_ms,
    p.predicted_ttft_ms,
    p.raw_ttft_ms,
    p.predicted_decode_tps,
    p.snapshot_age_ms,
    p.pending_for_model,
    p.total_pending,
    p.capacity_rate_ms,
    p.cache_discount_ms,
    p.shadow_would_shed,
    p.shadow_idle_alternative,
    p.lock_wait_us,
    p.scan_us,
    p.admit_us,
    p.preflight_us,
    p.ttft_calibration_ratio,
    p.prefill_decode_ratio,
    p.queue_position_at_enqueue,
    p.queue_depth_at_enqueue,
    p.drain_trigger,
    p.candidates,

    p.prov_total_us,
    p.prov_first_delta_us,
    p.prov_engine_submit_us,
    p.prov_engine_admitted_us,
    p.prov_prompt_prep_us,
    p.prov_load_wait_us,
    p.prov_load_cold,
    p.prov_running_at_admit,
    p.prov_waiting_at_admit,
    p.prov_kv_bytes_in_use_at_admit,
    p.prov_cancel_stage,
    p.eng_queue_wait_ns,
    p.eng_first_token_ns,
    p.eng_prompt_computed_ns,
    p.eng_prefill_chunks,
    p.eng_decode_steps,
    p.eng_mtp_accepted,
    p.eng_finish_reason,
    p.provider_profile,
    p.provider_profile_valid,
    p.provider_profile_invalid_reason,
    p.provider_profile_consistent,

    p.created_at,

    -- inference_routes: routing decision, provider snapshot numerics, outcome
    -- and latency decomposition. Columns that collide with request_profiles
    -- names are prefixed route_. Identity, prompt-derived and verbatim
    -- provider-string columns are deliberately absent (see header).
    r.id AS route_id,
    r.outcome AS route_outcome,
    r.cost_ms,
    r.state_ms,
    r.queue_ms,
    r.pending_ms,
    r.backlog_ms,
    r.this_req_ms,
    r.health_ms,
    r.ttft_ms,
    r.best_ttft_ms,
    r.effective_queue,
    r.candidate_count,
    r.capacity_rejections,
    r.model_too_large_rejections,
    r.vision_rejections,
    r.ttft_rejections,
    r.effective_tps,
    r.static_tps,
    r.provider_status,
    r.provider_trust_level,
    r.memory_gb,
    r.gpu_cores,
    r.cpu_cores,
    r.system_memory_pressure,
    r.system_cpu_usage,
    r.gpu_memory_active_gb,
    r.gpu_memory_peak_gb,
    r.gpu_memory_cache_gb,
    r.backend_running,
    r.backend_waiting,
    r.active_token_budget_used,
    r.active_token_budget_max,
    r.queued_token_budget,
    r.estimated_prompt_tokens AS route_estimated_prompt_tokens,
    r.requested_max_tokens AS route_requested_max_tokens,
    r.requires_vision AS route_requires_vision,
    r.has_tools AS route_has_tools,
    r.self_route_only,
    r.prefer_owner,
    r.final_status AS route_final_status,
    r.error_code,
    r.error_class,
    r.error_reason AS route_error_reason,
    r.prompt_tokens,
    r.completion_tokens,
    r.reasoning_tokens,
    r.cost_micro_usd,
    r.actual_ttft_ms,
    r.dispatch_to_first_chunk_ms,
    r.total_duration_ms,
    r.parse_ms,
    r.reserve_ms,
    r.route_ms,
    r.encrypt_ms,
    r.queue_wait_ms,
    r.dispatch_ms,
    r.actual_decode_tps,
    r.admitted_but_failed,
    r.used_backup,
    r.backup_won AS route_backup_won,
    r.provider_region,
    r.consumer_region,
    r.created_at AS route_created_at,
    r.updated_at AS route_updated_at
FROM request_profiles p
LEFT JOIN inference_routes r
       ON r.request_id = p.request_id
      AND r.attempt = p.attempt;
