import Foundation
import ArgumentParser
import MLX
import ProviderCore
import Network

/// darkbloom cluster — manage a multi-Mac pipeline-parallel inference cluster.
///
/// Prerequisites on every Mac:
///   1. macOS 26.2+ with Apple Silicon and Thunderbolt 5
///   2. Enable RDMA in macOS Recovery: `rdma enable`
///   3. Connect Macs with Thunderbolt cables and assign static IP addresses
///
/// Setup (run on each Mac):
///   Mac A (rank 0):  darkbloom cluster setup --rank 0 --coordinator :9999 --rdma-device rdma_en2
///   Mac B (rank 1):  darkbloom cluster setup --rank 1 --coordinator 169.254.100.1:9999 --rdma-device rdma_en2
///
/// After setup, start inference:
///   Mac A (rank 0):  darkbloom cluster run --model <id>
///   Mac B (rank 1):  darkbloom cluster run --model <id>
struct Cluster: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "cluster",
        abstract: "Multi-Mac pipeline-parallel inference over RDMA/Thunderbolt.",
        subcommands: [ClusterSetup.self, ClusterDevices.self, ClusterPing.self, ClusterRun.self]
    )
}

// MARK: - cluster setup

struct ClusterSetup: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "setup",
        abstract: "Configure this Mac as a member of a pipeline-parallel cluster."
    )

    @Option(name: .long, help: "Rank of this machine (0 = coordinator/first rank).")
    var rank: Int

    @Option(name: .long, help: "Rank 0's TCP side-channel address for jaccl (e.g. 169.254.100.1:9999 or just :9999 on rank 0).")
    var coordinator: String

    @Option(name: [.customLong("rdma-device")], help: "RDMA interface name(s) to use, comma-separated (e.g. rdma_en2). Omit to auto-detect.")
    var rdmaDevice: String?

    @Option(name: .long, help: "Total number of ranks in the cluster.")
    var size: Int = 2

    @Option(name: [.customLong("peer-serial")], help: "Hardware serial number of the peer Mac (from `system_profiler SPHardwareDataType` on the peer). Used to fetch and pin the peer's SE public key from the coordinator.")
    var peerSerial: String

    @Option(name: [.customLong("peer-ip")], help: "Thunderbolt IP of the peer Mac (e.g. 169.254.58.74). Used as the Keychain key for the pinned SE public key.")
    var peerIP: String

    @Option(name: [.customLong("devices-file")], help: "Path to write the jaccl devices JSON file.")
    var devicesFile: String = "/etc/darkbloom/cluster-devices.json"

    @Option(name: [.customLong("env-file")], help: "Path to write the shell environment file.")
    var envFile: String = "/etc/darkbloom/cluster-env.sh"

    mutating func validate() throws {
        guard rank >= 0 && rank < size else {
            throw ValidationError("--rank must be in 0..<\(size).")
        }
        guard size >= 2 else {
            throw ValidationError("--size must be at least 2.")
        }
        guard !peerSerial.isEmpty else {
            throw ValidationError("--peer-serial is required.")
        }
        guard !peerIP.isEmpty else {
            throw ValidationError("--peer-ip is required.")
        }
    }

    mutating func run() async throws {
        // Step 1: Fetch and pin the peer's SE key from the coordinator.
        try await pinPeerSEKey()

        // Step 2: Detect RDMA interfaces if not specified.
        let device: String
        if let specified = rdmaDevice {
            device = specified
        } else {
            device = try detectRDMADevice()
        }
        print("Using RDMA device: \(device)")

        // Step 3: Resolve coordinator address.
        let coordAddr = try resolveCoordinatorAddress(coordinator, rank: rank)
        print("jaccl coordinator: \(coordAddr)")

        // Step 4: Write devices JSON (2-machine mesh: each connects to the other).
        let devicesJSON = buildDevicesJSON(size: size, myRank: rank, device: device)
        try writeFile(path: devicesFile, content: devicesJSON)
        print("Wrote devices file: \(devicesFile)")

        // Step 5: Write environment file.
        let envContent = """
        # Darkbloom cluster environment — source this before running darkbloom cluster run
        # Generated by: darkbloom cluster setup (rank \(rank))
        export MLX_RANK=\(rank)
        export MLX_JACCL_COORDINATOR=\(coordAddr)
        export MLX_IBV_DEVICES=\(devicesFile)
        export MLX_JACCL_RING=0
        """
        try writeFile(path: envFile, content: envContent)
        print("Wrote environment file: \(envFile)")

        print("""

        Setup complete for rank \(rank).

        To activate: source \(envFile)
        Then start:  darkbloom cluster run --peer-ip \(peerIP)

        Make sure all \(size) Macs have completed setup before running.
        """)
    }

    // MARK: - Peer SE key pinning

    private func pinPeerSEKey() async throws {
        guard let authToken = AuthTokenStore.load() else {
            throw ValidationError("Not logged in. Run `darkbloom login` before `cluster setup`.")
        }

        let config = ConfigManager.loadDefault()
        let wsURL = config.coordinator.url

        print("Fetching SE key for peer serial \(peerSerial) from coordinator…")
        let info = try await ClusterCoordinatorClient.fetchPeerSEKey(
            serial: peerSerial,
            coordinatorWSURL: wsURL,
            authToken: authToken
        )

        guard let keyData = info.sePublicKeyData else {
            throw ValidationError("Coordinator returned an invalid base64 SE key for serial \(peerSerial).")
        }

        try ClusterPeerKeychain.store(peerSEKey: keyData, peerIP: peerIP)

        let trustNote = info.mdaVerified ? " (Apple MDA verified ✓)" : " (trust level: \(info.trustLevel))"
        print("Pinned SE key for \(peerSerial) → Keychain entry for \(peerIP)\(trustNote)")
    }

    // MARK: - Helpers

    private func detectRDMADevice() throws -> String {
        let result = try shell("ibv_devices 2>/dev/null | awk 'NR>2 {print $1}' | head -1")
        let trimmed = result.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            throw ValidationError(
                "No RDMA devices found. Is macOS 26.2+ with RDMA enabled in Recovery? " +
                "Run: rdma enable (in macOS Recovery Terminal)")
        }
        return trimmed
    }

    private func resolveCoordinatorAddress(_ input: String, rank: Int) throws -> String {
        if input.hasPrefix(":") {
            // Port-only form (e.g. ":9999") — this Mac is the coordinator.
            guard rank == 0 else {
                throw ValidationError(
                    "Port-only coordinator address (e.g. ':9999') is only valid for rank 0. " +
                    "Rank \(rank) must specify the full address of rank 0 (e.g. 169.254.100.1:9999).")
            }
            // Resolve our Thunderbolt IP to form the full address for the env file.
            let ip = try detectThunderboltIP() ?? "127.0.0.1"
            let port = String(input.dropFirst())
            return "\(ip)\(input)"  // keep ":port" form — jaccl binds on rank 0
        }
        return input
    }

    private func detectThunderboltIP() throws -> String? {
        // Look for an IP on a wired Ethernet interface that's link-local (169.254.x.x)
        // or a configured static IP — typical for Thunderbolt bridge setups.
        let result = try shell("ifconfig | grep -A1 'bridge\\|en[0-9]' | grep 'inet 169\\.254' | awk '{print $2}' | head -1")
        let trimmed = result.trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }

    // MARK: - Devices JSON

    /// Build a jaccl mesh devices file for `size` ranks where every pair
    /// communicates over `device`.
    ///
    /// Format: `devices[src][dst]` = RDMA interface name from src to dst, or null for self.
    private func buildDevicesJSON(size: Int, myRank: Int, device: String) -> String {
        var rows: [String] = []
        for src in 0 ..< size {
            var cols: [String] = []
            for dst in 0 ..< size {
                if src == dst {
                    cols.append("null")
                } else {
                    cols.append("\"\(device)\"")
                }
            }
            rows.append("  [\(cols.joined(separator: ", "))]")
        }
        return "[\n\(rows.joined(separator: ",\n"))\n]\n"
    }

    // MARK: - File I/O

    private func writeFile(path: String, content: String) throws {
        let url = URL(fileURLWithPath: path)
        let dir = url.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        try content.write(to: url, atomically: true, encoding: .utf8)
    }

    private func shell(_ command: String) throws -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/sh")
        process.arguments = ["-c", command]
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = Pipe()
        try process.run()
        process.waitUntilExit()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        return String(data: data, encoding: .utf8) ?? ""
    }
}

// MARK: - cluster devices

struct ClusterDevices: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "devices",
        abstract: "List RDMA devices available on this Mac."
    )

    mutating func run() async throws {
        print("RDMA availability: \(DistributedGroup.isAvailable ? "yes" : "no (macOS 26.2+ with RDMA enabled required)")")
        print("")

        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/sh")
        process.arguments = ["-c", "ibv_devices 2>&1; echo '---'; ibv_devinfo 2>&1 | grep -E 'hca_id|transport|state|port'"]
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = pipe
        try process.run()
        process.waitUntilExit()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        if let output = String(data: data, encoding: .utf8) {
            print(output)
        }
    }
}

// MARK: - cluster ping

struct ClusterPing: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "ping",
        abstract: "RDMA connectivity smoke test. Run on all ranks simultaneously."
    )

    @Option(name: .long, help: "Rank of this machine (0 = coordinator).")
    var rank: Int

    @Option(name: .long, help: "Total number of ranks.")
    var size: Int = 2

    @Option(name: [.customLong("coordinator")], help: "jaccl coordinator address (rank 0's IP:port, e.g. 169.254.106.209:9999).")
    var coordinator: String

    @Option(name: [.customLong("rdma-device")], help: "RDMA device name (e.g. rdma_en2). Omit to auto-detect.")
    var rdmaDevice: String?

    @Option(name: [.customLong("rounds")], help: "Number of ping-pong rounds.")
    var rounds: Int = 10

    mutating func run() async throws {
        // Build a temporary devices file.
        let device: String
        if let d = rdmaDevice {
            device = d
        } else {
            device = try autoDetectRDMADevice()
        }

        let devicesPath = "/tmp/darkbloom-ping-devices.json"
        let devicesJSON = buildMeshJSON(size: size, device: device)
        try devicesJSON.write(toFile: devicesPath, atomically: true, encoding: .utf8)

        // Set jaccl env vars before initializing.
        setenv("MLX_RANK", "\(rank)", 1)
        setenv("MLX_JACCL_COORDINATOR", coordinator, 1)
        setenv("MLX_IBV_DEVICES", devicesPath, 1)
        setenv("MLX_JACCL_RING", "0", 1)

        print("rank \(rank)/\(size) — coordinator \(coordinator) — device \(device)")
        print("Initializing jaccl…")

        guard let group = DistributedGroup.initialize(strict: false) else {
            print("ERROR: DistributedGroup.initialize() returned nil.")
            print("Check: macOS 26.2+, RDMA enabled in Recovery, env vars set correctly.")
            throw ExitCode.failure
        }
        print("jaccl up — group size=\(group.size) my-rank=\(group.rank)")

        // Warm-up round.
        let warmup = MLXArray([Float(rank)])
        let _ = warmup.allSum(group: group)
        eval(warmup)

        // Timed rounds.
        var totalNs: Double = 0
        for i in 0 ..< rounds {
            let payload = MLXArray([Float(i)])
            let t0 = DispatchTime.now().uptimeNanoseconds
            let result = payload.allSum(group: group)
            eval(result)
            let dt = Double(DispatchTime.now().uptimeNanoseconds - t0)
            totalNs += dt
            let expected = Float(group.size * i)
            let got = result.item(Float.self)
            let ok = abs(got - expected) < 0.5
            print("  round \(i+1)/\(rounds): \(String(format: "%.1f", dt / 1000))µs  result=\(got) [\(ok ? "OK" : "MISMATCH expected \(expected)")]")
        }
        let avgUs = totalNs / Double(rounds) / 1000.0
        print("\nall_sum avg latency: \(String(format: "%.1f", avgUs))µs over \(rounds) rounds")
        print("RDMA link: OK")
    }

    private func autoDetectRDMADevice() throws -> String {
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/bin/sh")
        process.arguments = ["-c", "ibv_devices 2>/dev/null | awk 'NR>2 {print $1}' | head -1"]
        let pipe = Pipe()
        process.standardOutput = pipe
        process.standardError = Pipe()
        try process.run()
        process.waitUntilExit()
        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        let trimmed = (String(data: data, encoding: .utf8) ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            throw ValidationError("No RDMA devices found. Pass --rdma-device explicitly.")
        }
        return trimmed
    }

    private func buildMeshJSON(size: Int, device: String) -> String {
        var rows: [String] = []
        for src in 0 ..< size {
            var cols: [String] = []
            for dst in 0 ..< size {
                cols.append(src == dst ? "null" : "\"\(device)\"")
            }
            rows.append("  [\(cols.joined(separator: ", "))]")
        }
        return "[\n\(rows.joined(separator: ",\n"))\n]\n"
    }
}

// MARK: - cluster run

/// Starts the encrypted pipeline-parallel cluster on this Mac.
///
/// Run on rank 0 first (it will wait for rank 1 to connect), then rank 1.
///
/// Example:
///   Mac A (rank 0):  darkbloom cluster run --rank 0 --peer-ip 169.254.58.74
///   Mac B (rank 1):  darkbloom cluster run --rank 1 --peer-ip 169.254.106.209
struct ClusterRun: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "run",
        abstract: "Start encrypted pipeline-parallel inference. Run on all ranks simultaneously."
    )

    @Option(name: .long, help: "Rank of this machine (0 = initiator, 1 = responder).")
    var rank: Int

    @Option(name: [.customLong("peer-ip")], help: "The other Mac's Thunderbolt IP address.")
    var peerIP: String

    @Option(name: .long, help: "TCP port for the cluster session (default: 7777).")
    var port: UInt16 = 7777

    mutating func validate() throws {
        guard rank == 0 || rank == 1 else {
            throw ValidationError("--rank must be 0 or 1.")
        }
        guard !peerIP.isEmpty else {
            throw ValidationError("--peer-ip is required.")
        }
    }

    mutating func run() async throws {
        let signer = try PersistentEnclaveKey.loadOrCreate()

        if rank == 0 {
            try await runRank0(signer: signer)
        } else {
            try await runRank1(signer: signer)
        }
    }

    // MARK: - Rank 0

    private func runRank0(signer: PersistentEnclaveKey) async throws {
        let config = ClusterSessionConfig(peerIP: peerIP, port: port)
        let session = ClusterSession(config: config, signer: signer)

        print("Connecting to rank 1 at \(peerIP):\(port)…")
        Task { await session.start() }

        // Wait up to 60s for the session to become ready.
        for _ in 0 ..< 60 {
            let h = await session.health
            if case .ready = h { break }
            try await Task.sleep(for: .seconds(1))
        }

        let health = await session.health
        guard case .ready = health else {
            print("ERROR: Cluster session did not become ready (health: \(health)).")
            throw ExitCode.failure
        }
        if let status = await session.peerStatus {
            print("Rank 1 status — model loaded: \(status.modelLoaded), memory: \(status.memoryPressure.rawValue)")
        }
        print("Cluster session ready. Rank 0 is serving.")
        print("(Integrate EncryptedPipelineEngine with the coordinator request queue to route inference.)")

        // Keep the session alive.
        while true {
            try? await Task.sleep(for: .seconds(3600))
        }
    }

    // MARK: - Rank 1

    private func runRank1(signer: PersistentEnclaveKey) async throws {
        let peer = ClusterPeer(port: port, signer: signer, peerIP: peerIP)
        print("Rank 1 listening on port \(port) (peer IP for pinning: \(peerIP))…")

        // Serve with a static model state and a no-op inference handler.
        // Replace the inferenceHandler with EncryptedPipelineServer.makeInferenceHandler()
        // once a model is loaded.
        try await peer.serve(
            modelState: {
                PongPayload(modelLoaded: false, inferenceInFlight: false, memoryPressure: .normal)
            },
            inferenceHandler: { conn, _, _ in
                // No model loaded — send sessionEnd to signal rank 0 to retry later.
                let endFrame = ClusterFrame.encode(type: .sessionEnd)
                try? await conn.send(endFrame)
            }
        )
    }
}
