import Foundation

/// The content inventories compiled into the runtime: one generated document
/// per registered model that has been inventoried. Nothing sends them, and the
/// worker build hash the two ranks already compare covers them.
enum QwenRegisteredContentInventory {
    /// The canonical document, or nil for a model nobody has inventoried.
    static func document(_ model: QwenRegisteredDenseModel) -> String? {
        switch model {
        case .qwen35NineB: QwenRegistered9BContentInventory.document
        case .qwen38TwentySevenB: nil
        }
    }

    /// A registered model's inventory, checked every time it is taken: the
    /// document's hash is the specification's pin, and without file, offset
    /// and content it is the layout inventory the specification already pins.
    static func admit(_ specification: QwenDenseRegisteredSpecification) throws -> LayerStageTensorContentInventory? {
        try admit(document: document(specification.model), pin: specification.contentInventorySHA256,
                  layoutInventorySHA256: specification.inventorySHA256)
    }

    static func admit(document: String?, pin: String?,
                      layoutInventorySHA256: String) throws -> LayerStageTensorContentInventory? {
        guard let document, let pin else {
            guard document == nil, pin == nil else {
                throw ProbeError("Registered content inventory needs both its document and its pin")
            }
            return nil
        }
        let data = Data(document.utf8)
        guard sha256(data) == pin else {
            throw ProbeError("Registered content inventory differs from its pinned SHA-256")
        }
        let inventory = try LayerStageTensorContentInventory.decode(data)
        guard inventory.layoutInventorySHA256 == layoutInventorySHA256 else {
            throw ProbeError("Registered content inventory differs from the pinned layout inventory")
        }
        return inventory
    }

    /// The generated source file that embeds a document. A canonical document
    /// has no character a multi-line string literal would need escaped.
    static func swiftSource(model: QwenRegisteredDenseModel, document: Data) throws -> String {
        let inventory = try LayerStageTensorContentInventory.decode(document)
        let name: (type: String, artifact: String)
        switch model {
        case .qwen35NineB: name = ("QwenRegistered9BContentInventory", "Qwen3.5 9B")
        case .qwen38TwentySevenB: name = ("QwenRegistered27BContentInventory", "Qwen3.8 27B")
        }
        let lines = String(decoding: document, as: UTF8.self).split(separator: "\n").map { "    " + $0 + "\n" }
        return """
            // Generated by `darkbloom-cluster-stage-check content-inventory` from the
            // verified registered \(name.artifact) artifact. Do not edit.
            //
            // The canonical per-tensor content inventory: \(inventory.records.count) tensors, \(inventory.payloadBytes) bytes.
            // `QwenDenseRegisteredSpecification.contentInventorySHA256` pins its SHA-256,
            // \(inventory.encodedSHA256).
            enum \(name.type) {
                static let document = \"\"\"

            """ + lines.joined() + "\n    \"\"\"\n}\n"
    }
}
