#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
REHEARSAL="$ROOT/scripts/rehearse-coordinator-rollback.sh"
DEPLOY_PROD="$ROOT/deploy/gcp/deploy-prod.sh"

bash -n "$REHEARSAL"
bash -n "$DEPLOY_PROD"

if DATABASE_URL="postgresql://writer@prod.example/prod" \
  "$REHEARSAL" \
    --candidate-image local/candidate \
    --fallback-image local/fallback \
    --output /tmp/forbidden-cutover-report.json \
    > /dev/null 2>&1; then
  echo "rollback rehearsal accepted a runtime write credential" >&2
  exit 1
fi

if EIGENINFERENCE_DATABASE_URL="postgresql://writer@prod.example/prod" \
  "$REHEARSAL" \
    --candidate-image local/candidate \
    --fallback-image local/fallback \
    --output /tmp/forbidden-cutover-report.json \
    > /dev/null 2>&1; then
  echo "rollback rehearsal accepted the coordinator database credential" >&2
  exit 1
fi

if ! rg -q -- "--pull never" "$REHEARSAL"; then
  echo "rollback rehearsal can pull unreviewed images" >&2
  exit 1
fi

if rg -q 'wget|gcloud|aws |kubectl' "$REHEARSAL"; then
  echo "rollback rehearsal contains an external or mutating control-plane command" >&2
  exit 1
fi

if rg -o 'https?://[^" ]+' "$REHEARSAL" | rg -v 'http://127\.0\.0\.1' >/dev/null; then
  echo "rollback rehearsal curl is not restricted to loopback" >&2
  exit 1
fi

# shellcheck disable=SC2016 # These are literal source markers, not shell expressions.
for lifecycle_marker in \
  'run_coordinator "$fallback"' \
  'run_coordinator "$candidate"' \
  'entrypoint=/usr/local/bin/coordinator-rs' \
  'docker kill --signal KILL' \
  'rollback-check' \
  'replacement_replay_ack_historical_terminal_and_v2_to_v1_are_fenced'; do
  rg -Fq "$lifecycle_marker" "$REHEARSAL" || {
    echo "rollback rehearsal omits lifecycle marker: $lifecycle_marker" >&2
    exit 1
  }
done

first_gcloud_line=$(rg -n '^[[:space:]]*[^#]*gcloud ' "$DEPLOY_PROD" | cut -d: -f1 | sed -n '1p')
remote_line=$(rg -n 'gcloud_ssh "\$remote_command"' "$DEPLOY_PROD" | cut -d: -f1)
mapfile -t authorization_rechecks < <(
  rg -n '^[[:space:]]*verify_full_cutover_authorization \|\|' "$DEPLOY_PROD" |
    cut -d: -f1
)
[[ "${#authorization_rechecks[@]}" -eq 2 &&
  "${authorization_rechecks[0]}" -lt "$first_gcloud_line" &&
  "${authorization_rechecks[1]}" -lt "$remote_line" ]] || {
  echo "production deploy does not verify authorization before remote mutation" >&2
  exit 1
}
for binding in \
  'expected_gate' \
  'expected_environment' \
  'candidate_image' \
  'fallback_image' \
  'assessment_sha256' \
  'approval_sha256'; do
  rg -Fq "$binding" "$ROOT/scripts/cutover_readiness/gates.py" || {
    echo "deployment authorization omits binding: $binding" >&2
    exit 1
  }
done

if rg -n 'collect-live|deploy-prod\.sh|remote-deploy\.sh|gcloud compute|aws rds' \
  "$ROOT/.github/workflows/cutover-readiness.yml" \
  "$ROOT/.github/workflows/pilot-load.yml" >/dev/null; then
  echo "scheduled cutover workflow contains a production read or write path" >&2
  exit 1
fi
if rg -q -- '--public-key-output' "$ROOT/.github/workflows/cutover-readiness.yml"; then
  echo "scheduled evidence trusts a key generated by the report itself" >&2
  exit 1
fi
if rg -q 'rust-coordinator-fault-evidence|fault-matrix\.pub\.pem|import-fault' \
  "$ROOT/.github/workflows/ci.yml"; then
  echo "ordinary CI publishes self-trusted output as cutover evidence" >&2
  exit 1
fi
for pilot_marker in \
  'scripts/pilot-load.py component' \
  'CUTOVER_EVIDENCE_PUBLIC_KEY_PEM' \
  'scripts/cutover-readiness.py import-pilot' \
  'component-scheduled/load.json'; do
  rg -Fq "$pilot_marker" "$ROOT/.github/workflows/pilot-load.yml" || {
    echo "pilot workflow omits signed cutover evidence marker: $pilot_marker" >&2
    exit 1
  }
done

# shellcheck disable=SC2016 # These are literal workflow source markers.
for workflow in \
  "$ROOT/.github/workflows/cutover-readiness.yml" \
  "$ROOT/.github/workflows/pilot-load.yml"; do
  for protection_marker in \
    'environment: cutover-evidence-signer' \
    "github.repository == 'Layr-Labs/d-inference'" \
    "github.ref == format('refs/heads/{0}', github.event.repository.default_branch)" \
    'test "$GITHUB_REF_PROTECTED" = true' \
    'test "$GITHUB_WORKFLOW_SHA" = "$GITHUB_SHA"' \
    'needs.' \
    "result == 'success'" \
    'id-token: none' \
    'id-token: write' \
    'actions/attest@a1948c3f048ba23858d222213b7c278aabede763' \
    'cosign sign-blob --yes' \
    'gh attestation verify'; do
    rg -Fq "$protection_marker" "$workflow" || {
      echo "$(basename "$workflow") omits protection marker: $protection_marker" >&2
      exit 1
    }
  done
  attest_line=$(rg -n 'actions/attest@' "$workflow" | cut -d: -f1 | sed -n '1p')
  hash_line=$(rg -n 'Verify artifact hashes and unsigned canonical envelopes' "$workflow" |
    cut -d: -f1 | sed -n '1p')
  [[ -n "$attest_line" && -n "$hash_line" && "$hash_line" -lt "$attest_line" ]] || {
    echo "$(basename "$workflow") attests before verifying producer hashes" >&2
    exit 1
  }
  signer_block=$(sed -n '/^  sign-evidence:/,$p' "$workflow")
  if rg -q 'actions/checkout@|scripts/' <<<"$signer_block"; then
    echo "$(basename "$workflow") signer executes repository code" >&2
    exit 1
  fi
done

if rg -q 'CUTOVER_EVIDENCE_SIGNING_KEY_PEM|secrets\.' \
  "$ROOT/.github/workflows/cutover-readiness.yml" \
  "$ROOT/.github/workflows/pilot-load.yml"; then
  echo "fault/load workflows expose a long-lived secret to test code" >&2
  exit 1
fi

rollback_workflow="$ROOT/.github/workflows/cutover-readiness.yml"
if rg -q 'docker build' "$rollback_workflow"; then
  echo "rollback workflow builds an unauthorized placeholder image" >&2
  exit 1
fi
# shellcheck disable=SC2016 # These are literal workflow source markers.
for target_marker in \
  'CUTOVER_ENVIRONMENT_MANIFEST_JSON' \
  '.payload.environment_binding.descriptor.candidate_image' \
  '.payload.environment_binding.descriptor.fallback_image' \
  'docker pull "$candidate"' \
  'docker pull "$fallback"'; do
  rg -Fq "$target_marker" "$rollback_workflow" || {
    echo "rollback workflow omits target authorization marker: $target_marker" >&2
    exit 1
  }
done

for retirement_marker in \
  'go_db_mutation_writes' \
  'go_background_writes' \
  'go_financial_writes' \
  'go_ownership_epochs' \
  'go_sessions' \
  'go_audit_coverage_complete' \
  'go_audit_trigger_states_valid' \
  'go_audit_definition_hashes_valid' \
  'go_audit_owner_coverage_complete' \
  'database_system_identifier'; do
  rg -Fq "$retirement_marker" "$ROOT/deploy/cutover/rds-readonly.sql" || {
    echo "RDS retirement proof omits: $retirement_marker" >&2
    exit 1
  }
done
if rg -q 'go_mutation_traffic_90d|!method:GET' \
  "$ROOT/deploy/cutover/datadog-queries.json"; then
  echo "retirement still relies on HTTP proxy mutation traffic" >&2
  exit 1
fi

for query_file in \
  "$ROOT/deploy/cutover/datadog-queries.json" \
  "$ROOT/deploy/cutover/datadog-queries-canary.json"; do
  if [[ "$(rg -o '\.rollup\([^)]*,900\)' "$query_file" | wc -l)" -lt 9 ]]; then
    echo "$(basename "$query_file") does not pin every query to 900-second rollups" >&2
    exit 1
  fi
done

for runtime_marker in \
  'EIGENINFERENCE_IMAGE_DIGEST' \
  'com.darkbloom.image-digest' \
  '.image_digest == $digest'; do
  rg -Fq "$runtime_marker" \
    "$ROOT/deploy/gcp/run-coordinator.sh" \
    "$ROOT/deploy/gcp/remote-deploy.sh" || {
    echo "runtime image corroboration omits: $runtime_marker" >&2
    exit 1
  }
done

env -u GITHUB_ACTIONS python3 -m unittest \
  scripts.tests.test_cutover_readiness \
  scripts.tests.test_fault_matrix

