package postgres

import (
	"context"
	"encoding/json"
	"fmt"
	"time"

	"github.com/eigeninference/d-inference/coordinator/store"
	"github.com/eigeninference/d-inference/coordinator/store/postgres/storedb"
)

// The api_keys queries are generated by sqlc from queries/api_keys.sql
// (make sqlc-generate).

func (s *PostgresStore) queries() *storedb.Queries { return storedb.New(s.pool) }

// apiKeyFromRow converts one api_keys row into a store.APIKey.
func apiKeyFromRow(row storedb.ApiKey) *store.APIKey {
	return &store.APIKey{
		ID:             row.ID,
		OwnerAccountID: row.OwnerAccountID,
		Name:           row.Name,
		Label:          row.RawPrefix,
		KeyHash:        row.KeyHash,
		Disabled:       !row.Active,
		LimitMicroUSD:  row.LimitMicroUsd,
		LimitReset:     store.NormalizeResetWindow(row.LimitReset),
		RPMLimit:       row.RpmLimit,
		ITPMLimit:      row.ItpmLimit,
		OTPMLimit:      row.OtpmLimit,
		AllowedModels:  decodeModelList(row.AllowedModels),
		ExpiresAt:      row.ExpiresAt,
		CreatedAt:      row.CreatedAt,
		LastUsedAt:     row.LastUsedAt,
		SelfRouteOnly:  row.SelfRouteOnly,
	}
}

// insertAPIKeyParams maps a fully-formed key record to its insert columns.
func insertAPIKeyParams(rec *store.APIKey) storedb.InsertAPIKeyParams {
	return storedb.InsertAPIKeyParams{
		ID:             rec.ID,
		KeyHash:        rec.KeyHash,
		RawPrefix:      rec.Label,
		OwnerAccountID: rec.OwnerAccountID,
		Name:           rec.Name,
		Active:         !rec.Disabled,
		LimitMicroUsd:  rec.LimitMicroUSD,
		LimitReset:     store.NormalizeResetWindow(rec.LimitReset),
		RpmLimit:       rec.RPMLimit,
		ItpmLimit:      rec.ITPMLimit,
		OtpmLimit:      rec.OTPMLimit,
		AllowedModels:  encodeModelList(rec.AllowedModels),
		ExpiresAt:      rec.ExpiresAt,
		CreatedAt:      rec.CreatedAt,
		SelfRouteOnly:  rec.SelfRouteOnly,
	}
}

// encodeModelList serializes a model allow-list for storage. Empty → "".
func encodeModelList(models []string) string {
	if len(models) == 0 {
		return ""
	}
	b, err := json.Marshal(models)
	if err != nil {
		return ""
	}
	return string(b)
}

// decodeModelList parses a stored model allow-list. "" / invalid → nil.
func decodeModelList(s string) []string {
	if s == "" || s == "[]" {
		return nil
	}
	var out []string
	if err := json.Unmarshal([]byte(s), &out); err != nil {
		return nil
	}
	if len(out) == 0 {
		return nil
	}
	return out
}

// CreateKeyForAccount generates a new API key linked to a specific account.
func (s *PostgresStore) CreateKeyForAccount(accountID string) (string, error) {
	raw, _, err := s.CreateAPIKey(accountID, store.APIKeyCreate{})
	return raw, err
}

// CreateAPIKey mints a new API key with optional per-key limits.
func (s *PostgresStore) CreateAPIKey(accountID string, opts store.APIKeyCreate) (string, *store.APIKey, error) {
	raw, err := store.GenerateRawKey()
	if err != nil {
		return "", nil, fmt.Errorf("store: generate key: %w", err)
	}
	id, err := store.GenerateKeyID()
	if err != nil {
		return "", nil, fmt.Errorf("store: generate key id: %w", err)
	}
	rec := &store.APIKey{
		ID:             id,
		OwnerAccountID: accountID,
		Name:           opts.Name,
		Label:          store.KeyLabel(raw),
		KeyHash:        store.HashKey(raw),
		LimitMicroUSD:  opts.LimitMicroUSD,
		LimitReset:     store.NormalizeResetWindow(opts.LimitReset),
		RPMLimit:       opts.RPMLimit,
		ITPMLimit:      opts.ITPMLimit,
		OTPMLimit:      opts.OTPMLimit,
		AllowedModels:  opts.AllowedModels,
		SelfRouteOnly:  opts.SelfRouteOnly,
		ExpiresAt:      opts.ExpiresAt,
		CreatedAt:      time.Now().UTC(),
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := s.queries().InsertAPIKey(ctx, insertAPIKeyParams(rec)); err != nil {
		return "", nil, fmt.Errorf("store: insert key: %w", err)
	}
	return raw, rec, nil
}

// SeedKey inserts a specific raw key into the database. This is used for
// bootstrapping the admin key. If the key already exists, it is a no-op.
func (s *PostgresStore) SeedKey(rawKey string) error {
	id, err := store.GenerateKeyID()
	if err != nil {
		return fmt.Errorf("store: generate key id: %w", err)
	}
	rec := &store.APIKey{
		ID:         id,
		Name:       "admin",
		Label:      store.KeyLabel(rawKey),
		KeyHash:    store.HashKey(rawKey),
		LimitReset: store.KeyResetNone,
		CreatedAt:  time.Now().UTC(),
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := s.queries().InsertAPIKeyIfAbsent(ctx, storedb.InsertAPIKeyIfAbsentParams(insertAPIKeyParams(rec))); err != nil {
		return fmt.Errorf("store: seed key: %w", err)
	}
	return nil
}

// GetKeyAccount returns the account ID that owns this key, or "" if unlinked.
func (s *PostgresStore) GetKeyAccount(key string) string {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	accountID, err := s.queries().GetActiveKeyAccount(ctx, store.HashKey(key))
	if err != nil {
		return ""
	}
	return accountID
}

// AuthenticateKey resolves a raw key to its active record for request auth.
func (s *PostgresStore) AuthenticateKey(rawKey string) (*store.APIKey, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	row, err := s.queries().GetAPIKeyByHash(ctx, store.HashKey(rawKey))
	if err != nil {
		return nil, err
	}
	k := apiKeyFromRow(row)
	if k.Disabled {
		return nil, fmt.Errorf("key disabled")
	}
	if k.ExpiresAt != nil && time.Now().After(*k.ExpiresAt) {
		return nil, fmt.Errorf("key expired")
	}
	return k, nil
}

// ListAPIKeys returns all keys owned by an account, newest first.
func (s *PostgresStore) ListAPIKeys(accountID string) ([]store.APIKey, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	rows, err := s.queries().ListAPIKeysByOwner(ctx, accountID)
	if err != nil {
		return nil, err
	}
	out := make([]store.APIKey, 0, len(rows))
	for _, row := range rows {
		out = append(out, *apiKeyFromRow(row))
	}
	return out, nil
}

// GetAPIKeyByID returns a single key by ID, scoped to the owner.
func (s *PostgresStore) GetAPIKeyByID(accountID, id string) (*store.APIKey, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	row, err := s.queries().GetAPIKeyByID(ctx, storedb.GetAPIKeyByIDParams{ID: id, OwnerAccountID: accountID})
	if err != nil {
		return nil, err
	}
	return apiKeyFromRow(row), nil
}

// UpdateAPIKey overwrites mutable fields of a key, scoped to the owner.
func (s *PostgresStore) UpdateAPIKey(accountID, id string, mutable store.APIKey) (*store.APIKey, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	updated, err := s.queries().UpdateAPIKey(ctx, storedb.UpdateAPIKeyParams{
		Name:           mutable.Name,
		Active:         !mutable.Disabled,
		LimitMicroUsd:  mutable.LimitMicroUSD,
		LimitReset:     store.NormalizeResetWindow(mutable.LimitReset),
		RpmLimit:       mutable.RPMLimit,
		ItpmLimit:      mutable.ITPMLimit,
		OtpmLimit:      mutable.OTPMLimit,
		AllowedModels:  encodeModelList(mutable.AllowedModels),
		ExpiresAt:      mutable.ExpiresAt,
		SelfRouteOnly:  mutable.SelfRouteOnly,
		ID:             id,
		OwnerAccountID: accountID,
	})
	if err != nil {
		return nil, err
	}
	if updated == 0 {
		return nil, fmt.Errorf("key not found")
	}
	return s.GetAPIKeyByID(accountID, id)
}

// RevokeAPIKeyByID permanently deletes a key by ID, scoped to the owner.
func (s *PostgresStore) RevokeAPIKeyByID(accountID, id string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	deleted, err := s.queries().DeleteAPIKeyByID(ctx, storedb.DeleteAPIKeyByIDParams{ID: id, OwnerAccountID: accountID})
	if err != nil {
		return err
	}
	if deleted == 0 {
		return fmt.Errorf("key not found")
	}
	return nil
}

// RotateAPIKey atomically replaces a key within a transaction (see Store
// interface). The old key is deleted and the new key inserted in the same tx;
// a concurrent rotate of the same id finds the row gone and returns not-found.
func (s *PostgresStore) RotateAPIKey(accountID, id string) (string, *store.APIKey, error) {
	raw, err := store.GenerateRawKey()
	if err != nil {
		return "", nil, fmt.Errorf("store: generate key: %w", err)
	}
	newID, err := store.GenerateKeyID()
	if err != nil {
		return "", nil, fmt.Errorf("store: generate key id: %w", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return "", nil, fmt.Errorf("store: begin rotate tx: %w", err)
	}
	defer tx.Rollback(ctx)
	q := storedb.New(tx)

	oldRow, err := q.GetAPIKeyByIDForUpdate(ctx, storedb.GetAPIKeyByIDForUpdateParams{ID: id, OwnerAccountID: accountID})
	if err != nil {
		return "", nil, fmt.Errorf("key not found")
	}
	old := apiKeyFromRow(oldRow)

	rec := &store.APIKey{
		ID:             newID,
		OwnerAccountID: accountID,
		Name:           old.Name,
		Label:          store.KeyLabel(raw),
		KeyHash:        store.HashKey(raw),
		Disabled:       old.Disabled,
		LimitMicroUSD:  old.LimitMicroUSD,
		LimitReset:     store.NormalizeResetWindow(old.LimitReset),
		RPMLimit:       old.RPMLimit,
		ITPMLimit:      old.ITPMLimit,
		OTPMLimit:      old.OTPMLimit,
		AllowedModels:  old.AllowedModels,
		SelfRouteOnly:  old.SelfRouteOnly,
		ExpiresAt:      old.ExpiresAt,
		CreatedAt:      time.Now().UTC(),
	}
	if err := q.InsertAPIKey(ctx, insertAPIKeyParams(rec)); err != nil {
		return "", nil, fmt.Errorf("store: insert rotated key: %w", err)
	}
	if _, err := q.DeleteAPIKeyByID(ctx, storedb.DeleteAPIKeyByIDParams{ID: id, OwnerAccountID: accountID}); err != nil {
		return "", nil, fmt.Errorf("store: delete old key: %w", err)
	}
	if err := tx.Commit(ctx); err != nil {
		return "", nil, fmt.Errorf("store: commit rotate: %w", err)
	}
	return raw, rec, nil
}

// TouchAPIKey records that a key was used at the given time.
func (s *PostgresStore) TouchAPIKey(id string, at time.Time) {
	if id == "" {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	lastUsed := at.UTC()
	_ = s.queries().TouchAPIKey(ctx, storedb.TouchAPIKeyParams{LastUsedAt: &lastUsed, ID: id})
}

// KeySpendSince returns total micro-USD charged to a key since `since` (UTC).
func (s *PostgresStore) KeySpendSince(keyID string, since time.Time) int64 {
	if keyID == "" {
		return 0
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	params := storedb.KeySpendSinceParams{KeyID: keyID}
	if !since.IsZero() {
		params.Since = &since
	}
	total, err := s.queries().KeySpendSince(ctx, params)
	if err != nil {
		return 0
	}
	return total
}

// RevokeKey deactivates a key. Returns true if the key existed and was active.
func (s *PostgresStore) RevokeKey(key string) bool {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	deactivated, err := s.queries().DeactivateAPIKeyByHash(ctx, store.HashKey(key))
	if err != nil {
		return false
	}
	return deactivated > 0
}
