{{- if .Values.computeClass.enabled }}
apiVersion: cloud.google.com/v1
kind: ComputeClass
metadata:
  name: {{ .Values.computeClass.name }}
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}
spec:
  whenUnsatisfiable: {{ .Values.computeClass.whenUnsatisfiable }}
  nodePoolAutoCreation:
    enabled: true
  {{- with .Values.computeClass.zones }}
  priorityDefaults:
    location:
      zones:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  priorities:
    {{- toYaml .Values.computeClass.priorities | nindent 4 }}
{{- end }}
