apiVersion: v1
kind: Service
metadata:
  name: {{ include "coordinator.fullname" . }}
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    {{- include "coordinator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      appProtocol: http
    - name: mdm
      port: {{ .Values.service.mdmPort }}
      targetPort: mdm
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coordinator.headlessName" . }}
  labels:
    {{- include "coordinator.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "coordinator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: mdm
      port: {{ .Values.service.mdmPort }}
      targetPort: mdm
      protocol: TCP
