"use client";

import { memo, useMemo } from "react";
import { DEFAULT_DOT_SPACING, MAP_HEIGHT, MAP_WIDTH, dotsToPathData, getLandDots } from "./worldGeometry";

/** Land-dot radius in viewBox units (kept crisp under the meet-scaled SVG). */
const DOT_RADIUS = 1.7;

interface WorldDotMatrixProps {
  className?: string;
  /** SVG aspect handling — "xMidYMid meet" for the square-ish nodes map, "none" to stretch. */
  preserveAspectRatio?: string;
  /** Grid spacing in viewBox units (smaller = denser land field). */
  spacing?: number;
  dotRadius?: number;
  /** Draw the faint meridian/parallel graticule behind the dots. */
  graticule?: boolean;
}

/**
 * Refined dot-matrix world map: a faint graticule plus a field of evenly-spaced
 * dots covering the landmasses, rendered as a single `<path>` for cheap paint.
 *
 * The dot field is generated by pure ray-casting math ({@link getLandDots}) — no
 * canvas or DOM — so it is SSR-safe and produces an identical field on server and
 * client. Colors come from CSS vars (`--map-land-dot`, `--map-graticule`) so it
 * reads correctly in light and dark. Decorative only: `pointer-events: none` lets
 * zoom/pan drags and marker hovers pass straight through.
 */
export const WorldDotMatrix = memo(function WorldDotMatrix({
  className,
  preserveAspectRatio = "xMidYMid meet",
  spacing = DEFAULT_DOT_SPACING,
  dotRadius = DOT_RADIUS,
  graticule = true,
}: WorldDotMatrixProps) {
  const dotPath = useMemo(() => dotsToPathData(getLandDots(spacing), dotRadius), [spacing, dotRadius]);

  return (
    <svg
      className={className}
      viewBox={`0 0 ${MAP_WIDTH} ${MAP_HEIGHT}`}
      preserveAspectRatio={preserveAspectRatio}
      aria-hidden="true"
      style={{ pointerEvents: "none" }}
    >
      {graticule && (
        <g stroke="var(--map-graticule)" strokeWidth="1" vectorEffect="non-scaling-stroke">
          {[125, 250, 375].map((y) => (
            <line key={`lat-${y}`} x1="36" x2="964" y1={y} y2={y} />
          ))}
          {[200, 400, 600, 800].map((x) => (
            <line key={`lon-${x}`} x1={x} x2={x} y1="40" y2="460" />
          ))}
        </g>
      )}
      <path d={dotPath} fill="var(--map-land-dot)" />
    </svg>
  );
});
