SELECT json_build_object('kind','freshness','observed_at',clock_timestamp(),'replica_replay_at',pg_last_xact_replay_timestamp(),'latest_fleet_snapshot',(SELECT sampled_at FROM fleet_snapshots ORDER BY sampled_at DESC LIMIT 1),'latest_route',(SELECT created_at FROM inference_routes ORDER BY created_at DESC LIMIT 1));
WITH anchor AS (SELECT sampled_at AS at FROM fleet_snapshots ORDER BY sampled_at DESC LIMIT 1), latest AS (
 SELECT DISTINCT ON (f.provider_id, f.model) f.* FROM fleet_snapshots f, anchor a WHERE f.sampled_at>a.at-interval '2 minutes' AND f.provider_id<>'coordinator' ORDER BY f.provider_id,f.model,f.sampled_at DESC
) SELECT json_build_object('kind','fleet_by_gate','model',model,'eligibility_reason',eligibility_reason,'rows',count(*),'devices',count(DISTINCT provider_id),'idle_rows',count(*) FILTER(WHERE num_running=0 AND num_waiting=0),'pending_requests',sum(pending_count),'breaker_rows',count(*) FILTER(WHERE breaker_open),'ejected_rows',count(*) FILTER(WHERE ejected),'oldest_sample',min(sampled_at),'newest_sample',max(sampled_at)) FROM latest GROUP BY model,eligibility_reason ORDER BY count(*) DESC;
WITH recent AS (SELECT DISTINCT serial_number FROM providers WHERE serial_number<>'' AND last_seen>pg_last_xact_replay_timestamp()-interval '30 minutes'), paired AS (
 SELECT old.id AS oldest_id, fresh.id AS latest_id, old.last_seen AS oldest_seen, fresh.last_seen AS latest_seen FROM recent d
 CROSS JOIN LATERAL (SELECT id,last_seen FROM providers WHERE serial_number=d.serial_number ORDER BY last_seen ASC,id ASC LIMIT 1) old
 CROSS JOIN LATERAL (SELECT id,last_seen FROM providers WHERE serial_number=d.serial_number ORDER BY last_seen DESC,id DESC LIMIT 1) fresh
) SELECT json_build_object('kind','session_history','recent_serial_devices',count(*),'different_oldest_latest_session',count(*) FILTER(WHERE oldest_id<>latest_id),'oldest_rep_missing',count(*) FILTER(WHERE o.provider_id IS NULL),'latest_rep_missing',count(*) FILTER(WHERE n.provider_id IS NULL),'latest_jobs_lower_than_oldest',count(*) FILTER(WHERE n.total_jobs<o.total_jobs),'latest_jobs_greater_than_oldest',count(*) FILTER(WHERE n.total_jobs>o.total_jobs),'oldest_session_min',min(oldest_seen),'latest_session_max',max(latest_seen)) FROM paired p LEFT JOIN provider_reputation o ON o.provider_id=p.oldest_id LEFT JOIN provider_reputation n ON n.provider_id=p.latest_id;
