#!/bin/bash
# Canonical provider installer. coordinator/api/install.sh is generated byte-for-byte
# by scripts/sync-install-embed.sh and embedded in the coordinator binary.
set -euo pipefail

# Darkbloom Provider Installer (Swift CLI release v0.5.0+)
# Usage: curl -fsSL https://api.darkbloom.dev/install.sh | bash
#
# This script:
#   1. Fetches the latest signed release from the coordinator
#   2. Downloads Darkbloom.app (SwiftUI DarkbloomApp main executable PLUS the
#      co-bundled provider CLI, enclave helper, metallib, SwiftPM resources)
#      and installs it at the stable managed-update path
#      ~/.darkbloom/Darkbloom.app
#   3. Verifies bundle SHA-256 + Apple Developer ID code signature
#   4. Sets up the Secure Enclave identity
#   5. Optionally enrolls in MDM (device attestation)
#   6. Optionally downloads a starter model
#   7. Offers to launch the app (interactive terminals only)
#
# Zero prerequisites — just macOS 14+ on Apple Silicon. The Swift CLI
# links mlx-swift directly and ships a colocated mlx.metallib for Metal
# kernels; there is no Python interpreter to install and no inference
# subprocess to spawn.

# This source intentionally retains the placeholder used by the coordinator.
# End users fetch /install.sh from a coordinator, which substitutes its own base
# URL. Direct source execution must set COORD_URL explicitly.
COORD_URL="${COORD_URL:-__DARKBLOOM_COORD_URL__}"
INSTALL_DIR="$HOME/.darkbloom"
BIN_DIR="$INSTALL_DIR/bin"
DARKBLOOM_DESIGNATED_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.provider" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
DARKBLOOM_FAN_HELPER_REQUIREMENT='anchor apple generic and identifier "io.darkbloom.fan-helper" and certificate leaf[subject.OU] = "SLDQ2GJ6TL"'
FAN_HELPER_REQUIREMENT="$DARKBLOOM_FAN_HELPER_REQUIREMENT"
INSTALL_TEST_MODE=0

fail_install() {
    echo "  ✗ $*" >&2
    return 1
}

verify_file_hash() {
    local file=$1
    local expected=$2
    local label=$3
    [ -z "$expected" ] && return 0
    local actual
    actual=$(shasum -a 256 "$file" | cut -d' ' -f1)
    [ "$actual" = "$expected" ] \
        || fail_install "$label hash mismatch (expected $expected, got $actual)."
}

verify_code_requirement() {
    local target=$1
    local deep=$2
    local requirement=$3
    if [ "$deep" = "1" ]; then
        codesign --verify --deep --strict --verbose=2 \
            "-R=$requirement" "$target" >/dev/null 2>&1
    else
        codesign --verify --strict --verbose=2 \
            "-R=$requirement" "$target" >/dev/null 2>&1
    fi
}

verify_staged_app_signature() {
    local app=$1
    local requirement=${2:-$DARKBLOOM_DESIGNATED_REQUIREMENT}
    verify_code_requirement "$app" 1 "$requirement" || {
        fail_install "Staged Darkbloom.app does not satisfy the pinned signature requirement."
        return 1
    }
}

# Stock-macOS binary capability probe. `strings` is an Xcode CLT shim on a
# pristine Mac (it prompts/fails without developer tools), so scan the file
# directly with BSD grep's binary-as-text mode — grep ships in base macOS.
binary_contains_paged_code() {
    local binary=$1
    LC_ALL=C grep -a -q -F 'engine_v2_kv_backend' "$binary"
}

verify_fan_helper_capability() {
    local app=$1
    local executable="$app/Contents/MacOS/darkbloom"
    local marker="$app/Contents/Resources/darkbloom-runtime-capabilities/fan-helper-v1"
    local helper="$app/Contents/Helpers/darkbloom-fan-helper"
    local code_present=0
    local marker_present=0
    local helper_present=0

    LC_ALL=C grep -a -q -F 'darkbloom-fan-helper-v1' "$executable" \
        && code_present=1
    if [ -e "$marker" ] || [ -L "$marker" ]; then marker_present=1; fi
    if [ -e "$helper" ] || [ -L "$helper" ]; then helper_present=1; fi
    [ "$code_present" -eq "$marker_present" ] \
        && [ "$marker_present" -eq "$helper_present" ] || {
        fail_install "Fan-helper CLI capability, marker, and nested helper must be present together."
        return 1
    }
    [ "$marker_present" -eq 1 ] || return 0

    [ -f "$marker" ] && [ ! -L "$marker" ] \
        && [ "$(tr -d '[:space:]' < "$marker")" = "1" ] || {
        fail_install "Fan-helper capability marker is invalid."
        return 1
    }
    [ -f "$helper" ] && [ ! -L "$helper" ] && [ -x "$helper" ] || {
        fail_install "Bundled fan helper must be a regular executable, not a symlink."
        return 1
    }
    [ "$(stat -f '%Lp' "$helper" 2>/dev/null || true)" = "755" ] || {
        fail_install "Bundled fan helper must have mode 0755."
        return 1
    }
    verify_code_requirement "$helper" 0 "$FAN_HELPER_REQUIREMENT" || {
        fail_install "Bundled fan helper does not satisfy the pinned helper signature requirement."
        return 1
    }
}

verify_staged_app() {
    local app=$1
    local executable="$app/Contents/MacOS/darkbloom"
    local marker="$app/Contents/Resources/darkbloom-runtime-capabilities/paged-kernel-v1"

    if [ "$INSTALL_TEST_MODE" = "1" ]; then
        codesign --verify --deep --strict --verbose=2 "$app" >/dev/null 2>&1 || {
            fail_install "Strict code-signature verification failed for staged Darkbloom.app."
            return 1
        }
    else
        verify_staged_app_signature "$app" || return 1
    fi
    verify_fan_helper_capability "$app" || return 1

    local code_has_paged=0
    local marker_present=0
    binary_contains_paged_code "$executable" && code_has_paged=1
    [ -f "$marker" ] && marker_present=1
    [ "$code_has_paged" -eq "$marker_present" ] || {
        if [ "$code_has_paged" -eq 1 ]; then
            fail_install "Paged-capable staged app is missing its signed capability marker."
        else
            fail_install "Staged app advertises paged capability without paged runtime code."
        fi
        return 1
    }
    [ "$marker_present" -eq 1 ] || return 0
    [ "$(tr -d '[:space:]' < "$marker")" = "1" ] || {
        fail_install "Paged runtime capability marker is invalid."
        return 1
    }

    shopt -s nullglob
    local paged_resources=(
        "$app/Contents/Resources"/*.bundle/pagedattention.metal
    )
    local expected_resource="$app/Contents/Resources/mlx-swift-lm_MLXLMCommon.bundle/pagedattention.metal"
    [ "${#paged_resources[@]}" -eq 1 ] \
        && [ "${paged_resources[0]}" = "$expected_resource" ] \
        && [ -s "$expected_resource" ] \
        || {
            fail_install "Paged-capable staged app requires exactly one sealed MLXLMCommon pagedattention.metal."
            return 1
        }

    DARKBLOOM_NO_UPDATE_CHECK=1 \
        DARKBLOOM_GEMMA4_PREFILL_CHUNK_EVAL=18 \
        MLX_GEMMA4_FUSED_WEIGHTED_UNSORT=1 \
        MLX_GATHER_QMM_EXPERT_SLICES=1 \
        "$executable" runtime-smoke >/dev/null \
        || {
            fail_install "Packaged paged-kernel runtime smoke failed."
            return 1
        }
}

verify_staged_app_payload() {
    local app=$1
    local binary_hash=$2
    local metallib_hash=$3
    local app_bin="$app/Contents/MacOS"
    [ -n "$binary_hash" ] && [ -n "$metallib_hash" ] || {
        fail_install "App releases require binary_hash and metallib_hash."
        return 1
    }
    verify_file_hash "$app_bin/darkbloom" "$binary_hash" "App binary" \
        && verify_file_hash "$app_bin/mlx.metallib" "$metallib_hash" "App metallib"
}

# ~/.darkbloom/Darkbloom.app ownership: release bundles have always carried
# OUR id (io.darkbloom.provider — first the CLI wrapper, now the combined
# app); dev loops via script/build_and_run.sh produce the unsigned dev build
# (dev.darkbloom.app). Both are replaced in place. Anything else at that path
# is NOT ours (user-copied app, other tooling, corrupt bundle without an
# Info.plist): preserve it beside the install dir and warn, never clobber it.
existing_bundle_is_ours() {
    local app=$1
    local id
    [ -d "$app" ] && [ ! -L "$app" ] || return 1
    id=$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' \
        "$app/Contents/Info.plist" 2>/dev/null || true)
    case "$id" in
        io.darkbloom.provider|dev.darkbloom.app) return 0 ;;
        *) return 1 ;;
    esac
}

foreign_bundle_destination() {
    local install_dir=$1
    local base
    base="$install_dir/Darkbloom.app.foreign-$(date +%Y%m%d-%H%M%S)"
    local preserved=$base
    local suffix=1
    while [ -e "$preserved" ] || [ -L "$preserved" ]; do
        preserved="${base}-${suffix}"
        suffix=$((suffix + 1))
    done
    printf '%s\n' "$preserved"
}

install_test_fault() {
    local point=$1
    [ "$INSTALL_TEST_MODE" = "1" ] \
        && [ "${DARKBLOOM_INSTALL_TEST_FAIL_POINT:-}" = "$point" ]
}

install_path_exists() {
    [ -e "$1" ] || [ -L "$1" ]
}

restore_backed_up_links() {
    local backup_bin=$1
    local bin_dir=$2
    local name
    local failed=0
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        if install_path_exists "$backup_bin/$name"; then
            if ! rm -rf "$bin_dir/$name" 2>/dev/null; then
                failed=1
                continue
            fi
            mv "$backup_bin/$name" "$bin_dir/$name" 2>/dev/null || failed=1
        fi
    done
    return "$failed"
}

backup_managed_links() {
    local backup_bin=$1
    local bin_dir=$2
    local name
    mkdir -p "$backup_bin" || return 1
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        if install_path_exists "$bin_dir/$name"; then
            if ! mv "$bin_dir/$name" "$backup_bin/$name"; then
                restore_backed_up_links "$backup_bin" "$bin_dir" || true
                return 1
            fi
        fi
    done
}

restore_managed_links() {
    local backup_bin=$1
    local bin_dir=$2
    local name
    local failed=0
    for name in darkbloom darkbloom-enclave mlx.metallib eigeninference-enclave; do
        rm -rf "$bin_dir/$name" 2>/dev/null || failed=1
    done
    restore_backed_up_links "$backup_bin" "$bin_dir" || failed=1
    return "$failed"
}

rollback_staged_app_commit() {
    local destination=$1
    local previous_app=$2
    local had_previous=$3
    local backup_bin=$4
    local bin_dir=$5
    local links_touched=$6
    local failed=0

    if [ "$links_touched" -eq 1 ]; then
        restore_managed_links "$backup_bin" "$bin_dir" || failed=1
    fi
    rm -rf "$destination" 2>/dev/null || failed=1
    if [ "$had_previous" -eq 1 ] && ! install_path_exists "$destination"; then
        mv "$previous_app" "$destination" 2>/dev/null || failed=1
    fi
    rmdir "$backup_bin" 2>/dev/null || true
    rmdir "${backup_bin%/bin}" 2>/dev/null || true
    return "$failed"
}

create_managed_link() {
    local target=$1
    local link=$2
    local fault_point=$3
    install_test_fault "$fault_point" && return 1
    ln -s "$target" "$link"
}

ensure_user_app_shortcut() {
    local managed_app=$1
    local shortcut=$2
    local shortcut_dir=${shortcut%/*}
    local managed_resolved
    local shortcut_resolved

    [ -d "$managed_app" ] && [ ! -L "$managed_app" ] || return 0
    mkdir -p "$shortcut_dir" || {
        echo "  ⚠ Could not create $shortcut_dir; launch the managed app directly."
        return 1
    }

    if [ -e "$shortcut" ] || [ -L "$shortcut" ]; then
        if [ -L "$shortcut" ]; then
            managed_resolved=$(cd -P "$managed_app" 2>/dev/null && pwd -P || true)
            shortcut_resolved=$(cd -P "$shortcut" 2>/dev/null && pwd -P || true)
            if [ -n "$managed_resolved" ] \
                && [ "$shortcut_resolved" = "$managed_resolved" ]
            then
                return 0
            fi
        fi
        echo "  ⚠ Preserving existing $shortcut; open $managed_app directly."
        return 0
    fi

    if ! ln -s "$managed_app" "$shortcut"; then
        if [ -e "$shortcut" ] || [ -L "$shortcut" ]; then
            echo "  ⚠ Preserving $shortcut, which appeared while installing."
            return 0
        fi
        echo "  ⚠ Could not create the user Applications shortcut at $shortcut."
        return 1
    fi
}

commit_staged_app() {
    local staged_app=$1
    local install_dir=$2
    local backup="$install_dir/.install-backup-$$-$RANDOM"
    local destination="$install_dir/Darkbloom.app"
    local bin_dir="$install_dir/bin"
    local previous_app="$backup/Darkbloom.app"
    local had_previous=0
    local previous_was_foreign=0
    local links_touched=0
    mkdir -p "$backup" "$bin_dir" || {
        rm -rf "$backup"
        return 1
    }

    if install_path_exists "$destination"; then
        existing_bundle_is_ours "$destination" || previous_was_foreign=1
        if ! mv "$destination" "$previous_app"; then
            rm -rf "$backup"
            return 1
        fi
        had_previous=1
    fi
    if install_test_fault "staged-app-move" \
        || ! mv "$staged_app" "$destination"
    then
        rollback_staged_app_commit \
            "$destination" "$previous_app" "$had_previous" \
            "$backup/bin" "$bin_dir" "$links_touched" || true
        return 1
    fi

    if ! backup_managed_links "$backup/bin" "$bin_dir"; then
        rollback_staged_app_commit \
            "$destination" "$previous_app" "$had_previous" \
            "$backup/bin" "$bin_dir" "$links_touched" || true
        return 1
    fi
    links_touched=1

    local app_bin="$destination/Contents/MacOS"
    if ! create_managed_link \
        "../Darkbloom.app/Contents/MacOS/darkbloom" \
        "$bin_dir/darkbloom" "link-darkbloom" \
        || ! create_managed_link \
            "../Darkbloom.app/Contents/MacOS/darkbloom-enclave" \
            "$bin_dir/darkbloom-enclave" "link-darkbloom-enclave" \
        || ! create_managed_link \
            "../Darkbloom.app/Contents/MacOS/mlx.metallib" \
            "$bin_dir/mlx.metallib" "link-metallib" \
        || ! create_managed_link \
            "darkbloom-enclave" \
            "$bin_dir/eigeninference-enclave" "link-legacy-enclave"
    then
        rollback_staged_app_commit \
            "$destination" "$previous_app" "$had_previous" \
            "$backup/bin" "$bin_dir" "$links_touched" || true
        return 1
    fi
    if install_test_fault "app-chmod" \
        || ! chmod +x "$app_bin/darkbloom" "$app_bin/darkbloom-enclave"
    then
        rollback_staged_app_commit \
            "$destination" "$previous_app" "$had_previous" \
            "$backup/bin" "$bin_dir" "$links_touched" || true
        return 1
    fi

    if [ "$previous_was_foreign" -eq 1 ]; then
        local preserved
        preserved=$(foreign_bundle_destination "$install_dir")
        if ! mv "$previous_app" "$preserved"; then
            rollback_staged_app_commit \
                "$destination" "$previous_app" "$had_previous" \
                "$backup/bin" "$bin_dir" "$links_touched" || true
            return 1
        fi
        echo "  ⚠ $destination is not a Darkbloom build — preserving it at:"
        echo "      $preserved"
    fi

    # No rollback path is needed past this point: the app, every managed link,
    # executable modes, and any permanent foreign-bundle preservation have all
    # committed successfully.
    rm -rf "$backup" || {
        echo "  ⚠ Installed successfully, but could not remove transaction backup $backup." >&2
    }
}

commit_staged_flat_bundle() {
    local staged_bin=$1
    local install_dir=$2
    local backup="$install_dir/.install-backup-$$-$RANDOM"
    local destination="$install_dir/bin"
    mkdir -p "$backup"
    if [ -d "$destination" ]; then
        mv "$destination" "$backup/bin" || {
            rm -rf "$backup"
            return 1
        }
    fi
    if ! mv "$staged_bin" "$destination"; then
        [ -d "$backup/bin" ] && mv "$backup/bin" "$destination" 2>/dev/null || true
        rm -rf "$backup"
        return 1
    fi
    chmod +x "$destination/darkbloom" "$destination/darkbloom-enclave"
    ln -sfn "darkbloom-enclave" "$destination/eigeninference-enclave"
    rm -rf "$backup"
}

install_bundle_atomically() {
    local archive=$1
    local install_dir=$2
    local binary_hash=${3:-}
    local metallib_hash=${4:-}
    local stage="$install_dir/.install-staging-$$-$RANDOM"
    rm -rf "$stage"
    mkdir -p "$stage"
    if ! tar xzf "$archive" -C "$stage"; then
        rm -rf "$stage"
        return 1
    fi

    local flat_bin="$stage/bin"
    [ -f "$flat_bin/darkbloom" ] \
        && [ -f "$flat_bin/darkbloom-enclave" ] \
        && [ -f "$flat_bin/mlx.metallib" ] \
        || {
            rm -rf "$stage"
            fail_install "Release bundle is missing required flat verifier files."
            return 1
        }
    verify_file_hash "$flat_bin/darkbloom" "$binary_hash" "Binary" || {
        rm -rf "$stage"
        return 1
    }
    verify_file_hash "$flat_bin/mlx.metallib" "$metallib_hash" "Metallib" || {
        rm -rf "$stage"
        return 1
    }

    if [ -d "$stage/Darkbloom.app" ]; then
        verify_staged_app_payload \
            "$stage/Darkbloom.app" "$binary_hash" "$metallib_hash" || {
            rm -rf "$stage"
            return 1
        }
        verify_staged_app "$stage/Darkbloom.app" || {
            rm -rf "$stage"
            return 1
        }
        commit_staged_app "$stage/Darkbloom.app" "$install_dir" || {
            rm -rf "$stage"
            fail_install "Atomic app swap failed; previous install was restored."
            return 1
        }
    else
        if [ "$INSTALL_TEST_MODE" = "1" ]; then
            codesign --verify --strict --verbose=2 "$flat_bin/darkbloom" >/dev/null 2>&1 || {
                rm -rf "$stage"
                fail_install "Strict signature verification failed for legacy flat artifact."
                return 1
            }
        else
            verify_code_requirement \
                "$flat_bin/darkbloom" 0 "$DARKBLOOM_DESIGNATED_REQUIREMENT" || {
                rm -rf "$stage"
                fail_install "Legacy flat artifact does not satisfy the pinned signature requirement."
                return 1
            }
        fi
        commit_staged_flat_bundle "$flat_bin" "$install_dir" || {
            rm -rf "$stage"
            fail_install "Atomic flat-bundle swap failed; previous install was restored."
            return 1
        }
    fi
    rm -rf "$stage"
}

if [ "${1:-}" = "--verify-staged-app-signature-test" ]; then
    [ "$#" -eq 3 ] || {
        echo "usage: $0 --verify-staged-app-signature-test <app> <requirement>" >&2
        exit 64
    }
    verify_staged_app_signature "$2" "$3"
    exit $?
fi

if [ "${1:-}" = "--ensure-user-app-shortcut-test" ]; then
    [ "$#" -eq 3 ] || {
        echo "usage: $0 --ensure-user-app-shortcut-test <managed-app> <shortcut>" >&2
        exit 64
    }
    ensure_user_app_shortcut "$2" "$3"
    exit $?
fi

if [ "${1:-}" = "--install-bundle-test" ]; then
    { [ "$#" -eq 5 ] || [ "$#" -eq 6 ]; } || {
        echo "usage: $0 --install-bundle-test <archive> <install-dir> <binary-hash> <metallib-hash> [fan-helper-requirement]" >&2
        exit 64
    }
    INSTALL_TEST_MODE=1
    if [ "$#" -eq 6 ]; then FAN_HELPER_REQUIREMENT=$6; fi
    install_bundle_atomically "$2" "$3" "$4" "$5"
    exit $?
fi

# Detect interactive vs piped (curl | bash).
if [ -t 0 ]; then
    INTERACTIVE=true
else
    INTERACTIVE=false
fi

echo "╔══════════════════════════════════════════════╗"
echo "║  Darkbloom — Private AI on Verified Macs     ║"
echo "╚══════════════════════════════════════════════╝"
echo ""

# ─── Pre-flight checks ───────────────────────────────────────
if [ "$(uname)" != "Darwin" ]; then
    echo "Error: Darkbloom requires macOS with Apple Silicon."
    exit 1
fi
if [ "$(uname -m)" != "arm64" ]; then
    echo "Error: Darkbloom requires Apple Silicon (arm64)."
    exit 1
fi

CHIP=$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo "Apple Silicon")
MEM=$(sysctl -n hw.memsize 2>/dev/null | awk '{printf "%.0f", $1/1073741824}')
SERIAL=$(ioreg -c IOPlatformExpertDevice -d 2 | awk -F'"' '/IOPlatformSerialNumber/{print $4}')
MACOS=$(sw_vers -productVersion 2>/dev/null || echo "?")
echo "  $CHIP · ${MEM}GB · macOS $MACOS"
echo ""

# ─── Step 1: Fetch latest release ────────────────────────────
echo "→ [1/5] Fetching latest release from $COORD_URL ..."

RELEASE_JSON=$(curl -fsSL "$COORD_URL/v1/releases/latest" 2>/dev/null || echo "")
if [ -z "$RELEASE_JSON" ]; then
    echo "  ✗ Could not reach coordinator at $COORD_URL"
    echo "    Check your internet connection and try again."
    exit 1
fi

# Extract JSON string fields with sed — no python3 needed (no Xcode CLT prompt).
json_val() { echo "$1" | sed -n "s/.*\"$2\":\"\([^\"]*\)\".*/\1/p"; }
BUNDLE_URL=$(json_val "$RELEASE_JSON" url)
BUNDLE_HASH=$(json_val "$RELEASE_JSON" bundle_hash)
BINARY_HASH=$(json_val "$RELEASE_JSON" binary_hash)
METALLIB_HASH=$(json_val "$RELEASE_JSON" metallib_hash)
VERSION=$(json_val "$RELEASE_JSON" version)
BACKEND=$(json_val "$RELEASE_JSON" backend)

if [ -z "$BUNDLE_URL" ] || [ -z "$BUNDLE_HASH" ] || [ -z "$VERSION" ]; then
    echo "  ✗ Coordinator response missing required fields (url / bundle_hash / version)."
    echo "    Raw response: $RELEASE_JSON"
    exit 1
fi

echo "  Version: $VERSION"
echo "  Backend: ${BACKEND:-mlx-swift}"
echo "  Signed by: Developer ID Application: Eigen Labs, Inc."
echo ""

# ─── Step 2: Download + verify bundle ────────────────────────
echo "→ [2/5] Downloading Darkbloom v${VERSION}..."
mkdir -p "$INSTALL_DIR" "$BIN_DIR"

TARBALL="/tmp/darkbloom-bundle.tar.gz"
curl -f#L "$BUNDLE_URL" -o "$TARBALL"

ACTUAL_HASH=$(shasum -a 256 "$TARBALL" | cut -d' ' -f1)
if [ "$ACTUAL_HASH" != "$BUNDLE_HASH" ]; then
    echo ""
    echo "  ✗ Bundle hash mismatch — refusing to install possibly-tampered binary."
    echo "    Expected: $BUNDLE_HASH"
    echo "    Got:      $ACTUAL_HASH"
    rm -f "$TARBALL"
    exit 1
fi
echo "  Bundle hash verified ✓"

echo "  Staging and verifying the complete app before touching the live install ..."
if ! install_bundle_atomically "$TARBALL" "$INSTALL_DIR" "$BINARY_HASH" "$METALLIB_HASH"; then
    rm -f "$TARBALL"
    echo "  Existing installation was left unchanged."
    exit 1
fi
rm -f "$TARBALL"
echo "  Strict signature, runtime resources, and atomic swap verified ✓"

ensure_user_app_shortcut \
    "$INSTALL_DIR/Darkbloom.app" \
    "$HOME/Applications/Darkbloom.app" || true

# Make available in PATH. Try /usr/local/bin symlink, fall back to shell rc.
if ln -sf "$BIN_DIR/darkbloom" /usr/local/bin/darkbloom 2>/dev/null; then
    :
fi
RC="$HOME/.zshrc"
if [ -f "$HOME/.bashrc" ] && [ ! -f "$HOME/.zshrc" ]; then
    RC="$HOME/.bashrc"
fi
if ! grep -q "\.darkbloom/bin" "$RC" 2>/dev/null; then
    sed -i '' '/\.dginf\/bin/d; /\.eigeninference\/bin/d; /alias eigeninf/d; /alias dginf/d; /# EigenInference/d; /# Darkbloom$/d' "$RC" 2>/dev/null || true
    cat >> "$RC" << 'SHELL'

# Darkbloom
export PATH="$HOME/.darkbloom/bin:$PATH"
SHELL
fi
export PATH="$BIN_DIR:$PATH"

# Source rc so commands work in this shell. Disable -eu around it: rc files
# may use unbound vars or shell-specific builtins that fail under bash strict.
set +eu
# The selected user rc path is intentionally dynamic.
# shellcheck disable=SC1090
source "$RC" 2>/dev/null || true
set -eu

echo "  Binaries installed ✓"
echo "  Shortcut: darkbloom"

# ─── Migrate from old installs ───────────────────────────────
# Migration chain: ~/.dginf → ~/.eigeninference → ~/.darkbloom
for OLD_DIR in "$HOME/.dginf" "$HOME/.eigeninference"; do
    if [ -d "$OLD_DIR" ] && [ ! -L "$OLD_DIR" ]; then
        echo ""
        echo "  Migrating from $OLD_DIR..."
        for f in enclave_key.data wallet_key auth_token; do
            [ -f "$OLD_DIR/$f" ] && cp -n "$OLD_DIR/$f" "$INSTALL_DIR/$f" 2>/dev/null || true
        done
        # Symlink old path so stragglers still work, then drop the old python/
        # subtree -- the Swift release no longer needs it.
        ln -sfn "$INSTALL_DIR" "$OLD_DIR" 2>/dev/null || true
        echo "  Migration complete ✓"
    fi
done

# ─── Step 3: Secure Enclave identity ─────────────────────────
echo ""
echo "→ [3/5] Provisioning Secure Enclave identity..."
if "$BIN_DIR/darkbloom-enclave" info >/dev/null 2>&1; then
    echo "  Secure Enclave ✓ (P-256 key generated)"
else
    echo "  Secure Enclave ⚠ (not available on this hardware; provider will run with reduced trust)"
fi

# ─── Step 4: Enrollment + device attestation ─────────────────
echo ""
echo "→ [4/5] Enrollment + device attestation..."

ALREADY_ENROLLED=false
if profiles status -type enrollment 2>&1 | grep -q "MDM enrollment: Yes"; then
    ALREADY_ENROLLED=true
fi

if [ "$ALREADY_ENROLLED" = true ]; then
    echo "  Already enrolled ✓"
elif [ -n "$SERIAL" ]; then
    echo "  Requesting enrollment profile from coordinator..."
    PROFILE_PATH="/tmp/Darkbloom-Enroll-${SERIAL}.mobileconfig"
    rm -f "$PROFILE_PATH" 2>/dev/null
    if curl -fsSL -X POST "$COORD_URL/v1/enroll" \
        -H "Content-Type: application/json" \
        -d "{\"serial_number\": \"$SERIAL\"}" \
        -o "$PROFILE_PATH" 2>/dev/null; then
        echo ""
        echo "  ┌──────────────────────────────────────────────────┐"
        echo "  │ ACTION REQUIRED: Install the enrollment profile  │"
        echo "  │                                                  │"
        echo "  │ This profile lets the coordinator verify:        │"
        echo "  │  • SIP, Secure Boot, system integrity            │"
        echo "  │  • Your Secure Enclave is genuine Apple silicon  │"
        echo "  │  • Device identity signed by Apple's Root CA     │"
        echo "  │                                                  │"
        echo "  │ Darkbloom CANNOT erase, lock, or control         │"
        echo "  │ your Mac. Remove anytime in System Settings.     │"
        echo "  └──────────────────────────────────────────────────┘"
        echo ""
        open "$PROFILE_PATH"
        sleep 1
        open "x-apple.systempreferences:com.apple.Profiles-Settings.extension"

        echo "  System Settings opened — click Install and enter your password."
        if [ "$INTERACTIVE" = true ]; then
            echo ""
            read -r -p "  Press Enter once you have installed the profile..." || true
        else
            echo "  After installing, the provider will verify on first start."
            sleep 3
        fi
        if profiles status -type enrollment 2>&1 | grep -q "MDM enrollment: Yes"; then
            echo "  Enrollment verified ✓"
        else
            echo "  Enrollment pending ⚠ (complete it in System Settings, or run: darkbloom enroll)"
        fi
    else
        echo "  Enrollment ⚠ (coordinator unreachable — enroll later with: darkbloom enroll)"
    fi
else
    echo "  Enrollment ⚠ (could not read serial number — enroll later with: darkbloom enroll)"
fi

# ─── Step 5: Optional starter model ──────────────────────────
echo ""
echo "→ [5/5] Inference model..."

CATALOG_JSON=$(curl -fsSL "$COORD_URL/v1/models/catalog?type=text" 2>/dev/null || echo "")

if [ -n "$CATALOG_JSON" ]; then
    if [ "$INTERACTIVE" = true ]; then
        echo ""
        echo "  Available text models:"
        echo "$CATALOG_JSON" \
          | tr ',' '\n' \
          | sed -n 's/.*"id":"\([^"]*\)".*"display_name":"\([^"]*\)".*"size_gb":\([0-9.]*\).*"min_ram_gb":\([0-9]*\).*/  • \2  ~\3 GB  (≥\4 GB RAM)  [\1]/p' \
          | head -20
        echo ""
        echo "  Download a model with:"
        echo "    darkbloom models download <id>"
    else
        echo "  Run interactively to pick a starter model:"
        echo "    curl -fsSL $COORD_URL/install.sh | bash -s"
        echo "  Or list the catalog with:  darkbloom models catalog"
    fi
else
    echo "  Could not fetch model catalog (continuing anyway)."
fi

# ─── Done ────────────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║  Install complete                            ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
# Only releases that ship the SwiftUI payload can be launched; downlevel
# flat/CLI-wrapper bundles simply skip this step.
APP_MAIN="$INSTALL_DIR/Darkbloom.app/Contents/MacOS/DarkbloomApp"
if [ -x "$APP_MAIN" ]; then
    echo "  Next step: open Darkbloom and follow the guided setup."
    echo "  App location: ~/.darkbloom/Darkbloom.app"
    echo ""
    if [ "$INTERACTIVE" = true ]; then
        REPLY=""
        read -r -p "  Launch the Darkbloom app now? [Y/n] " REPLY || REPLY="n"
        case "$REPLY" in
            n|N|no|NO|No|nO)
                echo "  Skipped. Launch later with: open ~/.darkbloom/Darkbloom.app"
                ;;
            *)
                /usr/bin/open "$INSTALL_DIR/Darkbloom.app" \
                    && echo "  Darkbloom.app launched ✓" \
                    || echo "  ⚠ Could not launch the app; try: open ~/.darkbloom/Darkbloom.app"
                ;;
        esac
    else
        echo "  Desktop app: open ~/.darkbloom/Darkbloom.app"
    fi
    echo ""
    echo "  Advanced CLI (optional):"
else
    echo "  Next steps:"
fi
echo "    darkbloom doctor             # verify the system is ready"
echo "    darkbloom models catalog     # browse available models"
echo "    darkbloom models download <id>"
echo "    darkbloom login              # link this Mac to your account"
echo "    darkbloom start              # serve inference (interactive picker)"
echo ""
