// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"time"
)

type ApiKey struct {
	KeyHash        string
	RawPrefix      string
	OwnerAccountID string
	CreatedAt      time.Time
	Active         bool
	ID             string
	Name           string
	LimitMicroUsd  *int64
	LimitReset     string
	RpmLimit       *int64
	ItpmLimit      *int64
	OtpmLimit      *int64
	AllowedModels  string
	ExpiresAt      *time.Time
	LastUsedAt     *time.Time
	SelfRouteOnly  bool
	DeletedAt      *time.Time
}

type ErasureOutbox struct {
	ID         string
	RequestID  string
	Target     string
	ExternalID string
	State      string
	Attempts   int32
	NextAt     time.Time
	LeaseUntil *time.Time
	LastError  string
	DoneAt     *time.Time
	CreatedAt  time.Time
}

type ErasureRequest struct {
	ID               string
	AccountID        string
	Actor            string
	CanceledBy       string
	Reason           string
	State            string
	Plan             []byte
	ConfirmTokenHash string
	ConfirmExpiresAt *time.Time
	WalletAddresses  []string
	RequestedAt      *time.Time
	ScrubAfter       *time.Time
	ErasedAt         *time.Time
	CanceledAt       *time.Time
	LeaseUntil       *time.Time
	LastError        string
	CreatedAt        time.Time
}
