// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package storedb

import (
	"time"
)

type ApiKey struct {
	KeyHash        string
	RawPrefix      string
	OwnerAccountID string
	CreatedAt      time.Time
	Active         bool
	ID             string
	Name           string
	LimitMicroUsd  *int64
	LimitReset     string
	RpmLimit       *int64
	ItpmLimit      *int64
	OtpmLimit      *int64
	AllowedModels  string
	ExpiresAt      *time.Time
	LastUsedAt     *time.Time
	SelfRouteOnly  bool
	DeletedAt      *time.Time
}
