// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package storedb

import (
	"context"
	"time"
)

const deactivateAPIKeyByHash = `-- name: DeactivateAPIKeyByHash :execrows
UPDATE api_keys SET active = FALSE WHERE key_hash = $1 AND active = TRUE
`

func (q *Queries) DeactivateAPIKeyByHash(ctx context.Context, keyHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateAPIKeyByHash, keyHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAPIKeyByID = `-- name: DeleteAPIKeyByID :execrows
DELETE FROM api_keys WHERE id = $1 AND owner_account_id = $2
`

type DeleteAPIKeyByIDParams struct {
	ID             string
	OwnerAccountID string
}

func (q *Queries) DeleteAPIKeyByID(ctx context.Context, arg DeleteAPIKeyByIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKeyByID, arg.ID, arg.OwnerAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT key_hash, raw_prefix, owner_account_id, created_at, active, id, name, limit_micro_usd, limit_reset, rpm_limit, itpm_limit, otpm_limit, allowed_models, expires_at, last_used_at, self_route_only FROM api_keys WHERE key_hash = $1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.KeyHash,
		&i.RawPrefix,
		&i.OwnerAccountID,
		&i.CreatedAt,
		&i.Active,
		&i.ID,
		&i.Name,
		&i.LimitMicroUsd,
		&i.LimitReset,
		&i.RpmLimit,
		&i.ItpmLimit,
		&i.OtpmLimit,
		&i.AllowedModels,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.SelfRouteOnly,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT key_hash, raw_prefix, owner_account_id, created_at, active, id, name, limit_micro_usd, limit_reset, rpm_limit, itpm_limit, otpm_limit, allowed_models, expires_at, last_used_at, self_route_only FROM api_keys WHERE id = $1 AND owner_account_id = $2
`

type GetAPIKeyByIDParams struct {
	ID             string
	OwnerAccountID string
}

func (q *Queries) GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, arg.ID, arg.OwnerAccountID)
	var i ApiKey
	err := row.Scan(
		&i.KeyHash,
		&i.RawPrefix,
		&i.OwnerAccountID,
		&i.CreatedAt,
		&i.Active,
		&i.ID,
		&i.Name,
		&i.LimitMicroUsd,
		&i.LimitReset,
		&i.RpmLimit,
		&i.ItpmLimit,
		&i.OtpmLimit,
		&i.AllowedModels,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.SelfRouteOnly,
	)
	return i, err
}

const getAPIKeyByIDForUpdate = `-- name: GetAPIKeyByIDForUpdate :one
SELECT key_hash, raw_prefix, owner_account_id, created_at, active, id, name, limit_micro_usd, limit_reset, rpm_limit, itpm_limit, otpm_limit, allowed_models, expires_at, last_used_at, self_route_only FROM api_keys WHERE id = $1 AND owner_account_id = $2 FOR UPDATE
`

type GetAPIKeyByIDForUpdateParams struct {
	ID             string
	OwnerAccountID string
}

func (q *Queries) GetAPIKeyByIDForUpdate(ctx context.Context, arg GetAPIKeyByIDForUpdateParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByIDForUpdate, arg.ID, arg.OwnerAccountID)
	var i ApiKey
	err := row.Scan(
		&i.KeyHash,
		&i.RawPrefix,
		&i.OwnerAccountID,
		&i.CreatedAt,
		&i.Active,
		&i.ID,
		&i.Name,
		&i.LimitMicroUsd,
		&i.LimitReset,
		&i.RpmLimit,
		&i.ItpmLimit,
		&i.OtpmLimit,
		&i.AllowedModels,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.SelfRouteOnly,
	)
	return i, err
}

const getActiveKeyAccount = `-- name: GetActiveKeyAccount :one
SELECT owner_account_id FROM api_keys WHERE key_hash = $1 AND active = TRUE
`

func (q *Queries) GetActiveKeyAccount(ctx context.Context, keyHash string) (string, error) {
	row := q.db.QueryRow(ctx, getActiveKeyAccount, keyHash)
	var owner_account_id string
	err := row.Scan(&owner_account_id)
	return owner_account_id, err
}

const insertAPIKey = `-- name: InsertAPIKey :exec
INSERT INTO api_keys
	(id, key_hash, raw_prefix, owner_account_id, name, active,
	 limit_micro_usd, limit_reset, rpm_limit, itpm_limit, otpm_limit,
	 allowed_models, expires_at, created_at, self_route_only)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
`

type InsertAPIKeyParams struct {
	ID             string
	KeyHash        string
	RawPrefix      string
	OwnerAccountID string
	Name           string
	Active         bool
	LimitMicroUsd  *int64
	LimitReset     string
	RpmLimit       *int64
	ItpmLimit      *int64
	OtpmLimit      *int64
	AllowedModels  string
	ExpiresAt      *time.Time
	CreatedAt      time.Time
	SelfRouteOnly  bool
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) error {
	_, err := q.db.Exec(ctx, insertAPIKey,
		arg.ID,
		arg.KeyHash,
		arg.RawPrefix,
		arg.OwnerAccountID,
		arg.Name,
		arg.Active,
		arg.LimitMicroUsd,
		arg.LimitReset,
		arg.RpmLimit,
		arg.ItpmLimit,
		arg.OtpmLimit,
		arg.AllowedModels,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.SelfRouteOnly,
	)
	return err
}

const insertAPIKeyIfAbsent = `-- name: InsertAPIKeyIfAbsent :exec
INSERT INTO api_keys
	(id, key_hash, raw_prefix, owner_account_id, name, active,
	 limit_micro_usd, limit_reset, rpm_limit, itpm_limit, otpm_limit,
	 allowed_models, expires_at, created_at, self_route_only)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
ON CONFLICT (key_hash) DO NOTHING
`

type InsertAPIKeyIfAbsentParams struct {
	ID             string
	KeyHash        string
	RawPrefix      string
	OwnerAccountID string
	Name           string
	Active         bool
	LimitMicroUsd  *int64
	LimitReset     string
	RpmLimit       *int64
	ItpmLimit      *int64
	OtpmLimit      *int64
	AllowedModels  string
	ExpiresAt      *time.Time
	CreatedAt      time.Time
	SelfRouteOnly  bool
}

func (q *Queries) InsertAPIKeyIfAbsent(ctx context.Context, arg InsertAPIKeyIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertAPIKeyIfAbsent,
		arg.ID,
		arg.KeyHash,
		arg.RawPrefix,
		arg.OwnerAccountID,
		arg.Name,
		arg.Active,
		arg.LimitMicroUsd,
		arg.LimitReset,
		arg.RpmLimit,
		arg.ItpmLimit,
		arg.OtpmLimit,
		arg.AllowedModels,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.SelfRouteOnly,
	)
	return err
}

const keySpendSince = `-- name: KeySpendSince :one
SELECT COALESCE(SUM(cost_micro_usd), 0)::bigint AS total_micro_usd FROM usage
WHERE key_id = $1
  AND ($2::timestamptz IS NULL OR created_at >= $2)
`

type KeySpendSinceParams struct {
	KeyID string
	Since *time.Time
}

func (q *Queries) KeySpendSince(ctx context.Context, arg KeySpendSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, keySpendSince, arg.KeyID, arg.Since)
	var total_micro_usd int64
	err := row.Scan(&total_micro_usd)
	return total_micro_usd, err
}

const listAPIKeysByOwner = `-- name: ListAPIKeysByOwner :many
SELECT key_hash, raw_prefix, owner_account_id, created_at, active, id, name, limit_micro_usd, limit_reset, rpm_limit, itpm_limit, otpm_limit, allowed_models, expires_at, last_used_at, self_route_only FROM api_keys WHERE owner_account_id = $1 AND id <> '' ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByOwner(ctx context.Context, ownerAccountID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByOwner, ownerAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.KeyHash,
			&i.RawPrefix,
			&i.OwnerAccountID,
			&i.CreatedAt,
			&i.Active,
			&i.ID,
			&i.Name,
			&i.LimitMicroUsd,
			&i.LimitReset,
			&i.RpmLimit,
			&i.ItpmLimit,
			&i.OtpmLimit,
			&i.AllowedModels,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.SelfRouteOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys SET last_used_at = $1 WHERE id = $2
`

type TouchAPIKeyParams struct {
	LastUsedAt *time.Time
	ID         string
}

func (q *Queries) TouchAPIKey(ctx context.Context, arg TouchAPIKeyParams) error {
	_, err := q.db.Exec(ctx, touchAPIKey, arg.LastUsedAt, arg.ID)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :execrows
UPDATE api_keys SET
	name = $1, active = $2, limit_micro_usd = $3, limit_reset = $4,
	rpm_limit = $5, itpm_limit = $6, otpm_limit = $7,
	allowed_models = $8, expires_at = $9, self_route_only = $10
WHERE id = $11 AND owner_account_id = $12
`

type UpdateAPIKeyParams struct {
	Name           string
	Active         bool
	LimitMicroUsd  *int64
	LimitReset     string
	RpmLimit       *int64
	ItpmLimit      *int64
	OtpmLimit      *int64
	AllowedModels  string
	ExpiresAt      *time.Time
	SelfRouteOnly  bool
	ID             string
	OwnerAccountID string
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAPIKey,
		arg.Name,
		arg.Active,
		arg.LimitMicroUsd,
		arg.LimitReset,
		arg.RpmLimit,
		arg.ItpmLimit,
		arg.OtpmLimit,
		arg.AllowedModels,
		arg.ExpiresAt,
		arg.SelfRouteOnly,
		arg.ID,
		arg.OwnerAccountID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
