// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: erasure.sql

package storedb

import (
	"context"
	"time"
)

const countAPIKeysRows = `-- name: CountAPIKeysRows :one
SELECT COUNT(*) FROM api_keys WHERE owner_account_id = $1
`

func (q *Queries) CountAPIKeysRows(ctx context.Context, ownerAccountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeysRows, ownerAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAccountMachineAliasesRows = `-- name: CountAccountMachineAliasesRows :one
SELECT COUNT(*) FROM darkbloom_machine_aliases WHERE kind IN ('app_attest', 'legacy_se') AND scope = $1
`

func (q *Queries) CountAccountMachineAliasesRows(ctx context.Context, scope string) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountMachineAliasesRows, scope)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAdminNoteLedgerReferences = `-- name: CountAdminNoteLedgerReferences :one
SELECT COUNT(*) FROM ledger_entries
WHERE account_id = $1 AND entry_type IN ('admin_credit', 'admin_reward') AND reference <> entry_type
`

func (q *Queries) CountAdminNoteLedgerReferences(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminNoteLedgerReferences, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppAttestEvidenceBlobsRows = `-- name: CountAppAttestEvidenceBlobsRows :one
SELECT COUNT(*) FROM app_attest_evidence_blobs
WHERE evidence_id IN (SELECT id FROM app_attest_evidence WHERE session_id = ANY($1::text[]))
`

func (q *Queries) CountAppAttestEvidenceBlobsRows(ctx context.Context, sessionIds []string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppAttestEvidenceBlobsRows, sessionIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppAttestEvidenceRows = `-- name: CountAppAttestEvidenceRows :one
SELECT COUNT(*) FROM app_attest_evidence WHERE session_id = ANY($1::text[])
`

func (q *Queries) CountAppAttestEvidenceRows(ctx context.Context, sessionIds []string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppAttestEvidenceRows, sessionIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppAttestReceiptBlobsRows = `-- name: CountAppAttestReceiptBlobsRows :one
SELECT COUNT(*) FROM app_attest_receipt_blobs
WHERE receipt_id IN (SELECT id FROM app_attest_receipts WHERE key_id = ANY($1::text[]))
`

func (q *Queries) CountAppAttestReceiptBlobsRows(ctx context.Context, keyIds []string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppAttestReceiptBlobsRows, keyIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppAttestReceiptJobsRows = `-- name: CountAppAttestReceiptJobsRows :one
SELECT COUNT(*) FROM app_attest_receipt_jobs WHERE key_id = ANY($1::text[])
`

func (q *Queries) CountAppAttestReceiptJobsRows(ctx context.Context, keyIds []string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppAttestReceiptJobsRows, keyIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAppAttestReceiptsRows = `-- name: CountAppAttestReceiptsRows :one
SELECT COUNT(*) FROM app_attest_receipts WHERE key_id = ANY($1::text[])
`

func (q *Queries) CountAppAttestReceiptsRows(ctx context.Context, keyIds []string) (int64, error) {
	row := q.db.QueryRow(ctx, countAppAttestReceiptsRows, keyIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBillingSessionsRows = `-- name: CountBillingSessionsRows :one
SELECT COUNT(*) FROM billing_sessions WHERE account_id = $1
`

func (q *Queries) CountBillingSessionsRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBillingSessionsRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodeAttestPushBudgetsRows = `-- name: CountCodeAttestPushBudgetsRows :one
SELECT COUNT(*) FROM code_attest_push_budgets WHERE se_pubkey = ANY($1::text[])
`

func (q *Queries) CountCodeAttestPushBudgetsRows(ctx context.Context, seKeys []string) (int64, error) {
	row := q.db.QueryRow(ctx, countCodeAttestPushBudgetsRows, seKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodeAttestationsRows = `-- name: CountCodeAttestationsRows :one
SELECT COUNT(*) FROM code_attestations WHERE se_pubkey = ANY($1::text[])
`

func (q *Queries) CountCodeAttestationsRows(ctx context.Context, seKeys []string) (int64, error) {
	row := q.db.QueryRow(ctx, countCodeAttestationsRows, seKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConsumerRegionRows = `-- name: CountConsumerRegionRows :one
SELECT COUNT(*) FROM inference_routes WHERE consumer_key_hash = $1 AND consumer_region IS NOT NULL
`

func (q *Queries) CountConsumerRegionRows(ctx context.Context, consumerKeyHash string) (int64, error) {
	row := q.db.QueryRow(ctx, countConsumerRegionRows, consumerKeyHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeviceCodesRows = `-- name: CountDeviceCodesRows :one
SELECT COUNT(*) FROM device_codes WHERE account_id = $1
`

func (q *Queries) CountDeviceCodesRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDeviceCodesRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGlobalPayoutRows = `-- name: CountGlobalPayoutRows :one
SELECT COUNT(*) FROM global_payout_withdrawals WHERE account_id = $1
`

func (q *Queries) CountGlobalPayoutRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGlobalPayoutRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGlobalRecipientRow = `-- name: CountGlobalRecipientRow :one
SELECT COUNT(*) FROM global_payout_recipients WHERE account_id = $1
`

func (q *Queries) CountGlobalRecipientRow(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countGlobalRecipientRow, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLegacyMDMCohortRows = `-- name: CountLegacyMDMCohortRows :one
SELECT COUNT(*) FROM legacy_mdm_cohort WHERE account_id = $1
`

func (q *Queries) CountLegacyMDMCohortRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countLegacyMDMCohortRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMDASerialAliasesRows = `-- name: CountMDASerialAliasesRows :one
SELECT COUNT(*) FROM darkbloom_machine_aliases
WHERE kind = 'mda_serial' AND scope = '' AND digest = ANY($1::text[])
`

func (q *Queries) CountMDASerialAliasesRows(ctx context.Context, digests []string) (int64, error) {
	row := q.db.QueryRow(ctx, countMDASerialAliasesRows, digests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenGlobalPayouts = `-- name: CountOpenGlobalPayouts :one
SELECT COUNT(*) FROM global_payout_withdrawals
WHERE account_id = $1 AND (
    status IN ('pending', 'processing')
    OR (status = 'posted' AND submitted_at > $2::timestamptz))
`

type CountOpenGlobalPayoutsParams struct {
	AccountID   string
	PostedAfter time.Time
}

func (q *Queries) CountOpenGlobalPayouts(ctx context.Context, arg CountOpenGlobalPayoutsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenGlobalPayouts, arg.AccountID, arg.PostedAfter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpenStripeWithdrawals = `-- name: CountOpenStripeWithdrawals :one

SELECT COUNT(*) FROM stripe_withdrawals
WHERE account_id = $1 AND (
    status IN ('pending', 'transferred')
    OR (status = 'paid' AND updated_at > $2::timestamptz)
    OR (status = 'failed' AND NOT refunded AND transfer_id = '' AND payout_id = ''
        AND sweep_payout_id = '' AND amount_micro_usd > 0
        AND starts_with(failure_reason, $3::text)))
`

type CountOpenStripeWithdrawalsParams struct {
	AccountID    string
	PaidAfter    time.Time
	RefundPrefix string
}

// Money that is still moving blocks erasure.
func (q *Queries) CountOpenStripeWithdrawals(ctx context.Context, arg CountOpenStripeWithdrawalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenStripeWithdrawals, arg.AccountID, arg.PaidAfter, arg.RefundPrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentConsumerAddress = `-- name: CountPaymentConsumerAddress :one
SELECT COUNT(*) FROM payments WHERE consumer_address = $1
`

func (q *Queries) CountPaymentConsumerAddress(ctx context.Context, consumerAddress string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentConsumerAddress, consumerAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPaymentProviderAddress = `-- name: CountPaymentProviderAddress :one
SELECT COUNT(*) FROM payments WHERE provider_address = $1
`

func (q *Queries) CountPaymentProviderAddress(ctx context.Context, providerAddress string) (int64, error) {
	row := q.db.QueryRow(ctx, countPaymentProviderAddress, providerAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviderLogReportsRows = `-- name: CountProviderLogReportsRows :one
SELECT COUNT(*) FROM provider_log_reports WHERE account_id = $1
`

func (q *Queries) CountProviderLogReportsRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderLogReportsRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviderPayoutAddress = `-- name: CountProviderPayoutAddress :one
SELECT COUNT(*) FROM provider_payouts WHERE provider_address = $1
`

func (q *Queries) CountProviderPayoutAddress(ctx context.Context, providerAddress string) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderPayoutAddress, providerAddress)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviderRegionRows = `-- name: CountProviderRegionRows :one
SELECT COUNT(*) FROM inference_routes
WHERE provider_id = ANY($1::text[]) AND provider_region IS NOT NULL
`

func (q *Queries) CountProviderRegionRows(ctx context.Context, providerIds []string) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderRegionRows, providerIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviderSessionsRows = `-- name: CountProviderSessionsRows :one
SELECT COUNT(*) FROM provider_sessions WHERE account_id = $1
`

func (q *Queries) CountProviderSessionsRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderSessionsRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviderTokensRows = `-- name: CountProviderTokensRows :one
SELECT COUNT(*) FROM provider_tokens WHERE account_id = $1
`

func (q *Queries) CountProviderTokensRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderTokensRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviderTrustReuseRows = `-- name: CountProviderTrustReuseRows :one
SELECT COUNT(*) FROM provider_trust_reuse WHERE se_pubkey = ANY($1::text[])
`

func (q *Queries) CountProviderTrustReuseRows(ctx context.Context, seKeys []string) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderTrustReuseRows, seKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProviderVerificationJobsRows = `-- name: CountProviderVerificationJobsRows :one
SELECT COUNT(*) FROM provider_verification_jobs WHERE se_pubkey = ANY($1::text[])
`

func (q *Queries) CountProviderVerificationJobsRows(ctx context.Context, seKeys []string) (int64, error) {
	row := q.db.QueryRow(ctx, countProviderVerificationJobsRows, seKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProvidersRows = `-- name: CountProvidersRows :one
SELECT COUNT(*) FROM providers WHERE account_id = $1
`

func (q *Queries) CountProvidersRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countProvidersRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferralCodeCopies = `-- name: CountReferralCodeCopies :one
SELECT COUNT(*) FROM billing_sessions WHERE referral_code = $1
`

func (q *Queries) CountReferralCodeCopies(ctx context.Context, referralCode string) (int64, error) {
	row := q.db.QueryRow(ctx, countReferralCodeCopies, referralCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReferrersRow = `-- name: CountReferrersRow :one
SELECT COUNT(*) FROM referrers WHERE account_id = $1
`

func (q *Queries) CountReferrersRow(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countReferrersRow, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSmallModelsInterestRows = `-- name: CountSmallModelsInterestRows :one
SELECT COUNT(*) FROM small_models_interest WHERE account_id = $1
`

func (q *Queries) CountSmallModelsInterestRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSmallModelsInterestRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStripeLedgerReferences = `-- name: CountStripeLedgerReferences :one
SELECT COUNT(*) FROM ledger_entries WHERE account_id = $1 AND reference LIKE 'stripe:%'
`

func (q *Queries) CountStripeLedgerReferences(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countStripeLedgerReferences, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStripeWithdrawalRows = `-- name: CountStripeWithdrawalRows :one
SELECT COUNT(*) FROM stripe_withdrawals WHERE account_id = $1
`

func (q *Queries) CountStripeWithdrawalRows(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countStripeWithdrawalRows, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageLocationRows = `-- name: CountUsageLocationRows :one
SELECT COUNT(*) FROM usage WHERE consumer_key_hash = $1 AND request_location IS NOT NULL
`

func (q *Queries) CountUsageLocationRows(ctx context.Context, consumerKeyHash string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageLocationRows, consumerKeyHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersPendingErasureByPrivyID = `-- name: CountUsersPendingErasureByPrivyID :one
SELECT COUNT(*) FROM users WHERE privy_user_id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) CountUsersPendingErasureByPrivyID(ctx context.Context, privyUserID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersPendingErasureByPrivyID, privyUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersRow = `-- name: CountUsersRow :one

SELECT COUNT(*) FROM users WHERE account_id = $1
`

// Scrub statements, in erasure_rules.go order.
func (q *Queries) CountUsersRow(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersRow, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAccountMachineAliasesRows = `-- name: DeleteAccountMachineAliasesRows :execrows
DELETE FROM darkbloom_machine_aliases WHERE kind IN ('app_attest', 'legacy_se') AND scope = $1
`

func (q *Queries) DeleteAccountMachineAliasesRows(ctx context.Context, scope string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAccountMachineAliasesRows, scope)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAppAttestEvidenceBlobsRows = `-- name: DeleteAppAttestEvidenceBlobsRows :execrows
DELETE FROM app_attest_evidence_blobs
WHERE evidence_id IN (SELECT id FROM app_attest_evidence WHERE session_id = ANY($1::text[]))
`

func (q *Queries) DeleteAppAttestEvidenceBlobsRows(ctx context.Context, sessionIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppAttestEvidenceBlobsRows, sessionIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAppAttestReceiptBlobsRows = `-- name: DeleteAppAttestReceiptBlobsRows :execrows
DELETE FROM app_attest_receipt_blobs
WHERE receipt_id IN (SELECT id FROM app_attest_receipts WHERE key_id = ANY($1::text[]))
`

func (q *Queries) DeleteAppAttestReceiptBlobsRows(ctx context.Context, keyIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppAttestReceiptBlobsRows, keyIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAppAttestReceiptJobsRows = `-- name: DeleteAppAttestReceiptJobsRows :execrows
DELETE FROM app_attest_receipt_jobs WHERE key_id = ANY($1::text[])
`

func (q *Queries) DeleteAppAttestReceiptJobsRows(ctx context.Context, keyIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAppAttestReceiptJobsRows, keyIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCodeAttestPushBudgetsRows = `-- name: DeleteCodeAttestPushBudgetsRows :execrows
DELETE FROM code_attest_push_budgets WHERE se_pubkey = ANY($1::text[])
`

func (q *Queries) DeleteCodeAttestPushBudgetsRows(ctx context.Context, seKeys []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCodeAttestPushBudgetsRows, seKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCodeAttestationsRows = `-- name: DeleteCodeAttestationsRows :execrows
DELETE FROM code_attestations WHERE se_pubkey = ANY($1::text[])
`

func (q *Queries) DeleteCodeAttestationsRows(ctx context.Context, seKeys []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCodeAttestationsRows, seKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDeviceCodesRows = `-- name: DeleteDeviceCodesRows :execrows
DELETE FROM device_codes WHERE account_id = $1
`

func (q *Queries) DeleteDeviceCodesRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceCodesRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLegacyMDMCohortRows = `-- name: DeleteLegacyMDMCohortRows :execrows
DELETE FROM legacy_mdm_cohort WHERE account_id = $1
`

func (q *Queries) DeleteLegacyMDMCohortRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLegacyMDMCohortRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMDASerialAliasesRows = `-- name: DeleteMDASerialAliasesRows :execrows
DELETE FROM darkbloom_machine_aliases
WHERE kind = 'mda_serial' AND scope = '' AND digest = ANY($1::text[])
`

func (q *Queries) DeleteMDASerialAliasesRows(ctx context.Context, digests []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMDASerialAliasesRows, digests)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProviderLogReportsRows = `-- name: DeleteProviderLogReportsRows :execrows
DELETE FROM provider_log_reports WHERE account_id = $1
`

func (q *Queries) DeleteProviderLogReportsRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderLogReportsRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProviderTrustReuseRows = `-- name: DeleteProviderTrustReuseRows :execrows
DELETE FROM provider_trust_reuse WHERE se_pubkey = ANY($1::text[])
`

func (q *Queries) DeleteProviderTrustReuseRows(ctx context.Context, seKeys []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderTrustReuseRows, seKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProviderVerificationJobsRows = `-- name: DeleteProviderVerificationJobsRows :execrows
DELETE FROM provider_verification_jobs WHERE se_pubkey = ANY($1::text[])
`

func (q *Queries) DeleteProviderVerificationJobsRows(ctx context.Context, seKeys []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProviderVerificationJobsRows, seKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSmallModelsInterestRows = `-- name: DeleteSmallModelsInterestRows :execrows
DELETE FROM small_models_interest WHERE account_id = $1
`

func (q *Queries) DeleteSmallModelsInterestRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSmallModelsInterestRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStagedErasureObjects = `-- name: DeleteStagedErasureObjects :exec
DELETE FROM erasure_outbox o USING erasure_requests r
WHERE r.id = o.request_id AND r.account_id = $1 AND r.state <> 'erased'
`

func (q *Queries) DeleteStagedErasureObjects(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, deleteStagedErasureObjects, accountID)
	return err
}

const getBalanceForErasure = `-- name: GetBalanceForErasure :one
SELECT balance_micro_usd, withdrawable_micro_usd FROM balances WHERE account_id = $1
`

type GetBalanceForErasureRow struct {
	BalanceMicroUsd      int64
	WithdrawableMicroUsd int64
}

func (q *Queries) GetBalanceForErasure(ctx context.Context, accountID string) (GetBalanceForErasureRow, error) {
	row := q.db.QueryRow(ctx, getBalanceForErasure, accountID)
	var i GetBalanceForErasureRow
	err := row.Scan(&i.BalanceMicroUsd, &i.WithdrawableMicroUsd)
	return i, err
}

const getErasureRequest = `-- name: GetErasureRequest :one

SELECT id, account_id, actor, canceled_by, reason, state, plan, confirm_token_hash, confirm_expires_at, wallet_hash, wallet_addresses, requested_at, scrub_after, erased_at, canceled_at, lease_until, last_error, created_at FROM erasure_requests WHERE id = $1
`

// Account erasure: requests, outbox, key collection and the scrub statements
// that erasure_rules.go lists. Every scrub statement has a count query with
// the same predicate; the scrub compares the two in one transaction.
func (q *Queries) GetErasureRequest(ctx context.Context, id string) (ErasureRequest, error) {
	row := q.db.QueryRow(ctx, getErasureRequest, id)
	var i ErasureRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Actor,
		&i.CanceledBy,
		&i.Reason,
		&i.State,
		&i.Plan,
		&i.ConfirmTokenHash,
		&i.ConfirmExpiresAt,
		&i.WalletHash,
		&i.WalletAddresses,
		&i.RequestedAt,
		&i.ScrubAfter,
		&i.ErasedAt,
		&i.CanceledAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getErasureRequestForUpdate = `-- name: GetErasureRequestForUpdate :one
SELECT id, account_id, actor, canceled_by, reason, state, plan, confirm_token_hash, confirm_expires_at, wallet_hash, wallet_addresses, requested_at, scrub_after, erased_at, canceled_at, lease_until, last_error, created_at FROM erasure_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetErasureRequestForUpdate(ctx context.Context, id string) (ErasureRequest, error) {
	row := q.db.QueryRow(ctx, getErasureRequestForUpdate, id)
	var i ErasureRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Actor,
		&i.CanceledBy,
		&i.Reason,
		&i.State,
		&i.Plan,
		&i.ConfirmTokenHash,
		&i.ConfirmExpiresAt,
		&i.WalletHash,
		&i.WalletAddresses,
		&i.RequestedAt,
		&i.ScrubAfter,
		&i.ErasedAt,
		&i.CanceledAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getGlobalRecipientDataForErasure = `-- name: GetGlobalRecipientDataForErasure :one
SELECT data FROM global_payout_recipients WHERE account_id = $1
`

func (q *Queries) GetGlobalRecipientDataForErasure(ctx context.Context, accountID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getGlobalRecipientDataForErasure, accountID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getLatestErasureRequest = `-- name: GetLatestErasureRequest :one
SELECT id, account_id, actor, canceled_by, reason, state, plan, confirm_token_hash, confirm_expires_at, wallet_hash, wallet_addresses, requested_at, scrub_after, erased_at, canceled_at, lease_until, last_error, created_at FROM erasure_requests WHERE account_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestErasureRequest(ctx context.Context, accountID string) (ErasureRequest, error) {
	row := q.db.QueryRow(ctx, getLatestErasureRequest, accountID)
	var i ErasureRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Actor,
		&i.CanceledBy,
		&i.Reason,
		&i.State,
		&i.Plan,
		&i.ConfirmTokenHash,
		&i.ConfirmExpiresAt,
		&i.WalletHash,
		&i.WalletAddresses,
		&i.RequestedAt,
		&i.ScrubAfter,
		&i.ErasedAt,
		&i.CanceledAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenErasureRequestForUpdate = `-- name: GetOpenErasureRequestForUpdate :one
SELECT id, account_id, actor, canceled_by, reason, state, plan, confirm_token_hash, confirm_expires_at, wallet_hash, wallet_addresses, requested_at, scrub_after, erased_at, canceled_at, lease_until, last_error, created_at FROM erasure_requests
WHERE account_id = $1 AND state IN ('planned', 'pending')
FOR UPDATE
`

func (q *Queries) GetOpenErasureRequestForUpdate(ctx context.Context, accountID string) (ErasureRequest, error) {
	row := q.db.QueryRow(ctx, getOpenErasureRequestForUpdate, accountID)
	var i ErasureRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Actor,
		&i.CanceledBy,
		&i.Reason,
		&i.State,
		&i.Plan,
		&i.ConfirmTokenHash,
		&i.ConfirmExpiresAt,
		&i.WalletHash,
		&i.WalletAddresses,
		&i.RequestedAt,
		&i.ScrubAfter,
		&i.ErasedAt,
		&i.CanceledAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getReferrerCodeForErasure = `-- name: GetReferrerCodeForErasure :one
SELECT code FROM referrers WHERE account_id = $1
`

func (q *Queries) GetReferrerCodeForErasure(ctx context.Context, accountID string) (string, error) {
	row := q.db.QueryRow(ctx, getReferrerCodeForErasure, accountID)
	var code string
	err := row.Scan(&code)
	return code, err
}

const getUserForErasurePlan = `-- name: GetUserForErasurePlan :one
SELECT account_id, privy_user_id, email, stripe_account_id, deleted_at
FROM users WHERE account_id = $1
`

type GetUserForErasurePlanRow struct {
	AccountID       string
	PrivyUserID     string
	Email           string
	StripeAccountID string
	DeletedAt       *time.Time
}

func (q *Queries) GetUserForErasurePlan(ctx context.Context, accountID string) (GetUserForErasurePlanRow, error) {
	row := q.db.QueryRow(ctx, getUserForErasurePlan, accountID)
	var i GetUserForErasurePlanRow
	err := row.Scan(
		&i.AccountID,
		&i.PrivyUserID,
		&i.Email,
		&i.StripeAccountID,
		&i.DeletedAt,
	)
	return i, err
}

const insertErasureLedgerEntry = `-- name: InsertErasureLedgerEntry :exec
INSERT INTO ledger_entries (account_id, entry_type, amount_micro_usd, balance_after, reference)
VALUES ($1, $2, $3, 0, $4)
`

type InsertErasureLedgerEntryParams struct {
	AccountID      string
	EntryType      string
	AmountMicroUsd int64
	Reference      string
}

func (q *Queries) InsertErasureLedgerEntry(ctx context.Context, arg InsertErasureLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertErasureLedgerEntry,
		arg.AccountID,
		arg.EntryType,
		arg.AmountMicroUsd,
		arg.Reference,
	)
	return err
}

const insertErasureOutbox = `-- name: InsertErasureOutbox :exec
INSERT INTO erasure_outbox (id, request_id, target, external_id, next_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertErasureOutboxParams struct {
	ID         string
	RequestID  string
	Target     string
	ExternalID string
	NextAt     time.Time
}

func (q *Queries) InsertErasureOutbox(ctx context.Context, arg InsertErasureOutboxParams) error {
	_, err := q.db.Exec(ctx, insertErasureOutbox,
		arg.ID,
		arg.RequestID,
		arg.Target,
		arg.ExternalID,
		arg.NextAt,
	)
	return err
}

const insertErasurePlan = `-- name: InsertErasurePlan :exec
INSERT INTO erasure_requests (id, account_id, actor, state, plan, confirm_token_hash, confirm_expires_at, wallet_hash)
VALUES ($1, $2, $3, 'planned', $4, $5, $6, $7)
`

type InsertErasurePlanParams struct {
	ID               string
	AccountID        string
	Actor            string
	Plan             []byte
	ConfirmTokenHash string
	ConfirmExpiresAt *time.Time
	WalletHash       string
}

func (q *Queries) InsertErasurePlan(ctx context.Context, arg InsertErasurePlanParams) error {
	_, err := q.db.Exec(ctx, insertErasurePlan,
		arg.ID,
		arg.AccountID,
		arg.Actor,
		arg.Plan,
		arg.ConfirmTokenHash,
		arg.ConfirmExpiresAt,
		arg.WalletHash,
	)
	return err
}

const insertManualErasureOutbox = `-- name: InsertManualErasureOutbox :exec
INSERT INTO erasure_outbox (id, request_id, target, external_id, state, attempts, next_at, last_error)
VALUES ($1, $2, $3, $4, 'manual_action', 1, $5, $6)
`

type InsertManualErasureOutboxParams struct {
	ID         string
	RequestID  string
	Target     string
	ExternalID string
	NextAt     time.Time
	LastError  string
}

func (q *Queries) InsertManualErasureOutbox(ctx context.Context, arg InsertManualErasureOutboxParams) error {
	_, err := q.db.Exec(ctx, insertManualErasureOutbox,
		arg.ID,
		arg.RequestID,
		arg.Target,
		arg.ExternalID,
		arg.NextAt,
		arg.LastError,
	)
	return err
}

const isAccountErased = `-- name: IsAccountErased :one
SELECT EXISTS (SELECT 1 FROM erasure_requests WHERE account_id = $1 AND state = 'erased')
`

func (q *Queries) IsAccountErased(ctx context.Context, accountID string) (bool, error) {
	row := q.db.QueryRow(ctx, isAccountErased, accountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const leaseDueErasureOutbox = `-- name: LeaseDueErasureOutbox :many

WITH due AS (
    SELECT o.id FROM erasure_outbox o
    JOIN erasure_requests r ON r.id = o.request_id
    WHERE r.state = 'erased' AND o.state = 'pending' AND o.next_at <= $1::timestamptz
      AND (o.lease_until IS NULL OR o.lease_until <= $2::timestamptz)
    ORDER BY o.next_at
    LIMIT $3::int
    FOR UPDATE OF o SKIP LOCKED
), leased AS (
    UPDATE erasure_outbox o SET lease_until = $4::timestamptz,
        lease_generation = o.lease_generation + 1
    FROM due WHERE o.id = due.id
    RETURNING o.id, o.request_id, o.target, o.external_id, o.state, o.attempts, o.next_at, o.lease_until, o.last_error, o.done_at, o.created_at, o.stripe_job_id, o.stripe_job_status, o.stripe_job_status_since, o.stripe_job_generation, o.lease_generation
)
SELECT l.id, l.request_id, l.target, l.external_id, l.state, l.attempts, l.next_at,
       l.last_error, l.stripe_job_id, l.stripe_job_status, l.stripe_job_status_since,
       l.stripe_job_generation, l.lease_generation, l.created_at, r.account_id, r.erased_at
FROM leased l JOIN erasure_requests r ON r.id = l.request_id
`

type LeaseDueErasureOutboxParams struct {
	DueBefore  time.Time
	Now        time.Time
	MaxRows    int32
	LeaseUntil time.Time
}

type LeaseDueErasureOutboxRow struct {
	ID                   string
	RequestID            string
	Target               string
	ExternalID           string
	State                string
	Attempts             int32
	NextAt               time.Time
	LastError            string
	StripeJobID          string
	StripeJobStatus      string
	StripeJobStatusSince *time.Time
	StripeJobGeneration  int32
	LeaseGeneration      int64
	CreatedAt            time.Time
	AccountID            string
	ErasedAt             *time.Time
}

// Outbox delivery.
func (q *Queries) LeaseDueErasureOutbox(ctx context.Context, arg LeaseDueErasureOutboxParams) ([]LeaseDueErasureOutboxRow, error) {
	rows, err := q.db.Query(ctx, leaseDueErasureOutbox,
		arg.DueBefore,
		arg.Now,
		arg.MaxRows,
		arg.LeaseUntil,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaseDueErasureOutboxRow
	for rows.Next() {
		var i LeaseDueErasureOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Target,
			&i.ExternalID,
			&i.State,
			&i.Attempts,
			&i.NextAt,
			&i.LastError,
			&i.StripeJobID,
			&i.StripeJobStatus,
			&i.StripeJobStatusSince,
			&i.StripeJobGeneration,
			&i.LeaseGeneration,
			&i.CreatedAt,
			&i.AccountID,
			&i.ErasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const leaseDueErasureRequests = `-- name: LeaseDueErasureRequests :many
UPDATE erasure_requests SET lease_until = $1::timestamptz
WHERE id IN (
    SELECT r.id FROM erasure_requests r
    WHERE r.state = 'pending' AND r.scrub_after <= $2::timestamptz
      AND (r.lease_until IS NULL OR r.lease_until <= $2::timestamptz)
    ORDER BY r.scrub_after
    LIMIT $3::int
    FOR UPDATE SKIP LOCKED
)
RETURNING id
`

type LeaseDueErasureRequestsParams struct {
	LeaseUntil time.Time
	Now        time.Time
	MaxRows    int32
}

func (q *Queries) LeaseDueErasureRequests(ctx context.Context, arg LeaseDueErasureRequestsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, leaseDueErasureRequests, arg.LeaseUntil, arg.Now, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountCheckoutSessionIDs = `-- name: ListAccountCheckoutSessionIDs :many
SELECT external_id FROM billing_sessions
WHERE account_id = $1 AND payment_method = 'stripe' AND external_id <> ''
ORDER BY created_at, id
`

func (q *Queries) ListAccountCheckoutSessionIDs(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountCheckoutSessionIDs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var external_id string
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountHistoricalProviderIDs = `-- name: ListAccountHistoricalProviderIDs :many
SELECT p.session_id FROM provider_sessions p WHERE p.account_id = $1
UNION SELECT m.session_id FROM darkbloom_machine_sessions m WHERE m.account_id = $1
`

func (q *Queries) ListAccountHistoricalProviderIDs(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountHistoricalProviderIDs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var session_id string
		if err := rows.Scan(&session_id); err != nil {
			return nil, err
		}
		items = append(items, session_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountHistoricalSEKeys = `-- name: ListAccountHistoricalSEKeys :many
WITH keys AS (
 SELECT se_pubkey FROM provider_trust_reuse
 UNION SELECT se_pubkey FROM code_attestations
 UNION SELECT se_pubkey FROM provider_verification_jobs
)
SELECT k.se_pubkey FROM keys k WHERE k.se_pubkey <> '' AND (
 EXISTS(SELECT 1 FROM darkbloom_machine_aliases a WHERE a.kind='legacy_se' AND a.scope=$1
 AND a.digest=encode(sha256(convert_to('legacy_se','UTF8') || '\x00'::bytea || convert_to(k.se_pubkey,'UTF8')),'hex'))
 OR EXISTS(SELECT 1 FROM erasure_se_owners o WHERE o.account_id=$1
 AND o.se_key_digest=encode(sha256(convert_to('legacy_se','UTF8') || '\x00'::bytea || convert_to(k.se_pubkey,'UTF8')),'hex'))
)
`

// Historical aliases are authenticated, account-scoped legacy SE bindings.
// Never substitute provider_sessions.provider_key (an X25519 transport key)
// or an unverified serial for this ownership link.
func (q *Queries) ListAccountHistoricalSEKeys(ctx context.Context, scope string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountHistoricalSEKeys, scope)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var se_pubkey string
		if err := rows.Scan(&se_pubkey); err != nil {
			return nil, err
		}
		items = append(items, se_pubkey)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountLogReportSerials = `-- name: ListAccountLogReportSerials :many
SELECT DISTINCT serial_number FROM provider_log_reports WHERE account_id = $1 AND serial_number <> ''
`

func (q *Queries) ListAccountLogReportSerials(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountLogReportSerials, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var serial_number string
		if err := rows.Scan(&serial_number); err != nil {
			return nil, err
		}
		items = append(items, serial_number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountProviderKeys = `-- name: ListAccountProviderKeys :many

SELECT id, se_public_key, serial_number FROM providers WHERE account_id = $1
`

type ListAccountProviderKeysRow struct {
	ID           string
	SePublicKey  string
	SerialNumber string
}

// Key collection. Each list is bounded by an indexed account link.
func (q *Queries) ListAccountProviderKeys(ctx context.Context, accountID string) ([]ListAccountProviderKeysRow, error) {
	rows, err := q.db.Query(ctx, listAccountProviderKeys, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountProviderKeysRow
	for rows.Next() {
		var i ListAccountProviderKeysRow
		if err := rows.Scan(&i.ID, &i.SePublicKey, &i.SerialNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountRecipientIDs = `-- name: ListAccountRecipientIDs :many
SELECT DISTINCT (data->>'recipient_id')::text AS recipient_id FROM global_payout_withdrawals
WHERE account_id = $1 AND COALESCE(data->>'recipient_id', '') <> ''
`

func (q *Queries) ListAccountRecipientIDs(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountRecipientIDs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var recipient_id string
		if err := rows.Scan(&recipient_id); err != nil {
			return nil, err
		}
		items = append(items, recipient_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountSessionSerials = `-- name: ListAccountSessionSerials :many
SELECT DISTINCT serial_number FROM provider_sessions WHERE account_id = $1 AND serial_number <> ''
`

func (q *Queries) ListAccountSessionSerials(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountSessionSerials, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var serial_number string
		if err := rows.Scan(&serial_number); err != nil {
			return nil, err
		}
		items = append(items, serial_number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountStripeAccountIDs = `-- name: ListAccountStripeAccountIDs :many
SELECT DISTINCT stripe_account_id FROM stripe_withdrawals WHERE account_id = $1 AND stripe_account_id <> ''
`

func (q *Queries) ListAccountStripeAccountIDs(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAccountStripeAccountIDs, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var stripe_account_id string
		if err := rows.Scan(&stripe_account_id); err != nil {
			return nil, err
		}
		items = append(items, stripe_account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppAttestKeysForSessions = `-- name: ListAppAttestKeysForSessions :many
SELECT DISTINCT key_id FROM app_attest_evidence WHERE session_id = ANY($1::text[]) AND key_id <> ''
`

func (q *Queries) ListAppAttestKeysForSessions(ctx context.Context, sessionIds []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listAppAttestKeysForSessions, sessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key_id string
		if err := rows.Scan(&key_id); err != nil {
			return nil, err
		}
		items = append(items, key_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErasureOutbox = `-- name: ListErasureOutbox :many
SELECT id, request_id, target, external_id, state, attempts, next_at, lease_until, last_error, done_at, created_at, stripe_job_id, stripe_job_status, stripe_job_status_since, stripe_job_generation, lease_generation FROM erasure_outbox WHERE request_id = $1 ORDER BY created_at, id
`

func (q *Queries) ListErasureOutbox(ctx context.Context, requestID string) ([]ErasureOutbox, error) {
	rows, err := q.db.Query(ctx, listErasureOutbox, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErasureOutbox
	for rows.Next() {
		var i ErasureOutbox
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Target,
			&i.ExternalID,
			&i.State,
			&i.Attempts,
			&i.NextAt,
			&i.LeaseUntil,
			&i.LastError,
			&i.DoneAt,
			&i.CreatedAt,
			&i.StripeJobID,
			&i.StripeJobStatus,
			&i.StripeJobStatusSince,
			&i.StripeJobGeneration,
			&i.LeaseGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErasureRefusedCredits = `-- name: ListErasureRefusedCredits :many
SELECT id, account_id, entry_type, amount_micro_usd, reference_hash, reference, created_at FROM erasure_refused_credits WHERE account_id = $1 ORDER BY created_at, id LIMIT 500
`

func (q *Queries) ListErasureRefusedCredits(ctx context.Context, accountID string) ([]ErasureRefusedCredit, error) {
	rows, err := q.db.Query(ctx, listErasureRefusedCredits, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ErasureRefusedCredit
	for rows.Next() {
		var i ErasureRefusedCredit
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.EntryType,
			&i.AmountMicroUsd,
			&i.ReferenceHash,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMDASerialAliasesForErasure = `-- name: ListMDASerialAliasesForErasure :many
SELECT a.digest, EXISTS (
    SELECT 1 FROM darkbloom_machine_sessions s
    WHERE s.machine_id = a.machine_id AND s.account_id <> $1
      AND NOT EXISTS (SELECT 1 FROM erasure_requests r WHERE r.account_id = s.account_id AND r.state = 'erased')
) AS shared
FROM darkbloom_machine_aliases a
WHERE a.kind = 'mda_serial' AND a.scope = '' AND (
 a.digest = ANY($2::text[])
 OR EXISTS(SELECT 1 FROM darkbloom_machine_sessions own WHERE own.machine_id=a.machine_id AND own.account_id=$1)
)
`

type ListMDASerialAliasesForErasureParams struct {
	AccountID string
	Digests   []string
}

type ListMDASerialAliasesForErasureRow struct {
	Digest string
	Shared bool
}

func (q *Queries) ListMDASerialAliasesForErasure(ctx context.Context, arg ListMDASerialAliasesForErasureParams) ([]ListMDASerialAliasesForErasureRow, error) {
	rows, err := q.db.Query(ctx, listMDASerialAliasesForErasure, arg.AccountID, arg.Digests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMDASerialAliasesForErasureRow
	for rows.Next() {
		var i ListMDASerialAliasesForErasureRow
		if err := rows.Scan(&i.Digest, &i.Shared); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedAppAttestKeys = `-- name: ListSharedAppAttestKeys :many
SELECT DISTINCT key_id FROM app_attest_evidence
WHERE key_id = ANY($1::text[]) AND NOT (session_id = ANY($2::text[]))
AND NOT EXISTS (
    SELECT 1 FROM erasure_requests r
    WHERE r.state = 'erased' AND r.account_id IN (
        SELECT account_id FROM providers WHERE id = app_attest_evidence.session_id
        UNION SELECT account_id FROM provider_sessions WHERE session_id = app_attest_evidence.session_id
        UNION SELECT account_id FROM darkbloom_machine_sessions WHERE session_id = app_attest_evidence.session_id
    )
)
`

type ListSharedAppAttestKeysParams struct {
	KeyIds     []string
	SessionIds []string
}

func (q *Queries) ListSharedAppAttestKeys(ctx context.Context, arg ListSharedAppAttestKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSharedAppAttestKeys, arg.KeyIds, arg.SessionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key_id string
		if err := rows.Scan(&key_id); err != nil {
			return nil, err
		}
		items = append(items, key_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedSEKeys = `-- name: ListSharedSEKeys :many
WITH candidates AS (
 SELECT unnest($2::text[]) AS se_key
), owners AS (
 SELECT encode(sha256(convert_to('legacy_se','UTF8') || '\x00'::bytea || convert_to(p.se_public_key,'UTF8')),'hex') AS digest, p.account_id
 FROM providers p WHERE p.se_public_key=ANY($2::text[])
 UNION SELECT a.digest, a.scope FROM darkbloom_machine_aliases a WHERE a.kind='legacy_se'
 UNION SELECT o.se_key_digest, o.account_id FROM erasure_se_owners o
)
SELECT DISTINCT c.se_key::text FROM candidates c JOIN owners o
 ON o.digest=encode(sha256(convert_to('legacy_se','UTF8') || '\x00'::bytea || convert_to(c.se_key,'UTF8')),'hex')
WHERE o.account_id<>$1
AND NOT EXISTS(SELECT 1 FROM erasure_requests r WHERE r.account_id=o.account_id AND r.state='erased')
`

type ListSharedSEKeysParams struct {
	AccountID string
	SeKeys    []string
}

func (q *Queries) ListSharedSEKeys(ctx context.Context, arg ListSharedSEKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listSharedSEKeys, arg.AccountID, arg.SeKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var c_se_key string
		if err := rows.Scan(&c_se_key); err != nil {
			return nil, err
		}
		items = append(items, c_se_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStagedErasureObjects = `-- name: ListStagedErasureObjects :many
SELECT o.target, o.external_id FROM erasure_outbox o
JOIN erasure_requests r ON r.id = o.request_id
WHERE r.account_id = $1 AND r.state <> 'erased' AND o.external_id <> ''
`

type ListStagedErasureObjectsRow struct {
	Target     string
	ExternalID string
}

// A canceled erasure leaves staged external IDs with the live account. A later
// scrub includes them before replacing staging with its complete cleanup set.
func (q *Queries) ListStagedErasureObjects(ctx context.Context, accountID string) ([]ListStagedErasureObjectsRow, error) {
	rows, err := q.db.Query(ctx, listStagedErasureObjects, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStagedErasureObjectsRow
	for rows.Next() {
		var i ListStagedErasureObjectsRow
		if err := rows.Scan(&i.Target, &i.ExternalID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountBillingSessions = `-- name: LockAccountBillingSessions :many
SELECT id FROM billing_sessions WHERE account_id = $1 ORDER BY id FOR UPDATE
`

func (q *Queries) LockAccountBillingSessions(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockAccountBillingSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountGlobalPayouts = `-- name: LockAccountGlobalPayouts :many
SELECT id FROM global_payout_withdrawals WHERE account_id = $1 ORDER BY id FOR UPDATE
`

func (q *Queries) LockAccountGlobalPayouts(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockAccountGlobalPayouts, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountGlobalRecipient = `-- name: LockAccountGlobalRecipient :many
SELECT account_id FROM global_payout_recipients WHERE account_id = $1 FOR UPDATE
`

func (q *Queries) LockAccountGlobalRecipient(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockAccountGlobalRecipient, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var account_id string
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAccountStripeWithdrawals = `-- name: LockAccountStripeWithdrawals :many
SELECT id FROM stripe_withdrawals WHERE account_id = $1 ORDER BY id FOR UPDATE
`

func (q *Queries) LockAccountStripeWithdrawals(ctx context.Context, accountID string) ([]string, error) {
	rows, err := q.db.Query(ctx, lockAccountStripeWithdrawals, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBalance = `-- name: LockBalance :one
SELECT balance_micro_usd, withdrawable_micro_usd FROM balances WHERE account_id = $1 FOR UPDATE
`

type LockBalanceRow struct {
	BalanceMicroUsd      int64
	WithdrawableMicroUsd int64
}

func (q *Queries) LockBalance(ctx context.Context, accountID string) (LockBalanceRow, error) {
	row := q.db.QueryRow(ctx, lockBalance, accountID)
	var i LockBalanceRow
	err := row.Scan(&i.BalanceMicroUsd, &i.WithdrawableMicroUsd)
	return i, err
}

const lockErasureIdentityCleanup = `-- name: LockErasureIdentityCleanup :exec
SELECT pg_advisory_xact_lock(714320, 1)
`

func (q *Queries) LockErasureIdentityCleanup(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockErasureIdentityCleanup)
	return err
}

const lockErasureObservations = `-- name: LockErasureObservations :exec
SELECT pg_advisory_xact_lock(714320, 2)
`

func (q *Queries) LockErasureObservations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockErasureObservations)
	return err
}

const lockErasureOutbox = `-- name: LockErasureOutbox :exec
SELECT id FROM erasure_outbox WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockErasureOutbox(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, lockErasureOutbox, id)
	return err
}

const lockLiveUserForErasure = `-- name: LockLiveUserForErasure :one

SELECT account_id, email FROM users WHERE account_id = $1 AND deleted_at IS NULL FOR UPDATE
`

type LockLiveUserForErasureRow struct {
	AccountID string
	Email     string
}

// Soft delete and cancel.
func (q *Queries) LockLiveUserForErasure(ctx context.Context, accountID string) (LockLiveUserForErasureRow, error) {
	row := q.db.QueryRow(ctx, lockLiveUserForErasure, accountID)
	var i LockLiveUserForErasureRow
	err := row.Scan(&i.AccountID, &i.Email)
	return i, err
}

const lockUserForErasure = `-- name: LockUserForErasure :one
SELECT account_id, privy_user_id, email, stripe_account_id, deleted_at
FROM users WHERE account_id = $1 FOR UPDATE
`

type LockUserForErasureRow struct {
	AccountID       string
	PrivyUserID     string
	Email           string
	StripeAccountID string
	DeletedAt       *time.Time
}

func (q *Queries) LockUserForErasure(ctx context.Context, accountID string) (LockUserForErasureRow, error) {
	row := q.db.QueryRow(ctx, lockUserForErasure, accountID)
	var i LockUserForErasureRow
	err := row.Scan(
		&i.AccountID,
		&i.PrivyUserID,
		&i.Email,
		&i.StripeAccountID,
		&i.DeletedAt,
	)
	return i, err
}

const markErasureCanceled = `-- name: MarkErasureCanceled :exec
UPDATE erasure_requests
SET state = 'canceled', canceled_by = $2, canceled_at = $3, wallet_addresses = '{}', lease_until = NULL
WHERE id = $1
`

type MarkErasureCanceledParams struct {
	ID         string
	CanceledBy string
	CanceledAt *time.Time
}

func (q *Queries) MarkErasureCanceled(ctx context.Context, arg MarkErasureCanceledParams) error {
	_, err := q.db.Exec(ctx, markErasureCanceled, arg.ID, arg.CanceledBy, arg.CanceledAt)
	return err
}

const markErasureErased = `-- name: MarkErasureErased :exec
UPDATE erasure_requests
SET state = 'erased', erased_at = $2, plan = $3, wallet_addresses = '{}', lease_until = NULL, last_error = ''
WHERE id = $1
`

type MarkErasureErasedParams struct {
	ID       string
	ErasedAt *time.Time
	Plan     []byte
}

func (q *Queries) MarkErasureErased(ctx context.Context, arg MarkErasureErasedParams) error {
	_, err := q.db.Exec(ctx, markErasureErased, arg.ID, arg.ErasedAt, arg.Plan)
	return err
}

const markErasurePending = `-- name: MarkErasurePending :exec
UPDATE erasure_requests
SET state = 'pending', actor = $2, reason = $3, wallet_addresses = $4,
    requested_at = $5, scrub_after = $6, confirm_token_hash = '', confirm_expires_at = NULL
WHERE id = $1
`

type MarkErasurePendingParams struct {
	ID              string
	Actor           string
	Reason          string
	WalletAddresses []string
	RequestedAt     *time.Time
	ScrubAfter      *time.Time
}

func (q *Queries) MarkErasurePending(ctx context.Context, arg MarkErasurePendingParams) error {
	_, err := q.db.Exec(ctx, markErasurePending,
		arg.ID,
		arg.Actor,
		arg.Reason,
		arg.WalletAddresses,
		arg.RequestedAt,
		arg.ScrubAfter,
	)
	return err
}

const recordErasureFailure = `-- name: RecordErasureFailure :exec
UPDATE erasure_requests SET last_error = $2 WHERE id = $1 AND state = 'pending'
`

type RecordErasureFailureParams struct {
	ID        string
	LastError string
}

func (q *Queries) RecordErasureFailure(ctx context.Context, arg RecordErasureFailureParams) error {
	_, err := q.db.Exec(ctx, recordErasureFailure, arg.ID, arg.LastError)
	return err
}

const restoreProviders = `-- name: RestoreProviders :execrows
UPDATE providers SET deleted_at = NULL WHERE account_id = $1 AND deleted_at = $2
`

type RestoreProvidersParams struct {
	AccountID string
	DeletedAt *time.Time
}

func (q *Queries) RestoreProviders(ctx context.Context, arg RestoreProvidersParams) (int64, error) {
	result, err := q.db.Exec(ctx, restoreProviders, arg.AccountID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restoreUser = `-- name: RestoreUser :execrows
UPDATE users SET deleted_at = NULL WHERE account_id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreUser(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, restoreUser, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retainErasureSEOwners = `-- name: RetainErasureSEOwners :exec
INSERT INTO erasure_se_owners(se_key_digest, account_id)
SELECT encode(sha256(convert_to('legacy_se','UTF8') || '\x00'::bytea || convert_to(p.se_public_key,'UTF8')),'hex'), p.account_id
FROM providers p WHERE p.account_id=$1 AND p.se_public_key<>''
UNION SELECT digest, scope FROM darkbloom_machine_aliases WHERE kind='legacy_se' AND scope=$1 AND digest ~ '^[0-9a-f]{64}$'
ON CONFLICT DO NOTHING
`

func (q *Queries) RetainErasureSEOwners(ctx context.Context, accountID string) error {
	_, err := q.db.Exec(ctx, retainErasureSEOwners, accountID)
	return err
}

const saveErasureOutboxResult = `-- name: SaveErasureOutboxResult :execrows
UPDATE erasure_outbox
SET state = $1,
    attempts = $2,
    next_at = $3::timestamptz,
    last_error = $4,
    external_id = CASE WHEN $1 = 'done' THEN '' ELSE $5::text END,
    stripe_job_id = CASE WHEN $1 = 'done' THEN '' ELSE $6::text END,
    stripe_job_status = $7,
    stripe_job_status_since = $8::timestamptz,
    stripe_job_generation = $9,
    done_at = CASE WHEN $1 = 'done' THEN $3::timestamptz ELSE NULL END,
    lease_until = NULL
WHERE id = $10 AND state = 'pending'
  AND lease_generation = $11
  AND lease_until > clock_timestamp()
`

type SaveErasureOutboxResultParams struct {
	State                string
	Attempts             int32
	NextAt               time.Time
	LastError            string
	ExternalID           string
	StripeJobID          string
	StripeJobStatus      string
	StripeJobStatusSince *time.Time
	StripeJobGeneration  int32
	ID                   string
	LeaseGeneration      int64
}

func (q *Queries) SaveErasureOutboxResult(ctx context.Context, arg SaveErasureOutboxResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveErasureOutboxResult,
		arg.State,
		arg.Attempts,
		arg.NextAt,
		arg.LastError,
		arg.ExternalID,
		arg.StripeJobID,
		arg.StripeJobStatus,
		arg.StripeJobStatusSince,
		arg.StripeJobGeneration,
		arg.ID,
		arg.LeaseGeneration,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubAPIKeysRows = `-- name: ScrubAPIKeysRows :execrows
UPDATE api_keys SET name = '' WHERE owner_account_id = $1
`

func (q *Queries) ScrubAPIKeysRows(ctx context.Context, ownerAccountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubAPIKeysRows, ownerAccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubAdminNoteLedgerReferences = `-- name: ScrubAdminNoteLedgerReferences :execrows
UPDATE ledger_entries SET reference = entry_type
WHERE account_id = $1 AND entry_type IN ('admin_credit', 'admin_reward') AND reference <> entry_type
`

func (q *Queries) ScrubAdminNoteLedgerReferences(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubAdminNoteLedgerReferences, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubAppAttestEvidenceRows = `-- name: ScrubAppAttestEvidenceRows :execrows
UPDATE app_attest_evidence SET context = '{}' WHERE session_id = ANY($1::text[])
`

func (q *Queries) ScrubAppAttestEvidenceRows(ctx context.Context, sessionIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubAppAttestEvidenceRows, sessionIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubAppAttestReceiptsRows = `-- name: ScrubAppAttestReceiptsRows :execrows
UPDATE app_attest_receipts SET context = '{}' WHERE key_id = ANY($1::text[])
`

func (q *Queries) ScrubAppAttestReceiptsRows(ctx context.Context, keyIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubAppAttestReceiptsRows, keyIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubBillingSessionsRows = `-- name: ScrubBillingSessionsRows :execrows
UPDATE billing_sessions
SET external_id = '', status = CASE WHEN status = 'pending' THEN 'erased' ELSE status END
WHERE account_id = $1
`

func (q *Queries) ScrubBillingSessionsRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubBillingSessionsRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubConsumerRegionRows = `-- name: ScrubConsumerRegionRows :execrows
UPDATE inference_routes SET consumer_region = NULL WHERE consumer_key_hash = $1 AND consumer_region IS NOT NULL
`

func (q *Queries) ScrubConsumerRegionRows(ctx context.Context, consumerKeyHash string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubConsumerRegionRows, consumerKeyHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubGlobalPayoutRows = `-- name: ScrubGlobalPayoutRows :execrows
UPDATE global_payout_withdrawals
SET data = data || '{"recipient_id": "", "payout_method_id": "", "request": {}}'::jsonb
WHERE account_id = $1
`

func (q *Queries) ScrubGlobalPayoutRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubGlobalPayoutRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubPaymentConsumerAddress = `-- name: ScrubPaymentConsumerAddress :execrows
UPDATE payments SET consumer_address = $1 WHERE consumer_address = $2
`

type ScrubPaymentConsumerAddressParams struct {
	Replacement string
	Address     string
}

func (q *Queries) ScrubPaymentConsumerAddress(ctx context.Context, arg ScrubPaymentConsumerAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, scrubPaymentConsumerAddress, arg.Replacement, arg.Address)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubPaymentProviderAddress = `-- name: ScrubPaymentProviderAddress :execrows
UPDATE payments SET provider_address = $1 WHERE provider_address = $2
`

type ScrubPaymentProviderAddressParams struct {
	Replacement string
	Address     string
}

func (q *Queries) ScrubPaymentProviderAddress(ctx context.Context, arg ScrubPaymentProviderAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, scrubPaymentProviderAddress, arg.Replacement, arg.Address)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubProviderPayoutAddress = `-- name: ScrubProviderPayoutAddress :execrows
UPDATE provider_payouts SET provider_address = $1 WHERE provider_address = $2
`

type ScrubProviderPayoutAddressParams struct {
	Replacement string
	Address     string
}

func (q *Queries) ScrubProviderPayoutAddress(ctx context.Context, arg ScrubProviderPayoutAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, scrubProviderPayoutAddress, arg.Replacement, arg.Address)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubProviderRegionRows = `-- name: ScrubProviderRegionRows :execrows
UPDATE inference_routes SET provider_region = NULL
WHERE provider_id = ANY($1::text[]) AND provider_region IS NOT NULL
`

func (q *Queries) ScrubProviderRegionRows(ctx context.Context, providerIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubProviderRegionRows, providerIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubProviderSessionsRows = `-- name: ScrubProviderSessionsRows :execrows
UPDATE provider_sessions SET serial_number = '', disconnected_at = COALESCE(disconnected_at, NOW())
WHERE account_id = $1
`

func (q *Queries) ScrubProviderSessionsRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubProviderSessionsRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubProviderTokensRows = `-- name: ScrubProviderTokensRows :execrows
UPDATE provider_tokens SET label = '' WHERE account_id = $1
`

func (q *Queries) ScrubProviderTokensRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubProviderTokensRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubProvidersRows = `-- name: ScrubProvidersRows :execrows
UPDATE providers SET serial_number = '', location = NULL, attestation_result = NULL, mda_cert_chain = NULL
WHERE account_id = $1
`

func (q *Queries) ScrubProvidersRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubProvidersRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubReferralCodeCopies = `-- name: ScrubReferralCodeCopies :execrows
UPDATE billing_sessions SET referral_code = $1 WHERE referral_code = $2
`

type ScrubReferralCodeCopiesParams struct {
	NewCode string
	OldCode string
}

func (q *Queries) ScrubReferralCodeCopies(ctx context.Context, arg ScrubReferralCodeCopiesParams) (int64, error) {
	result, err := q.db.Exec(ctx, scrubReferralCodeCopies, arg.NewCode, arg.OldCode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubReferrersRow = `-- name: ScrubReferrersRow :execrows
UPDATE referrers SET code = $1 WHERE account_id = $2
`

type ScrubReferrersRowParams struct {
	Code      string
	AccountID string
}

func (q *Queries) ScrubReferrersRow(ctx context.Context, arg ScrubReferrersRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, scrubReferrersRow, arg.Code, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubStripeLedgerReferences = `-- name: ScrubStripeLedgerReferences :execrows
UPDATE ledger_entries SET reference = 'stripe:erased' WHERE account_id = $1 AND reference LIKE 'stripe:%'
`

func (q *Queries) ScrubStripeLedgerReferences(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubStripeLedgerReferences, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubStripeWithdrawalRows = `-- name: ScrubStripeWithdrawalRows :execrows
UPDATE stripe_withdrawals SET stripe_account_id = '' WHERE account_id = $1
`

func (q *Queries) ScrubStripeWithdrawalRows(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubStripeWithdrawalRows, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubUsageLocationRows = `-- name: ScrubUsageLocationRows :execrows
UPDATE usage SET request_location = NULL WHERE consumer_key_hash = $1 AND request_location IS NOT NULL
`

func (q *Queries) ScrubUsageLocationRows(ctx context.Context, consumerKeyHash string) (int64, error) {
	result, err := q.db.Exec(ctx, scrubUsageLocationRows, consumerKeyHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scrubUsersRow = `-- name: ScrubUsersRow :execrows
UPDATE users SET email = '', privy_user_id = $1, stripe_account_id = '',
    stripe_account_status = '', stripe_account_country = '', stripe_destination_type = '',
    stripe_destination_last4 = '', stripe_instant_eligible = FALSE
WHERE account_id = $2
`

type ScrubUsersRowParams struct {
	PrivyUserID string
	AccountID   string
}

func (q *Queries) ScrubUsersRow(ctx context.Context, arg ScrubUsersRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, scrubUsersRow, arg.PrivyUserID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteAPIKeys = `-- name: SoftDeleteAPIKeys :execrows
UPDATE api_keys SET active = FALSE, deleted_at = $2 WHERE owner_account_id = $1 AND deleted_at IS NULL
`

type SoftDeleteAPIKeysParams struct {
	OwnerAccountID string
	DeletedAt      *time.Time
}

func (q *Queries) SoftDeleteAPIKeys(ctx context.Context, arg SoftDeleteAPIKeysParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAPIKeys, arg.OwnerAccountID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProviderTokens = `-- name: SoftDeleteProviderTokens :execrows
UPDATE provider_tokens SET active = FALSE, deleted_at = $2 WHERE account_id = $1 AND deleted_at IS NULL
`

type SoftDeleteProviderTokensParams struct {
	AccountID string
	DeletedAt *time.Time
}

func (q *Queries) SoftDeleteProviderTokens(ctx context.Context, arg SoftDeleteProviderTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProviderTokens, arg.AccountID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteProviders = `-- name: SoftDeleteProviders :execrows
UPDATE providers SET deleted_at = $2 WHERE account_id = $1 AND deleted_at IS NULL
`

type SoftDeleteProvidersParams struct {
	AccountID string
	DeletedAt *time.Time
}

func (q *Queries) SoftDeleteProviders(ctx context.Context, arg SoftDeleteProvidersParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProviders, arg.AccountID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteUser = `-- name: SoftDeleteUser :execrows
UPDATE users SET deleted_at = $2 WHERE account_id = $1 AND deleted_at IS NULL
`

type SoftDeleteUserParams struct {
	AccountID string
	DeletedAt *time.Time
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteUser, arg.AccountID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tombstoneGlobalRecipientRow = `-- name: TombstoneGlobalRecipientRow :execrows
UPDATE global_payout_recipients SET country = '', data = $1 WHERE account_id = $2
`

type TombstoneGlobalRecipientRowParams struct {
	Data      []byte
	AccountID string
}

func (q *Queries) TombstoneGlobalRecipientRow(ctx context.Context, arg TombstoneGlobalRecipientRowParams) (int64, error) {
	result, err := q.db.Exec(ctx, tombstoneGlobalRecipientRow, arg.Data, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateErasurePlan = `-- name: UpdateErasurePlan :exec
UPDATE erasure_requests
SET actor = $2, plan = $3, confirm_token_hash = $4, confirm_expires_at = $5, wallet_hash = $6
WHERE id = $1 AND state = 'planned'
`

type UpdateErasurePlanParams struct {
	ID               string
	Actor            string
	Plan             []byte
	ConfirmTokenHash string
	ConfirmExpiresAt *time.Time
	WalletHash       string
}

func (q *Queries) UpdateErasurePlan(ctx context.Context, arg UpdateErasurePlanParams) error {
	_, err := q.db.Exec(ctx, updateErasurePlan,
		arg.ID,
		arg.Actor,
		arg.Plan,
		arg.ConfirmTokenHash,
		arg.ConfirmExpiresAt,
		arg.WalletHash,
	)
	return err
}

const zeroBalance = `-- name: ZeroBalance :execrows
UPDATE balances SET balance_micro_usd = 0, withdrawable_micro_usd = 0, updated_at = NOW()
WHERE account_id = $1
`

func (q *Queries) ZeroBalance(ctx context.Context, accountID string) (int64, error) {
	result, err := q.db.Exec(ctx, zeroBalance, accountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
